### ISSUE TITLE
Social: Sharing via twitter, facebook

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#122]
As a user, I want to be able to share a link to a hypothes.is annotation and have that annotation contain enough metadata (open graph, twitter card, etc) so that it looks beautiful when shared on other platforms.

**Comment by RawKStar77** [comment]
I've been thinking about this feature in light of via.hypothes.is. Personally as a user, I would rather share the via.hypothes.is link to a page rather than a link to the standalone. We need to do a bit more design thinking around how all this will work on social, so I've added the Epic and Needs Design labels.

**Comment by tilgovi** [comment]
This card is about linking to a single annotation:

- [ ] Card should look not awful in FB
- [ ] Card should look not awful in Twitter

**Comment by RawKStar77** [comment]
> This card is about linking to a single annotation

+1

**Comment by jeremydean** [comment]
i think this is HUGE! i want to be able to share what i'm working on seamlessly and elegantly. i think it's the best possible advertising for what we're doing if it's done right.

BUT i also think sharing a via.hypothes.is annotated page should also be a priority. it's possible the annotated page is really the unit for sharing. and the cards should look good and be branded right.

**Comment by judell** [comment]
#2215

**Comment by nickstenning** [comment]
I'm going to close this. The work described above is done, and while there is obviously *much* more to do on social sharing, we have better places to do that planning now.

**Comment by JakeHartnell** [comment]
:+1:

**Comment by edrex** [comment]
IMO social sharing of annotations is hugely important: it will enable Hypothesis authors to leverage their existing social network audience to promote their Hypothesis annotations, and as a side effect expose a steady stream of social network savvy users to opportunities for engagement with Hypothesis as a tool for social discourse.

I think an important metric for Hypothesis should be the proportion of annotations which receive responses. It is currently vanishingly close to 0, and I think social sharing is the way to bring it up.

@nickstenning #2215 is about sharing via links, not links to individual annotations, and as @tilgovi pointed out, this issue is about sharing individual annotations to Twitter and Facebook with appropriate meta tags to make them look good. I would propose reopening this issue or opening a new one to track that specifically, since AFAICT it is being tracked nowhere else.

**Comment by edrex** [comment]
IMO social sharing of annotations is hugely important: it will enable Hypothesis authors to leverage their existing social network audience to promote their Hypothesis annotations, and as a side effect expose a steady stream of social network savvy users to opportunities for engagement with Hypothesis as a tool for social discourse.

I think an important metric for Hypothesis should be the proportion of annotations which receive responses. It is currently vanishingly close to 0, and I think social sharing is the way to bring it up.

@nickstenning #2215 is about sharing "via" links, not links to individual annotations, and as @tilgovi pointed out, this issue is about sharing individual annotations to Twitter and Facebook with appropriate meta tags to make them look good. I would propose reopening this issue or opening a new one to track that specifically, since AFAICT it is being tracked nowhere else.

**Comment by edrex** [comment]
IMO social sharing of annotations is hugely important: it will enable Hypothesis authors to leverage their existing social network audience to promote their Hypothesis annotations, and as a side effect expose a steady stream of social network savvy users to opportunities for engagement with Hypothesis as a tool for social discourse.

I think an important metric for Hypothesis should be the proportion of annotations which receive responses. It is currently vanishingly close to 0, and I think social sharing is the way to bring it up.

@nickstenning #2215 is about sharing "via" links, not links to individual annotations, and as @tilgovi pointed out, this issue is about sharing individual annotations to Twitter and Facebook with appropriate meta tags to make them look good. I would propose reopening this issue or opening a new one to track that specifically, since AFAICT it is being tracked nowhere else.
