### ISSUE TITLE
Remove compass dependency

### ISSUE THREAD

**Issue by aron** [hypothesis/h#1292]
This is the first step to moving towards using lib libsass[1][2] and removing the ruby dependency in the project. We only use a small (but useful) subset of the compass functions, mainly for polyfilling, so it seems like we can easily include them directly in the project.

I've listed them all out here:

- Clearfix (pie-clearfix)
- Background images (background, background-image)
- Responsive (respond-to)
- Box shadow (box-shadow)
- Transition (single-transition, transition)
- Box model (box-sizing)
- Reset (reset-font, reset-box-model)
- Transition (transition, transition-duration, transition-property, transition-timing-function)
- Transform (scaleX, scale, rotateX)
- Wrapping (force-wrap)
- SVG (stretch-y)

[1] https://github.com/sass/libsass
[2] https://github.com/sass/node-sass

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).

**Comment by nickstenning** [comment]
For what it's worth, we finally managed to do this: #2958.
