### ISSUE TITLE
Feature request:  Howto annotate to a database

### ISSUE THREAD

**Issue by satra** [hypothesis/h#1331]
i'm trying to extract some information from publications (i've appended the list of things i'm going to be searching for). what i would really like to do is to open h.alpha as i view the pdf (which i can) and annotate using these "terms" as i go along (also i can). what would be supercool is if all of this info could itself be turned into an RDF dataset automatically that i can then render/play with. what would also be nice is if i could use a default tag as i do this, so that a tleast i can collect all these annotations.

right now, i'm using a spreadsheet to collect this info, and i think we can do better.

any thoughts/suggestions would be much appreciated.

```
- sample size (N)
- disorder 
- clinical_application (Y/N)
- used_cross_validation (Y/N/not specified)
  - type_of_cross_validation (Leave One Out, Split-Half, ...)
  - had_separate_validation_set (Y/N)
- used_nested_cross_validation
  - for feature selection
  - for parameter selection
  - for model selection
- learning_model (Linear/Logistic Regression, SVM, SVR, RandomForest, ...)
- estimated/determined_feature_importance
- loss_function 
- metric (explained_variance, Pearson correlation, ...)
- significance_testing (t-test, correlation p-value, permutation test, ...)
```

**Comment by satra** [comment]
@BigBlueHat - happy new year - last year ran away in a hurry. having cleared my inbox till last august here is the very belated response!

i think using tags like this is fine. it's just that it would be good for the UI to display the RDFs:label if available for that tag and link out from the tag to the URI when possible. the issue is that in the biomedical field a lot of the tag uris would have numeric identifiers that would be very difficult to parse. 

for examples of numeric identifiers see: http://www.ontobee.org/index.php

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
