### ISSUE TITLE
Add some attributions somewhere

### ISSUE THREAD

**Issue by tilgovi** [hypothesis/h#1400]
We have a NOTICE file that's probably woefully out of date. Apache projects require such a file IIRC, but I did it out of a love of attribution. I'd like to get this sort of information into the application itself somewhere.

We don't need to have it in the root like this. I think that habit comes out of a history of it being next to the LICENSE file and the historical concept of a source release. However, given that JavaScript is not compiled, but rather delivered as code to the browser, I see it as something we should really do to make attribution accessible inside the application. The legal issues here are either not really clear to the world or at least I've never come across a confident statement by a lawyer about what's required. It may never have been tested in any court. And anyway, IANAL, but I do love giving credit to the fabulous projects we depend on.

We could also deliver some messaging about the open source nature of Hypothesis itself and thereby create a bit of a portal into our developer world right from the app.

You'll notice that Google apps on Android typically have an about page somewhere buried in their settings where you can find the various open source licenses.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
