### ISSUE TITLE
Relatively positioned viewer

### ISSUE THREAD

**Issue by aron** [hypothesis/h#1522]
This is a new design for the annotation viewer that uses a Google Docs style method of displaying comments, where each annotation card is "anchored" next to it's corresponding highlight. If more than one card is vying for the same spot then subsequent cards are push downwards.

Demo: http://project.hypothes.is/viewer-prototypes/viewer-3/

The sort options have been moved into a filter bar that currently only hold sort value and ordering options. Clearing a selection is currently done by clicking in the selection gutter (see selected cards mockup), but this may need an explicit action as well.

Basic viewer: https://cloud.githubusercontent.com/assets/47144/4360196/3b580214-4279-11e4-9e22-3b7c0ee56210.png
Viewer filters: https://cloud.githubusercontent.com/assets/47144/4360194/3b52e3e2-4279-11e4-9216-6a4c8623f66a.png
View filters (active): https://cloud.githubusercontent.com/assets/47144/4360193/3b51c93a-4279-11e4-92b8-bd8fd8a7c7dc.png
Selected cards: https://cloud.githubusercontent.com/assets/47144/4360195/3b55e574-4279-11e4-8435-6a863735ad85.png

Pending design:

* Hover states, what happens when you mouseover an annotation card or highlight?

**Comment by judell** [comment]
http://project.hypothes.is/viewer-prototypes/viewer-3/ was intriguing but, as you say, also problematic. Close and tag for future reference? (Tags: h_repo sidebar_document_sync)

**Comment by tilgovi** [comment]
I would say keep it open. It comes up constantly and appears to have rough consensus from the entire team that this would be better than our current sidebar.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
