### ISSUE TITLE
Analyse `uri` field when searching

### ISSUE THREAD

**Issue by tilgovi** [hypothesis/h#1537]
With openannotation/annotator-store just merging the change to use match queries, we can change the analyzer for the `uri` now to tokenize the field and strip things, potentially the protocol, query string, and fragment for instance. This would introduce some optimism in our annotation results to account for poor practices by webmasters serving equivalent content and various uses of queries and hashes that don't dramatically affect primary content.

**Comment by csillag** [comment]
Are we going to do this sometimes soon?

This is needed to make old annotations appear on documents if they were saved with URLs with different hash parts, like (for example)

http://lappland.io/blog/2014/03/open-peer-review-as-annotations/
vs
http://lappland.io/blog/2014/03/open-peer-review-as-annotations/#fn:Diigo link feature

#1872 takes care of the new annotations, but not the old ones.

(Or, alternatively, we could also just migrate our database, but I am strongly for adding automation for this, so that it also solves the problem of the data living in other databases, and the data that is going to be created in the future by old versions of the code, or by different clients that save the hash part as part of the url, etc.)

**Comment by gergely-ujvari** [comment]
I'll experiment with this.
