### ISSUE TITLE
Form network response error messages need style

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#1550]
The login form recently had a new styling for alerts that @aron had created, red background, white text, and positioning underneath the entry fields and above the submit button.

It seems to have slipped from recent branches.

From stage:
![screen shot 2014-10-03 at 2 00 10 pm](https://cloud.githubusercontent.com/assets/1413074/4512461/a3c27fd0-4b40-11e4-97d2-ee39040ce486.png)

From the recent markdown branch https://github.com/hypothesis/h/pull/1548#event-174022051
![screen shot 2014-10-03 at 1 49 04 pm](https://cloud.githubusercontent.com/assets/1413074/4512478/d2b06dfc-4b40-11e4-8cff-77d8d4d1f6b3.png)

**Comment by judell** [comment]
Presumably can be closed, though I don't have the closing PR in hand.

**Comment by tilgovi** [comment]
@seanh @nickstenning did this close with the recent account view changes or are the network / form-wide responses still styled the same way?

**Comment by seanh** [comment]
I think the form-wide responses are still styled in the way that Dan originally complained about

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
