### ISSUE TITLE
When clicking a tag in an annotation card on the stream, update the current search term in the current tab

### ISSUE THREAD

**Issue by aron** [hypothesis/h#1565]
Current behaviour:

1) Visit https://hypothes.is/stream
2) Find an annotation with a tag.
3) Click the tag.

Expected behaviour:

The stream search bar should update with the tag filter term and the stream should update with new annotations.

Actual behaviour:

A new window opens with a stream for that tag.

Currently the stream feels like a jumping off point to open more tabs, the proposed change would make it behave more like a website or web application.

**Comment by judell** [comment]
What Aron expected now occurs.

**Comment by tilgovi** [comment]
Nope. It still opens in a new tab.

**Comment by judell** [comment]
Indeed, sorry, misread the sense of this, retitling to clarify.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
