### ISSUE TITLE
The sidebar hides the original text

### ISSUE THREAD

**Issue by scharf** [hypothesis/h#1654]
In many pages, the sidebar hides the underlying text. For example:

- http://thewebmustdie.com/
- http://www.autodidacts.io/openbci-brain-basics-neurons-structure-and-biology/ (on an iPad)

If there are many annotations it is difficult to switch between the original content and the sidebar, because I have to open close it all the time.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).

**Comment by jbshirk** [comment]
I can't believe this is still a thing  four years later. It's a major UX problem that makes me not want to use h.

![Screenshot_20191228_105610](https://user-images.githubusercontent.com/3949396/71546499-61f36c00-2965-11ea-9cf9-5e1ffc1719a3.png)

**Comment by tilgovi** [comment]
@jbshirk it's still a thing because it reliable, if sometimes less than ideal. Any attempt to do otherwise would involve artificially padding or otherwise altering the page in ways that its own designers did not foresee, which may result in very broken layouts.

I notice you're using Firefox, though. If you have any ambition to fix this, I think Firefox offers a way forward, but might involve some re-architecture. Loading Hypothesis in a Firefox sidebar and then listening to the active tab in order to populate it with the relevant annotations is something that has interested me for a long time.
