### ISSUE TITLE
Messaging around chrome store extension warnings.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#1692]
When you click to install our chrome extension, the following warning is shown.

![screen shot 2014-11-06 at 11 10 41 am](https://cloud.githubusercontent.com/assets/1413074/5062859/5171bb4a-6d84-11e4-9a8f-456edad45699.png)

User feedback says that's quite troubling to some.  We should let users know we're aware of this and why they should trust adding this extension.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
