### ISSUE TITLE
Decide how and when to attempt to load more context in the stream

### ISSUE THREAD

**Issue by aron** [hypothesis/h#1713]
> **tilgovi:** The stream also has holes when replies load before parents. We should probably do something smarter here like show the replies and load the parents on click, something like what Twitter is doing.

Extracted from #1513

**Comment by judell** [comment]
Closing in favor of https://github.com/hypothesis/h/issues/1712?

**Comment by judell** [comment]
Sorry, that was a question not a decision.

**Comment by tilgovi** [comment]
#1712 is closed and describes a specific change. I would say this should remain open, unless we want to close it and any other stream-related issues in favor of starting from a blue sky view of what the stream should be and what use it should serve.

**Comment by tilgovi** [comment]
What's needed is some leadership and guidance from anyone who can put time into thinking critically about the purpose of the stream, its intended use case and navigational behaviors, etc.

**Comment by judell** [comment]
"starting from a blue sky view of what the stream should be and what use it should serve."

I am (obviously) leaning that way. Let's discuss in the next design meeting.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
