### ISSUE TITLE
Fields not generated properly when reloading annotations (on login/logout)

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#1731]
Steps to reproduce:
 - Create an annotation
 - Change the document
 - Verify that now you have a visual diff shown
 - Edit your annotation
 - Change the document *back* to the original
 - Log out (for some reason, I can't reproduce this while logged in)

At this point, the visual diff should be gone - but in same cases, it will still be displayed.
The problem is that the "diff" data leaks to the saved annotation - which is old news. 
The news is that the improperly data is actually displayed on the client side.
(Earlier it was simply dropped.)

**Comment by gergely-ujvari** [comment]
About data flow.
Our client side annotator-store has a list (called `annotations`) which is considered to be all annotations currently loaded into the client side.
When we load annotations from the server-side, it checks for every annotation whether it is in that list. (https://github.com/hypothesis/h/blob/master/h/static/scripts/vendor/annotator.store.js#L145)
If yes, then it just updates the annotation with the properties loaded from the server-side (https://github.com/hypothesis/h/blob/master/h/static/scripts/vendor/annotator.store.js#L118), otherwise it will call the `annotator.loadAnnotations` with the newly loaded ones (https://github.com/hypothesis/h/blob/master/h/static/scripts/vendor/annotator.store.js#L153).

Now, our login/logout flow works the following way:
- We detach the old store plugin from annotator and initialize a new one (https://github.com/hypothesis/h/blob/master/h/static/scripts/controllers.coffee#L51)
- Based on the visibility, user, etc. we select annotations to drop and annotations to keep. (https://github.com/hypothesis/h/blob/master/h/static/scripts/controllers.coffee#L77)
- We set the `store.annotations` (for the new store) to only the annotations we want to keep (https://github.com/hypothesis/h/blob/master/h/static/scripts/controllers.coffee#L90) and drop the rest
- And as the new store loads the annotations (this happens automatically by adding the plugin) and yes, the annotations we wanted to keep are just updated, the newly loaded ones go throught the standard load/anchoring procedure.

And because of this the visualdiff is gone, because we store data inside `annotation.document` regarding the visual diff. But when the annotations are loaded, the store plugin overwrites ` `annotation.document` data with the server side side, which do not have the visual diff stored, and hence login/logout makes the visual diff disappear.

Comments:
- Visual diff data shouldn't be saved in the server side. It we were to solve this, it wouldn't disappear.
- The old-store new-store hack in the `initStore()` function is downward ugly, but hopefully Annotator 2.0 will fix this.
- There can be a timing issue alas if the newly set store loads faster the new annotations, when we select the ones to keep then we'll feed it a false .annotations list but I doubt it'll ever happen.

**Comment by tilgovi** [comment]
This thread is just too muddled and confusing and as far as I can tell #1207 (and any migration needed) would, in fact, fix this. If someone disagrees strongly enough and cares to explain they can try to clearly lay out why, in fact, that would not be sufficient.
