### ISSUE TITLE
As a user, I would like to be able to edit the selection

### ISSUE THREAD

**Issue by JakeHartnell** [hypothesis/h#1772]
A [request](https://hypothes.is/a/Z1d0KKtfSQajQxIj96f1wA) that came up during one of the user tests. As a user, I should be able to edit the selection of an annotation. 

Personally, when using hypothes.is I've often made the wrong selection (for example sometimes I select a couple of sentences and decide as I'm writing the annotation that I should only target one of the sentences), and have wanted this feature. I also think it relates a bit to the work to be done on Orphaned annotations, providing users with the ability to reattach their comment if need be.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
