### ISSUE TITLE
Fragment Identifiers in Annotation Target Links

### ISSUE THREAD

**Issue by shepazu** [hypothesis/h#1837]
Currently, each annotation links back to the target document at the root level. For example, I made an [annotation](https://notes.webplatform.org/a/0xqc3-4NTIOKFW_1hiImOg) that links to the [Web Audio API document](http://www.w3.org/2014/annotation/experiment/webaudio.html). This is good, because the user can copy the extracted blockquote and usually find the selection via the browser's find-in-page API. (This is the same link that is sent in our custom email notifications, BTW.)

However, it would be even better if that link were more discrete, and pointed to the selection's nearest ancestor fragment identifier. For example, the annotation above would point to the ["sampleRate" section of the Web Audio API document](http://www.w3.org/2014/annotation/experiment/webaudio.html#dfn-sampleRate).

This is an accessibility issue (and a fairly urgent one for us), but also just a basic usability issue. It makes finding the context of the annotation much easier if the user is not coming from the sidebar (e.g. the web repo, or an email).

I don't know if this information is already collected when you find your robust anchoring selectors, but my intuition says that it is. Would this be reasonably easy to add, in the clientside and in the backend? If it's a relatively small change to our local installation, we'd like to do this in advance of any major Hypothesis/Annotator releases.

__Note__ that this is different than #1090, because I'm asking for the direct fragment identifier link to be stored and added, but not used as the canonical target URL for determining when an annotation applies.

**Comment by tilgovi** [comment]
Not collected already. Not too hard to add.

**Comment by csillag** [comment]
#1872 touches on this.

**Comment by judell** [comment]
Tagged with document_equivalence because it's related to that in ways I don't yet fully understand but need to.

**Comment by tilgovi** [comment]
There are a few different things going on here.

First, we do collect fragment selectors. On master, there are two bugs, both solved already on anchoring-rewrite: a blank FragmentSelector is stored when there's no applicable fragment identifier and when a fragment identifier is stored it's stored with the value `#id` rather than simply `id`.

Second, there's the stream/navigational/direct-linking issue of having the link back to the source get at least to the fragment, if not to the exact quote, when the user navigates that link.

So, I would say we should maybe make sure we target the second of these with this issue.

**Comment by nickstenning** [comment]
@tilgovi Can this be closed?

**Comment by tilgovi** [comment]
I believe so.

**Comment by shepazu** [comment]
Does this work, now?

**Comment by tilgovi** [comment]
The stored target source URLs should not have fragments and there should be a FragmentSelector with the nearest fragment identifier from ancestors.

**Comment by shepazu** [comment]
I'm not sure if that answers my question. My request was not about the internal model, but that the link in some views of an annotation, for example in the livestream view or an email notification (but not the sidebar view), should contain the fragment id so it navigates to the right part of the target document when it's navigated. This is a UX request.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
