### ISSUE TITLE
Cannot edit or delete annotations at JEP

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#1843]
Go here:
- http://quod.lib.umich.edu/j/jep/3336451.0017.201/--new-feature-article-annotation-with-hypothesis?rgn=main;view=fulltext
- Create an annotation.
- You cannot edit or delete the annotation.

Example:

![screen shot 2015-01-12 at 6 42 17 am](https://cloud.githubusercontent.com/assets/1413074/5704533/3a9d4888-9a27-11e4-9926-b18b1d8c3f15.png)

**Comment by gergely-ujvari** [comment]
My guess is that these annotations actually never got saved to the backend.

**Comment by dwhly** [comment]
Appears to be the case.  Is anyone else not able to save annotations at JEP right now?

**Comment by gergely-ujvari** [comment]
Yes. I've tried to create one too and it wasn't saved.

**Comment by dwhly** [comment]
We should both figure out what's going on, but also issue some sort of error or alert that's visible if we can't save.

**Comment by tilgovi** [comment]
Everything appears to be working fine right now, though slowly. I suspect the server is a bit overloaded and I'll see what happens if I shift statsd/graphite off it. My guess is that it's memory constrained (it's not CPU constrained) and the Elasticsearch instance inside the graphite/statsd container is a memory hog.

As for API errors, we have #755 that is closed in favor of #1298, which I conveniently started work on over the weekend and have pushed as the store-resource branch.

In light of all this, I'm going to close this issue since it doesn't describe any original bug I can see.
