### ISSUE TITLE
LateX errors fail silently and confuse user

### ISSUE THREAD

**Issue by Treora** [hypothesis/h#1898]
Writing an erroneous formula in LateX resuts in the rendered content not updating at all. Clicking 'Preview' then shows the last succesful render, and clicking 'Save' does so too (until page reload, which shows an empty annotation).
Desirable improvements, from basic to nice:
- [ ] Show an error that rendering failed when pressing Preview or Save. (bare minimum fix)
- [ ] In the error message (or in the editor), link to an overview of supported latex.
- [ ] Tell in the error message what the error was (e.g. "unknown latex command \bf").
- [ ] Render the rest of the annotation normally, and in place of the failing formula show an error symbol, which shows the error message on hover.

Future improvements could be to support more commands (why do `\bf` or `\textbf` fail?), and having a wysiwyg editor for direct feedback (and as writing aid), but both are separate issues.

**Comment by RawKStar77** [comment]
+1 This can all easily be done from markdown directive.

**Comment by mbbaig** [comment]
Hi. I want to work on this bug. Any help on getting started?

**Comment by tilgovi** [comment]
The code for calling the LaTeX renderers is in h/static/scripts/directive/markdown.coffee.

Right now we use Katex with a MathJax fallback. With KaTeX, we are catching errors and then just enabling the fallback.

I suspect we might want to get rid of the MathJax fallback, and then inform the user if Katex cannot render the math.

We added the fallback initially because Katex had very limited support comared to MathJax.

However, it's clearly more complicated to have two different ways of rendering LaTeX.

I happen to think Katex is much simpler to use, and we are a couple versions behind now, which means the support may be good enough for us.

**Comment by tilgovi** [comment]
Or if we want to preserve MathJax, we should figure out how to use it with more control, so we know when there are errors.

This might also be interesting to look at to help compare: http://www.intmath.com/cg5/asciimathml-katex-mathjax.php

**Comment by dwhly** [comment]
> This might also be interesting to look at to help compare: http://www.intmath.com/cg5/asciimathml-katex-mathjax.php

Nice find... (here are some things that still fail w/ Katex
http://www.intmath.com/cg5/katex-mathjax-comparison.php)

**Comment by mbbaig** [comment]
Okay lots of information there thanks :sweat_smile:  . Let me just take a look at everything and get back to you with any questions that I might have.
