### ISSUE TITLE
Highlight is not removed from document when an annotation is deleted in a different window

### ISSUE THREAD

**Issue by aron** [hypothesis/h#1928]
Steps to reproduce:

1) Open two windows (**a** and **b**) with the sidebar open in a document.
2) Turn on "always on highlights" in **b** window.
3) Create an annotation in **a**, it should appear in **b**.
4) Delete the annotation in **a**.

Expected behaviour:

The annotation should be removed from the sidebar and the document in both **a** and **b**.

Actual behaviour:

The annotation is removed from both document and sidebar in **a**.
The annotation is removed from the sidebar in **b** but the highlight remains in the document.

**Comment by csillag** [comment]
Thanks, I'll fix this one.

**Comment by csillag** [comment]
I didn't quite follow the latest X-frame work. Could someone please fill me in where is the new entry point when the operation to delete an annotation enters the guest frame?

Or better yet, where are the design documents / diagrams / etc about our new cross-frame architecture?
Thanks.

**Comment by tilgovi** [comment]
See `_channelListeners` in scripts/annotation-sync.coffee

**Comment by aron** [comment]
@csillag general changes and architecture are described in the PR here https://github.com/hypothesis/h/pull/1878#issue-55179939 (main changes from the diagram are that "toolkit" was renamed to "ui")

**Comment by aron** [comment]
Oh, just an additional comment to say that the architecture isn't new, it still uses the same design and messages. The logic was just split out into more understandable pieces especially the `Hypothesis` and `Bridge` components.

**Comment by csillag** [comment]
So, I understand what's happening here, but I am not sure about how to solve the problem. I need some input about the intended working of the cross-frame and the live update subsystems.

Basically, when we [receive](https://github.com/hypothesis/h/blob/9da628e66599f6195d60477cdaf1844a36eacc90/h/static/scripts/controllers.coffee#L53) delete request from the stream, we just [emit](https://github.com/hypothesis/h/blob/9da628e66599f6195d60477cdaf1844a36eacc90/h/static/scripts/controllers.coffee#L51) an `annotationDeleted` event with the vanilla objects the we received on the wire, without any attempt to look up our existing annotation object with the same it.

When the `annotationDeleted` event attempts to cross the bridge (from the sidebar to the guest side), it's [rejected](https://github.com/hypothesis/h/blob/9da628e66599f6195d60477cdaf1844a36eacc90/h/static/scripts/annotation-sync.coffee#L119), because the annotation shipped with the event does not have a `$$tag`. (Which is normal, since it has never crossed the bridge before.) Hence annotation deleted event never reaches the guest frame, and that's why the highlights (and the anchors, and the annotations) remain there.

To get the event across the bridge, we would need to use the same annotation object that we already have in the sidebar, and not the new one that we received on the wire. So I guess we should just take the ID, and look up the annotation object. (Why do we sent the body of the deleted annotation anyway in in the live update stream? Wouldn't the ID be sufficient?)

Anyway, what I don't know is where are we supposed to do the lookup. My guess is the [`AnnotationMapperService`](https://github.com/hypothesis/h/blob/9da628e66599f6195d60477cdaf1844a36eacc90/h/static/scripts/annotation-mapper-service.coffee#L27), but I would like some comments from those who designed this subsystem.

**Comment by csillag** [comment]
> Anyway, what I don't know is where are we supposed to do the lookup. My guess is the [`AnnotationMapperService`](https://github.com/hypothesis/h/blob/9da628e66599f6195d60477cdaf1844a36eacc90/h/static/scripts/annotation-mapper-service.coffee#L27), but I would like some comments from those who designed this subsystem.

Or maybe in the controller that is receiving the realtime update event?
Around [here](https://github.com/hypothesis/h/blob/9da628e66599f6195d60477cdaf1844a36eacc90/h/static/scripts/controllers.coffee#L51) ?

**Comment by csillag** [comment]
> Or maybe in the controller that is receiving the realtime update event?
Around [here](https://github.com/hypothesis/h/blob/9da628e66599f6195d60477cdaf1844a36eacc90/h/static/scripts/controllers.coffee#L51) ?

See my initial shot in PR https://github.com/hypothesis/h/issues/1949 - but feel free to correct me if this is not how it was originally dreamed up to work.
