### ISSUE TITLE
FF extension does not seem to be loading annotations over PDF files

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#1954]
Steps to reproduce:
 - Launch FF (if not running)
 - Install [H add-on](https://addons.mozilla.org/en-US/firefox/addon/hypothesis/) (if not installed)
 - Visit http://www.education.gov.yk.ca/pdf/pdf-test.pdf
 - Activate the add-on

Expected result: annotations are loaded from the server.

Actual result: annotations are not loaded from the server.

If the network monitor is open, we can clearly see that no `/search` requests are sent to the server.

If, by contrast, we do the same with the bookmarklet, it will send search requests, and load annotations.

**Comment by csillag** [comment]
Debugging this depends on https://github.com/hypothesis/h/issues/1956

**Comment by BigBlueHat** [comment]
@csillag or...we can figure out the commit sha @aron built the FF 0.3.2.1 extension from.

**Comment by csillag** [comment]
We could, but the FF 0.3.2.1 extension is not our best build ever, either. I mean, I can't get an adder on HTML, it doesn't load annotations on PDF....

I would prefer if we could work with master.

**Comment by BigBlueHat** [comment]
Agreed. Just saying we have other options for figuring out what's wrong with 0.3.2.1

Also...we need to start tagging releases (of *anything*).

**Comment by aron** [comment]
Hey, so I forgot to document this.

The Firefox extension is currently built from this PR https://github.com/hypothesis/h/pull/1813 as we require unminified assets. It's pretty outdated now (I was hoping that the browserify branch would replace it, but as always that was more complicated than it looked).

So 0.3.2.1 is built from the above branch with the ".1" added to the package.json manually to get past the Mozilla requirement for different version numbers (This should also use something similar to the Chrome extension where a build specific number is generated).

Once the extension is built using the documented commands, then all non embed assets need to be deleted before submission. This leaves only `hypothesis.js` and `hypothesis.css` and `jquery.js` in `/data` as I recall. The FF extension loads the sidebar from https://hypothes.is due to restrictions on iframes loading files over the `resource://` protocol. So we don't require any of the other files.

As for what's wrong with it, I never got to the bottom of it, but I assume it's conflicts between the older hypothesis.js file and the newer sidebar (app.js etc) deployed to production. Ideally we should never be in the position where we run different versions in two places, but that means working around the iframe issue. So I think the next step would be to get an unminified version of current master built and submitted, likely by finishing the browserify branch. Then looking at how to inject an iframe containing html loaded from the extension to resolve the larger issue.

**Comment by csillag** [comment]
> I assume it's conflicts between the older hypothesis.js file and the newer sidebar (app.js etc) deployed to production. Ideally we should never be in the position where we run different versions in two places, but that means working around the iframe issue. 

This is exactly why we got rid of the same hybrid extension packaging method for the Chrome Extension, as soon as possible.

**Comment by tilgovi** [comment]
Make sure you don't have minified assets lying around:

    $ git clean -dxf h/static/scripts/vendor

Build from development.ini to get unminified assets:

    $ hypothesis extension development.ini https://hypothes.is resource://firefox-at-hypothes-dot-is/hypothesis/data

Remove extra stuff from the scripts directories (everything except hypothesis.js):

    $ rm app.js account.js session.js helpers.js

Remove extra stuff from vendor directory:

    $ rm annotator* chai.js sinon.js Markdown* unorm.js uuid.js jstz.js jwz.jz
    $ rm -rf katex

You can remove these polyfill, too. I think promise _should_ be conditionally included by embed.js, but it isn't right now. The rest I don't believe are used by the injected code.

    $ rm autofill-event.js bind.js promise.js url.js

Remove these styles:

    $ rm app.css topbar.css

I have no idea which, if any, images are needed.

Copy the bootstrap script over to the data directory along with h/static/icomoon.css.

At this point I have a working extension, but clearly our build script has lots of problems!!

**Comment by csillag** [comment]
> At this point I have a working extension, but clearly our build script has lots of problems!!

Hey, you can produce a working FF extenstion with just these few lines, instead of the 700+ lines code change that has been proposed in https://github.com/hypothesis/h/pull/1813 ?

**Comment by tilgovi** [comment]
Yes.

**Comment by tilgovi** [comment]
Removing this in favor of #1956

**Comment by BigBlueHat** [comment]
Should `make clean` handle removing the minified versions or the Firefox build process?

/me is making issues for all the things [above](https://github.com/hypothesis/h/issues/1954#issuecomment-74970756)

**Comment by tilgovi** [comment]
@BigBlueHat `make clean` does handle removing minified build artifacts that wind up in the `h/static` tree, but it does not clear the `build` directory where the extension go. It could. It's not really important. The build script wipes the output directory for extension builds at the start of the script anyway.

**Comment by tilgovi** [comment]
What's at issue for the built assets is that we're doing a copy of the assets directories to the output directory, I think. For Chrome, we have no problem, because we just set the webassets base directory to the build directory so the minified files get output to that place. For firefox, the assets don't pass through the webassets pipeline, so they're never processed, concatenated, and output anywhere. They stay where they start. So, we just naively copy that directory to make sure they make it into the build. Problem there is that if you've run locally with minified assets you'll have minified assets in your tree.

Probably, we could actually traverse the bundles and pull out the files that are included and copy them one by one, rather than doing a copy of the whole scripts directory.

**Comment by tilgovi** [comment]
@BigBlueHat but let's keep the rest of this discussion on #1956
