### ISSUE TITLE
Single Annotation card view of a reply should link to it's parent

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#1959]
As a user viewing a reply annotation "card" view directly,
I want to know what it's an annotation of,
so that I can view it in context.

For instance:
https://hypothes.is/a/7bHDnNmzRJ2O2HxAP-OrFQ
is a reply to:
https://hypothes.is/a/U4klFvnQS1aKWBysiDOYSA

Relates to #1712 (which is about cards in the Stream) and #1713 (context and Stream related). For clarity, this is *not* about the Stream, but about the standalone card view.

Acceptance criteria:
* [ ] Users can browse to parent from a reply's card view

Proposal:
* [ ] Make card's header state that it's a reply when in card / standalone view: "{user} in reply to {other_user} on {document.title / url}"

**Comment by dwhly** [comment]
@BigBlueHat can you create this in vision instead?

**Comment by BigBlueHat** [comment]
@dwhly what's the motivation for putting it in `vision` vs. here? I see it as a bug in `h`.

**Comment by dwhly** [comment]
I'm not sure I'd call it a bug.  I think it's an obvious deficiency. 

Anyway.  Things that are in vision are managed as product, they might need design work for instance before an engineer can pick them up-- or they might bear directly on other design work ongoing or contemplated.  Things that are in h are things engineers can pick up and manage the backlog of independently.  Bugs, refactoring, architectural work, etc.  Mostly they should be mangaged as part of a single product prioritization backlog.

This is my understanding per the more recent discussion that @tilgovi @nickstenning and I had.  

By that conceptualization, this probably belongs in vision.

**Comment by tilgovi** [comment]
Seems reasonable in either place.

**Comment by dwhly** [comment]
I guess the rationale for having it in vision is so I don't have to create a duplicate card for it there, since we've decoupled h from https://huboard.com/hypothesis/vision/#/

**Comment by tilgovi** [comment]
Who says you can't?

**Comment by tilgovi** [comment]
Remember, you're not responsible for closing this one. If you create another card in vision for this issue, it's not really duplicating work, it's coordinating.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
