### ISSUE TITLE
API variation of #1959 - linking from reply to parent

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#1960]
The JSON for replies are confusing as...
* the `references` key is an ID not a URL
* there is no `target` array
* and the `uri` value is the URI of the page the parent annotation is for (and not, as expected) the annotation this reply is in reply to.

Options:
* switch to using `target` (with no selectors?) in place of `references`
* or make `references` an array of URLs rather than IDs (backwards compatibility issues abound here...)

Also, might be a good time to add a `motivatedBy` key...to prep for more complete Open Annotation support.

**Comment by BigBlueHat** [comment]
The non-UI variant of #1959 (mentioning here 'cause mentioning in the title didn't get me any link :sparkles: magic :sparkles:).

**Comment by tilgovi** [comment]
:+1: to using target instead of `references`.
:+1: to using target instead of `uri`.

I'd separate `motivatedBy` for the moment because I would like to roundtrip that rather opaquely. I feel it's for the client/user to determine the motivation and not something that could be added by a server. The other two are proper busted as is and should definitely align with OA through targets.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
