### ISSUE TITLE
Clicking on the number of replies folds the thread-sub tree

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#1964]
We have a bit of a confusing behavior with the number of replies. When the tread below is hidden, it opens it, but when you click it on an open thread it hides/collapses the current thread
Like:
![reply-folding](https://cloud.githubusercontent.com/assets/2094134/6287675/92031278-b913-11e4-82a0-edcb4b9a95b2.png)

Result:
![repy-folding-after-click](https://cloud.githubusercontent.com/assets/2094134/6287677/94ae6252-b913-11e4-8460-feee6aadaebb.png)

And this is not intuitive enough for new users

**Comment by tilgovi** [comment]
We should fix this at some point. I think the simplest thing would be to make the number of replies simply not a clickable thing, but then the top level annotation needs to have an expander.

The most confusing thing is this non-uniformity of behavior between the top level and the replies.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
