### ISSUE TITLE
More clearly distinguish Page Comments from Highlight-based Annotations

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#1984]
#1386 is for the editor. This one's for the sidebar.

IIRC there was some design done by @aron that had "dividers" sitting between the lists of cards.

Might also be interesting to explore stacks or piles of cards to represent the two collections:
http://semantic-ui.com/elements/segment.html#piled

Maybe. :smile:

**Comment by judell** [comment]
Reactivating this based on feedback from @jeremydean. 

"ALL page level annotations should be anchored to top somehow. (it's confusing to see them throughout IMO.)"

**Comment by tilgovi** [comment]
They're currently anchored at the bottom, I thought.

**Comment by jeremydean** [comment]
thinking through this more. 

is there anyway to allow user to anchor them wherever they want by some kind of more regional selection mechanism?

that is, i could anchor to top or bottom or to any particular space within the text, but some marker would indicate exactly where. [crocodocs](https://crocodoc.com/see-it-in-action/) allows "area" (draw a box) and "point" annotation (place a sticky)--i prefer the latter:

![image](https://cloud.githubusercontent.com/assets/3261902/7685107/61b4181c-fd59-11e4-85c0-b53d4e553e91.png)

this would allow page-level annotations in the sense of top-level (this article is generally about x), but also page *region* annotations (this is the passage that x).

design wise: i think it would be cool if either of these options turned into a kind of marginal sticky notifying user that there was something to see there.

![dsc_0002](https://cloud.githubusercontent.com/assets/3261902/7685173/09edfa2a-fd5a-11e4-87b1-53a3fa5ef65e.jpg)

**Comment by haristephenkumar** [comment]
+1 for Jeremy's suggestion. I'm working with faculty at Amherst College on piloting the use of annotation tools for reading assignments, and a regional selection capability is exactly what we are looking for. Another annotation tool, nb.mit.edu, offers that capability, but we would very much like to see this in hypothes.is as well. The crocodocs example is a great prototype to follow too.

**Comment by judell** [comment]
@haristephenkumar, can you say a bit more about the benefits of alternative target selection?

**Comment by haristephenkumar** [comment]
@judell, sure:

(1) I have faculty who create PDFs by scanning chapters or selected passages from books. These scanned PDFs are usually not OCR'able, or the OCR quality is wonky, so text selection either doesn't work or is jittery. For these kinds of PDFs, faculty would prefer that students be able to select a region of the page or put a sticky on the page to anchor their comment rather than select a specific sequence of text.

(2) Some of the scanned PDFs contain images along with the text, such as maps, charts, pictures, artwork, etc. (For example, I worked with a professor of religion who had his students reading manuscripts containing essays about religious artifacts, which often included pictures of art embedded with the text.) Text-based selection would not allow students to anchor a comment to a graphic or a chart on the page.

(3) Overall, the alternative target selection modes allow for a wider range of comment scopes, as @jeremydean pointed out above. So, for example, selecting a region on the page allows for comments oriented at the paragraph level or page level ("I have a general comment about these three paragraphs") without having to select all the sentences for the entire paragraph or page. The text-based selection mode is akin to underlining, whereas the region-based selection mode is akin to making a note in the margin alongside a larger body of text or scribbling an overarching remark on the top or the bottom of the page. When annotating a physical text, I don't underline an entire paragraph in order to make a comment about the paragraph. Rather, I draw a box around the para or a line down the side of the para in the margin with a short note in the margin remarking on the para. That's the kind of approach I'm looking for from the alternative target selection modes.

**Comment by judell** [comment]
@haristephenkumar thanks for the clarification. Regarding 1 and 2, image annotation is a core capability that is available in other annotation systems built on the AnnotatorJS library that Hypothesis also uses, and will be available in Hypothesis.

3 I still don't fully understand. Drawing a box around a para, or a line down the margin, presumes a fixed layout. So, this would apply only to PDFs? Given that Hypothesis can (and does) anchor annotations to both PDF and HTML representations of the same document, what would happen to box-anchored annotations made against a PDF when viewing the same document in HTML?

**Comment by jeremydean** [comment]
@judell if you table @haristephenkumar example of drawing a box, i think we can agree that being able to stick a note to a region on a page (PDF or URL) would be useful, especially as regards actually annotating web pages (and noting formatting, images, etc.)

on a related note, i've been revisiting diigo, which allows you to stick add a sticky note to a region on the page. their design is terrible. and i remember webpages with lots of sticky notes being a poor reading experience when i used d to teach, BUT, i like the general idea: i want to mark a larger part of this text (a paragraph, a section beginning "here," the top of a page for a broad comment about the overall work, etc. 

![screen shot 2015-05-28 at 3 17 21 pm](https://cloud.githubusercontent.com/assets/3261902/7868947/5b4d1a0e-054d-11e5-9977-7a713d73503a.png)
 
my preference would be for some kind of elegant marginal digital sticky as pictured below. this would not cover everything hari is concerned about, but would be a start i think.

![6a0148c5f37eca970c0147e17e0bca970b](https://cloud.githubusercontent.com/assets/3261902/7869011/d872f3dc-054d-11e5-97aa-1cb537754eb3.jpg)

**Comment by haristephenkumar** [comment]
@judell On 1 and 2, I'm not specifically asking for image annotation, but since you mention that it will be available in Hypothesis can you give me an estimated timeframe for when that will happen? All I'm asking for is the ability to select a region on a PDF as an anchor for an annotation.

On 3, I mentioned drawing a box and drawing a line as examples of how I do annotations on actual printed text, not on PDFs. I used those examples to show how certain annotations have a different scope or purpose than annotations made at the level of a sentence or piece of text. Hence my example about if I wanted to make a comment about a paragraph, on an actual book or printed text, I wouldn't want to underline every line of the paragraph. So too on the electronic version of the text, to make a comment about an entire paragraph or a larger section of the text, there should be some way of doing so without having to underline (highlight/select) all the lines of the paragraph.

Regarding both PDF and HTML representations of the same document, I'm not sure I'm clear on what you mean. I assume you mean only in those instances where the PDF version of the document is OCR'able, i.e. where the HTML representation of the PDF is a straightforward rendering of just the textual content of the PDF? That is, are you assuming that the PDF version of the document contains just plain text and that the HTML version would be the same text? If so, then my answer to your question is: the annotation should stay close to the same area of the text where the box-anchor was in the PDF, perhaps using the top-right corner as the closest indicator of a "sticky" marker. In such a scenario, I'm with @jeremydean in prefering the "sticky note" approach rather than a selection box.

But for PDFs that do NOT have OCR content, i.e. PDFs that are not just text-only content or have a mixture of text and images, then yes, I guess the box-anchor would apply only to the PDF version of the document.

**Comment by haristephenkumar** [comment]
Just saw @jeremydean's comment and his photo of the sticky notes on the sides of the paper. Yes, exactly, :+1: to his suggestion of "some kind of elegant marginal digital sticky."

**Comment by haristephenkumar** [comment]
@jeremydean said: "i think we can agree that being able to stick a note to a region on a page (PDF or URL) would be useful, especially as regards actually annotating web pages (and noting formatting, images, etc.)"

Yes, I agree, well put. Such a capability would allow annotating more than just the text on a web page, since sticking a note on a webpage would allow users to annotate and comment on many other aspects of the page -- formatting, images, graphics, styles, positioning of other content types on the page, etc.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
