### ISSUE TITLE
Lack of offline highlighting (at least) storage is quite painful

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#2008]
0. You don't know if you're logged in without opening the sidebar.
1. However, it's quite possible to turn on Highlight Mode and make highlights without being logged in.
2. But, if you browse away from that page (thinking all is well).
3. You will be disappointed, :cry: in your :tea:, etc.
4. Because they're not stored anywhere...

Logging in--if you happen to look in the sidebar and realize you're not...--*will* store them into your account (which is great!).

What should happen is that we use localStorage (or PouchDB or something!) to keep these highlights around in that browser until such time as the person logs in.

Obviously there are scenarios where a single browser may be used by more than on person, so someone else's highlights could end in your account (they make the highlights, close the browser, you re-open it, and save them), but I think that's an edge case and worth the "risk"--additionally, having highlights on be default (and other things we've discussed) would help alleviate that problem.

**Comment by csillag** [comment]
Obviously, this was not designed (and implemented) to work the way you have described (using your data).

When you try turn on highlight mode without being logged in, the user used to be redirected to the login screen, and the highlight mode couldn't be activated unless the user logged in. (Similarly, logging out automatically disabled the highlight mode.)

This used to break on one (or two) of the earlier refactorings ... then I fixed it ... and now it looks like it's broken again. I guess this is because we don't really have full auto-test coverage for it, and it's also not in the immediate forefront of attention when doing end-user testing after refactorings ....

... and so now it's broken again :(

Sorry for your loss.

**Comment by BigBlueHat** [comment]
It's actually not mine, but someone from support@.

I think I'd prefer to be able to highlight without logging in, and be asked to login if I try to leave page perhaps.

Regardless, we should put this on the roadmap somewhere or other--especially (if, as you say @csillag) it's a regression.

**Comment by tilgovi** [comment]
It was a conscious decision on my part to remove the code that forced users to log in because:

- The code was tricky and therefore broke often
- It's a nasty time to interrupt a user

:+1: for an offline storage solutions
In the meantime, I'd also be :+1: a warning when navigating away from a page.

**Comment by tilgovi** [comment]
Okay, if there's a concrete proposal for a change here it needs to get some love and find its way into our product pipeline or come back with a PR.

In the meantime, we have hypothesis/vision#45 to track offline annotating, so I'm going to close this.

**Comment by hftf** [comment]
Please reinstate a login screen before letting the user annotate, or at least add a highly visible warning, if offline annotations will never be/until it will be fully implemented.
