### ISSUE TITLE
Can't use debugger.

### ISSUE THREAD

**Issue by RawKStar77** [hypothesis/h#2011]
Recently I was trying to use the debugger in a directive like so:
```
    controller: ($scope, $element, $attrs) ->
    	$scope.viaLinkVisible = false
    	$scope.viaPageLink = 'https://via.hypothes.is/h/' + window.location.origin
        debugger
```
This threw a 500 server error. Removing debugger fixed the problem. I tried it in another directive and the same thing happen. 

To reproduce use debugger in a directive, and reload the page... a 500 server error is thrown.

@gergely-ujvari was able to confirm this happening on IRC and suggested:

> It seems that it cannot generate the source map strangely.

There error that happens on the server is:

```
FilterError: browserify: subprocess returned a non-success result code: 1, stdout=undefined
, stderr=
```

It would be nice to be able to use debugger. : )

**Comment by tilgovi** [comment]
I can't reproduce this. I have no problems adding the `debugger` statement.
However, you probably don't want that as the last line in your `controller`, fyi, since the controller function should return the controller instance. You want the last line to be `this` or else explicitly return undefined, which implies `this`, since I believe the controller function is called with the `new` keyword.
