### ISSUE TITLE
Sidebar won't open on the Guardian

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2026]
Issue on the Guardian deploying the chrome extension.  no sidebar appears.  
"uncaught error: duplicate define: jquery"

http://www.theguardian.com/environment/2015/mar/10/working-towards-practical-solutions

![screen shot 2015-03-12 at 6 04 43 am](https://cloud.githubusercontent.com/assets/1413074/6618157/bbbbfa5c-c87d-11e4-99b1-3cc4d2fb63b7.png)

**Comment by csillag** [comment]
I thought we are using some kind of compatibility / no collision mode 
of jquery, in order to avoid any collusions like that... aren't we?

2015. márc. 12., cs 14.06-kor-kor, Dan Whaley 
<notifications@github.com> írta:

**Comment by tilgovi** [comment]
The problem is that a script on this page is using requirejs and leaves the `define` function on `window`. Our bundled jQuery sees this and tries to attach itself by calling `define` instead of acting like a CommonJS module as we'd like it to. The result is that the `define` call is telling us jquery is already defined (because the script that is meant to use the AMD loader already did this).

**Comment by tilgovi** [comment]
Okay, this is kind of nasty. Here's what's going on:

We list "jquery" in our browserify-shims (package.json) but we specify 'global:jQuery'. What this means is that our code can call require('jquery') and jquery doesn't get bundled in. Instead, it's expected to be in the global scope as 'jQuery'. That's the case because we specify it in our asset bundles (h/assets.yaml).

Unfortunately, this means that browserify-shim isn't wrapping jquery and inlining it. If that were the case, it would be loading a scope where `define` has explicitly been set to `undefined`. Instead, it loads in the global scope. Some script on this site uses require.js and jquery and therefore `define.amd` is true and jquery tries to be clever and load itself as an AMD module. This means that our jquery conflicts with the already-loaded jquery provided by the site.

We could strip jquery out of our asset bundles and change to `"jquery": "$"` in our browserify-shims settings, but that breaks Annotator v1.2.x which expects `jQuery` in the global scope.

So we're in a bind. @nickstenning help me.

**Comment by tilgovi** [comment]
Hold still... I'm going to attempt to browserify-shim all of annotator and its deps.

**Comment by orschiro** [comment]
@nickstenning 

Can you please also update the package on the Webstore?

https://chrome.google.com/webstore/detail/hypothesis-web-pdf-annota/bjfhmglciegochdpefhhlphglcehbmek

Thanks!

**Comment by csillag** [comment]
@orschiro sure, eventually we will, but before putting out a new extension release, usually we do a few days of internal testing, to make sure that everything works as it's supposed to.

But you can expect a new official release soon.

**Comment by orschiro** [comment]
@csillag 

Thanks! Can you please announce the release of the new version here as well? Then I can test it on the Guardian page myself.

**Comment by renehamburger** [comment]
@tilgovi, I'm wondering whether this is related: When activating the hypothes.is extension on Moodle, require.js throws the exception `Mismatched anonymous define() module` frequently. You can see that happen, for example, if you navigate to the [calendar on the Moodle demo site](https://school.demo.moodle.net/calendar/view.php) and log in as guest.

This does not happen when hypothes.is is only loaded once the page load is finished, e.g. with the bookmarklet.

I'm currently investigating this issue on my own Moodle platformt (with non-minified require.js code) to figure out how this could be fixed.
