### ISSUE TITLE
IE11 thinks we're pulling xpath.js from annotateit.org O.o

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#2027]
![Um...](http://f.cl.ly/items/3j192h2W0D19193c0a3V/2015-03-12%2010_00_29-https___hypothes.is_blog_meetvia_%20-%20Internet%20Explorer.png)

So...yeah...gonna clear my cache and see what it does next.

:fire: :computer: :fire:

**Comment by BigBlueHat** [comment]
Strangely...clearing the cache didn't do a thing. :astonished:

**Comment by BigBlueHat** [comment]
Testing here (fwiw) https://hypothes.is/blog/meetvia/

**Comment by tilgovi** [comment]
Upstream Annotator does this. It shouldn't, since we should be fetching polyfills before we load Annotator. Even so, Annotator probably shouldn't be doing this detection itself. Unfortunately, that domain seems to not have a valid cert, or we could simply change the URL to `//` for the moment. So, let's do something smarter. Wanna rip it out of Annotator? @nickstenning ?

**Comment by nickstenning** [comment]
Yes, kill it with :fire: -- this is entirely my fault and is a terribly bad decision. I guess that's v1.2.11, then?

**Comment by BigBlueHat** [comment]
Doing all that is fab, but why would IE11 be looking for that file when
loading our blog post (which has our embed.js code on it)?

`h` doesn't request the file...so what's up, do you think?

**Comment by tilgovi** [comment]
Annotator requests the file. Annotator is part of h.

**Comment by tilgovi** [comment]
Grep the v1.2.x source. Kill it with :fire: like @nickstenning said. PR and
:shipit:.

**Comment by tilgovi** [comment]
Just going to close this one. It's an Annotator issue and I don't think I ever want to change that for Annotator 1.2.x since it means updating documentation, changing translation strings, and communicating this effectively in a patch release. This will die with Annotator 2.0 and doesn't need to be tracked here.
