### ISSUE TITLE
Some advice.

### ISSUE THREAD

**Issue by tvvocold** [hypothesis/h#2045]
1,  add Social authentication like google, github, openid ,etc.
2,  use globle CDN service such like cloudflare( I can't wait 15s to load the hypothesis' js, btw, i'm in China) 
3,  add admin feature so that the site's admin could delete/ban spam comments/bot.

**Comment by tilgovi** [comment]
Thank you for opening your issue. I am going to respond and close it because this is not the preferred forum for discussion. We try to use the GitHub issues for tracking bugs and work in progress, while the mailing list is a better place to discuss extensions and enhancements.

1. We've considered it and we may at some time. I have personally prototyped an external auth flow and the W3C has successfully integrated our server with the Firefox Accounts authentication server. Thank you for that feedback, though, we will consider adding 3rd party authentication providers to our public service.

2. We just recently moved our assets to a subdomain, static.hypothes.is, which was the last thing I wanted to do before enabling a CDN. I will do that soon, so thanks for the reminder. However, we do specify far future headers for the assets, so your browser should cache them aggressively. We've also got open issues to improve startup performance, which could do fewer round trips.

3. This may or may not be in scope for this repository. Historically, we've always spoken about community moderation but never have super-user privileges been part of that discussion. If you're interested in having your own deployment with this kind of feature, please get in touch on our development list: https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev
