### ISSUE TITLE
Form is not always visible after clicking the sign in link

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#2052]
Tested with latest master.

To reproduce
1. Find a page which has enough annotation cards to be able to scroll down
2. Load h/apply the bookmark in this page (welcome page works too) when you're not logged in.
3. Notice that the login form appears as a top card.
4. Scroll down the annotation cards as far as the login form to be scrolled 'out' from the screen
5. Click on the Sign in link

Result: It seems as nothing happens, because we have the form opened but not visible. This is very confusing.

**Comment by tilgovi** [comment]
Please try to frame your issues in terms of the problems and the goals, rather than the implementations suggested to fix it. For instance, this could just as well or perhaps better be solved by having the form be on another z index, or something.

**Comment by tilgovi** [comment]
Had to revert #2086. See comment there.

**Comment by seanh** [comment]
I think this got merged again

**Comment by tilgovi** [comment]
Nope. Was not.

**Comment by tilgovi** [comment]
So, angular is a PITA for things like this. It does not mix nicely with standard markup for hash changes. The reason is, I think, that angular can optionally be in html5mode or not for its `$locationProvider`. That means that when angular is in use, it's not clear what the meaning of a hash href is. Therefore, angular treats them all the same, as though "#hash" were actually "/hash" relative to the base URL of the application.

`$anchorScroll` works for what we want here. However, testing things out I find that while `reloadOnSearch: false` for a route definition will prevent the route from reloading when I do `$location.hash('id')` it still reloads when I do `$location.hash('')` to empty it. In v1.3, angular added an argument to `$anchorScroll` so that we can invoke it directly instead of changing the hash.

I think we should just look at upgrading Angular first.

**Comment by nickstenning** [comment]
This is fixed. Clicking on "sign in" now always focuses the username field and scrolls it into view.
