### ISSUE TITLE
Sometimes you have to search for the new annotation cards if many are present

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#2053]
Tested with the latest master branch.

- Find a page which has many annotation cards.
- Scroll the annotation cards, so that their position would be different than their position on the page
- Try to create a new annotation

Result:
A new annotation card is created but not always visible or just partly visible. You've have to scroll the cards to find it.
This can be confusing and very cumbersome. I expect the newly created card to be immediately fully visible.

**Comment by csillag** [comment]
@seanh, do you think the solution to applied in https://github.com/hypothesis/h/pull/2086 would work for this one, too?

**Comment by seanh** [comment]
I'm not sure that the simple solution will work here because the popup button that you click on to create a new annotation is outside of the iframe. I'll investigate. I need to figure out what happens / what code is involved when you click on the new annotation button..

**Comment by csillag** [comment]
@seanh:

> I need to figure out what happens / what code is involved when you click on the new annotation button..

For example, [this code](https://github.com/hypothesis/h/blob/3b962a0630718b152e04cfbe9ab9a86a139ff173/h/static/scripts/controllers.coffee#L109) is run in the sidebar, when we start to create a new annotation.

**Comment by seanh** [comment]
Is that even going to be helpful here? We want to scroll to the edit form in the annotation, but unless I'm mistaken the annotation hasn't been added to the dom yet when that even triggers

**Comment by csillag** [comment]
> Is that event going to be helpful here?

It can be helpful as a starting point where you can start to analyze the system. 

> We want to scroll to the edit form in the annotation, but unless I'm mistaken the annotation hasn't been added to the dom yet when that event triggers

That's probably correct. See if you can find a trigger after the editor has been added to the DOM; or you might want to start a short timer here, *if there is really no better way to do it*.

**Comment by seanh** [comment]
@csillag That was very helpful, thanks! Take a look at my attempted solution here: https://github.com/hypothesis/h/pull/2101

**Comment by seanh** [comment]
I'm gonna give up on this one and look for something else to do, because I'm not making any progress on it.

`scrollIntoView()` is a DOM method that _might_ be usable to do this (not sure about browser support).

I've tried two approaches. One is to start from the new annotation form itself, `annotation.html`. `annotation.html` has a `<div>` for the editor form with an `ng-if` on it that controls showing or not showing the form depending on the controller's `editing` property. I can't find any way in the HTML/Angular template to get the `<div>` to say "call scrollIntoView() on me when this ng-if becomes true."

The controller for this directive is `AnnotationController` and it has an `edit()` method that sets the `editing` property to true. But I can't find any way for the controller's CoffeeScript code to access the DOM element that this instance of the controller was instantiated for in order to call `scrollIntoView()` on it.

Coming at it from the other direction, the "New Note" popup button ends up calling `guest.coffee`'s `onAdderClick()`. What happens next is bizarre:

    setupAnnotation: ->
      annotation = super
      this.plugins.CrossFrame.sync([annotation])
      annotation

    createAnnotation: ->
      annotation = super
      this.plugins.CrossFrame.sync([annotation])
      annotation

    onAdderClick: (event) =>
      ..
      switch event.target.dataset.action
        ..
        when 'comment'
          this.setupAnnotation(this.createAnnotation())
          ...

But anyway ... So `CrossFrame.sync()` gets called, and in turns it calls `AnnotationSync.sync()` which calls `Bridge.call()` with the method name "sync" which calls `jschannel`. At this point I lose track of what's happening, there's too much indirection. Lots of signals seem to get emitted like createAnnotation, annotationCreated and beforeAnnotationCreated, updateAnnotation, beforeAnnotationUpdated, annotationUpdated.

What I guess this all boils down to is: user clicked the "add annotation" button in the document, a signal needs to be sent to the sidebar telling it to add an annotation.

_Something_ in the sidebar is on the other end of this bridge receiving this signal and inserting a new annotation!

If I could find it, _maybe_ I could add a line after creating the annotation to say "now scroll the annotation into view".

I'll come back to this if I have any inspirations as my understanding of the code improves.
https://github.com/hypothesis/h/issues/2053#

**Comment by seanh** [comment]
@nickstenning ^ cc

**Comment by tilgovi** [comment]
Some possibly useful links:

- scrollIntoView polyfill: https://gist.github.com/termi/5063286
- $anchorScroll service: https://code.angularjs.org/1.2.27/docs/api/ng/service/$anchorScroll

With ng-if, you can add another directive to the same element and since ng-if removes and then re-adds/compiles/links the element and directives of lower priority whenever the condition changes to true, so you could add a directive that just scrolls to itself on link.

**Comment by seanh** [comment]
Re-assigning to myself, I'll look into @tilgovi's tips

**Comment by seanh** [comment]
Going out for lunch now but this looks promising. Looks like the `<article class="annotation"`s don't have ids, so first step will be to add those

**Comment by seanh** [comment]
Thanks for that @tilgovi, here's another attempt: https://github.com/hypothesis/h/pull/2121

**Comment by seanh** [comment]
Another version: https://github.com/hypothesis/h/pull/2123

**Comment by tilgovi** [comment]
Re-opened because I had to revert #2123. See comment there.

**Comment by tilgovi** [comment]
Closed in 92ebb252f95872c88b0df769cddbac7d01cfcf97
