### ISSUE TITLE
Body of annotation lost on forced login

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#2078]
Latest master.

Steps to reproduce:

 * Deploy H on a page, without logging it
 * Start to annotate. Write your annotations, and try to save it
 * You will be reminded that you need to log in.
 * Click log in
 * The login form appears. 
 * Log in
 * The editor (for the original selection) will open again; however, the text that you have previously entered for annotation body will be gone.

Since losing user-entered data is always ugly, and since this is likely to be among the very first impressions any user gets about our system, I am marking this as a blocker.

**Comment by csillag** [comment]
Removed blocker flag, as per group decision.

**Comment by tilgovi** [comment]
This one is tricky. I was thinking about it last night.
Maybe what's needed is a better drafts system. Rather than trying to preserve cards and UI across login changes (reloading is much "safer" when changing auth contexts) maybe we just enable ourselves to restore more state.

**Comment by BigBlueHat** [comment]
Maybe just use `localStorage` to keep the content they've started writing? We're able to re-open the same annotation editor, so there should be enough "uniqueness" to store that locally until they login.

I keep hitting this, so :+1: for gettin' it fixed. :smile:

**Comment by tilgovi** [comment]
`localStorage` isn't necessary unless you want these to persist across reloads or between frames. What's needed for the problem as described is much simpler and "in memory".

**Comment by BigBlueHat** [comment]
Oh. Even better then. :smile:

**Comment by scharf** [comment]
From a users perspective this is really annoying, because you loose some work without notice. Letting the user to interact with the system without being signed in or registered is great, but loosing work is much worse than not allowing it in the first place. I would rather prefer that the system asks me to log in *before* I enter a comment than to let me enter the comment and then throwing it away!

**Comment by scharf** [comment]
The frustrating part is, once you have experienced this, you think twice before using the system, because you know it's one of the system that does not respect your work. Few years ago it was much more common to loose work in web forms. Today browsers are quite good at dealing with that and often recover what you have entered.

In this case, the most frustrating part is that the system guides you and tells you, you should sign in. Therefore you assume: "ah that's cool they allow me to log in now". And then loosing the work is even more frustrating,

If I would have gotten an error message that I am not signed in (without loosing the data) I would have taken steps to save my work before I sign in. But because the system pretended it knows that I have to sign in, I assumed it is clever enough to submit my change (automatically) after I signed in. This makes the pain of loosing data worse.

**Comment by JakeHartnell** [comment]
Addressed with a quick fix here: https://github.com/hypothesis/h/pull/2361

We certainly need better a drafts system, but there other issues for that: for example https://github.com/hypothesis/h/issues/2151 & https://github.com/hypothesis/h/issues/2150

Closing.
