### ISSUE TITLE
ID Token / Access Token Disambiguation

### ISSUE THREAD

**Issue by tilgovi** [hypothesis/h#2084]
Here's a roadmap for getting better aligned with OpenID Connect and OAuth 2:

- [ ] Split h.auth (Identity) and h.api.auth (Storage)
- [ ] Identity server should return an ID Token from its authentication flow.
  - [ ] OPTIONAL an Access Token may be returned _may be the same as ID Token iff both are JWTs_
- [x] Storage should accept ID Tokens in exchange for Access Tokens (_may be the same iff both are JWTs)

There are two relationships happening:

1. Client and Identity Server are doing OIDC authentication.
2. Client and Storage Server are doing OAuth2 authorization.

These are two _separate_ interactions. It is tempting to try to think of them all as part of one flow, but the most reasonable way to connect both while maintaining some alignment with specifications for the sake of interoperability.

In this case, we happen to be implementing a Storage Server that supports JWTs as Authorization Grants, and providing our Identity Token to it so that the second flow is one round trip. The Storage Server can provide storage namespaced (via our `consumer` key in storage) to each issuer it knows about.

Down the road, an ideal client might wish to engage in OIDC discovery to allow adding identities. The discovery of the preferred Storage Server for any identity is out of scope for now and we should do whatever works.

**Comment by judell** [comment]
Why remove Partner:Lumen?

**Comment by tilgovi** [comment]
I removed all the partner labels to avoid any perception of favoritism in this tracker and a preference for tracking partner needs in product planning rather than individual technical issues.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
