### ISSUE TITLE
inconsistency in the displayed number of search results

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#2088]
Here is how to reproduce:

 * Go to a document with some annotations with replies, and deploy H
 * Run a page search that will match one of the replies
 * Observe the text near the top of the viewer: "Found one result"
 * By default, the top-level annotation is not loaded. Click on the "View one more in conversation" link to load it.
 * Observe the changed text near the top: "Found 2 results"

I don't think that's correct; the declared number of results shouldn't be influenced by the user's decisions about viewing more content.

**Comment by judell** [comment]
Straw man proposals:

term found in n annotations

term found in n annotations and m replies

Either way, the numbers would not change as collapsed parts of threads are expanded. The count of search results does not vary, it's only the visibility of context surrounding them that does.

**Comment by tilgovi** [comment]
:+1: for the numbers not changing.

**Comment by tilgovi** [comment]
Alternatively, this is currently showing correctly the number of _visible_ annotations, whether they are drafts, search results, or selected annotations, or whatever.

Would we be okay to simply change the wording for the time being, to not say "results"?

**Comment by tilgovi** [comment]
bump

**Comment by judell** [comment]
"Would we be okay to simply change the wording for the time being, to not say "results"?"

If you mean entirely remove "Found 1 result" or "Found 3 results" -- i.e., just don't count anything for now -- then yes.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
