### ISSUE TITLE
Separate viewer and streamer templates

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#2089]
This issue rose when fixing #1916.
The point is that we want to have the freedom to display annotation cards in the viewer and in the streamer completely differently.

PR #2081 did the first step by populating the `$scope.threadRoot` differently and handling the annotation events but our ultimate goal is totally decouple them. (Separate template, no magic with populating a scope variable differently, etc etc.)

This can be done when we'll have a decision on https://github.com/hypothesis/vision/issues/166 and this separation can be part of the implementation.

What is good to consider (I'm not suggesting any implementation, just listing key areas):
- Stream may not even need to use our jwz message containers.
- The annotation [cleanup process](https://github.com/hypothesis/h/blob/ba340540d587621fccd8a77a508a6edec5182b43/h/static/scripts/controllers.coffee#L66) should be revised. It expects the threading service to be the master of all loaded annotations (PR #2081 changes this, but with total separation we can do this more clearly)
- Currently the [AppController populates $scope variables which shouldn't there](https://github.com/hypothesis/h/blob/ba340540d587621fccd8a77a508a6edec5182b43/h/static/scripts/controllers.coffee#L137) (should move to the template Controllers).

**Comment by tilgovi** [comment]
:+1:

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
