### ISSUE TITLE
Add tooltips for hovering on annotations

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2109]
For a couple of related reasons. First, to summarize info about the annotation: how much text, how many tags, how many replies. This helps the user decide whether to invest in that next click. Second, to announce that this is in fact an H annotation. There are other extensions and hacks running in the world that might create yellow highlights too.  A tooltip brands a yellow highlight as an H highlight.

(See also https://github.com/hypothesis/h/pull/2064)

**Comment by tilgovi** [comment]
Can we narrow down exactly what we want here? You mentioned a few possible things. Let's make it more concrete.

**Comment by judell** [comment]
Since this came up again today, the min example would be: "Click to open Hypothesis annotation" or maybe "Click to open Hypothesis annotation with n replies." More aggressively, that with some preview snippet of the annotation.

The key point is that opening the sidebar is a relatively heavy operation. Any information we can surface to help the user decide whether the annotations under this particular highlight are worth that context disruption will be helpful. Plus, as I said, we add H branding to the page.

An an often-hidden experience, we want to communicate as effectively as possible whenever we are hovered over. That applies to existing tooltips and to places like this where we don't yet offer them.

**Comment by dwhly** [comment]
@RawKStar77 didn't you have mockups of this from a while back, or maybe it was @jtremback?

**Comment by RawKStar77** [comment]
@dwhly -> https://docs.google.com/a/hypothes.is/document/d/1-tV9_F7lxjLl5waSP5HpoplQhgofyhoR11kIkRJma_Q/edit

**Comment by RawKStar77** [comment]
![selection_041](https://cloud.githubusercontent.com/assets/521978/7061154/c0c4ad66-de42-11e4-9718-494d3f27b76c.png)

**Comment by dwhly** [comment]
I swear I remember some HTML implementation somewhere... must be dreaming.

**Comment by RawKStar77** [comment]
Annotator? : ) http://annotatorjs.org/

**Comment by dwhly** [comment]
Nope. :)

**Comment by judell** [comment]
DoTheSimplestThingThatCouldPossiblyWork suggests to start with "Click to see Hypothesis annotation" or (if replies) "Click to see Hypothesis annotation with n replies"

That gives us, and users, a taste of the interaction, and a basis for evolving a richer presentation (if even warranted). My hunch is that things like this are sometimes over-specified at first, and then languish because it's hard to decide or act on the more complex thing.

**Comment by dwhly** [comment]
My edit pen wants to remove "Hypothesis" from "Click to see Hypothesis annotation" if only because when this is in place at the W3C or w/ EJP they'll rather that not be there, since there's no context for it.  (It wouldn't make sense for it to say "EJP" either, since the reviewers aren't aware of the vendor on the back end).  Maybe we solve the "whose highlight is this i'm clicking on" problem later when there are more instances of conflicts?

**Comment by judell** [comment]
OK.

**Comment by jtremback** [comment]
Yea, I never had mockups of this I think.

**Comment by judell** [comment]
We are quite good about being unobtrusive and that is a virtue. So I'd add that when we add Settings to the Account menu (as we inevitably will), Show Tooltips on Annotation Highlights would be a setting that would default to On but could be switched to Off.

**Comment by nickstenning** [comment]
There's a lot to unpack in putting tooltips on a page. It potentially reverses a trend to moving more and more of our functionality into a domain we control (the sidebar) rather than the wild west of someone else's page. There are security/privacy implications.

It may well be the right thing to do, but I suggest this is a feature with big enough implications that we should discuss it on a call.

**Comment by judell** [comment]
https://github.com/hypothesis/h/issues/620

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
