### ISSUE TITLE
Clicking on tag auto-complete only inserts what's been typed--not full tag

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#2114]
Steps to reproduce (on production in Firefox, atm):
1. Create some annotations with some tags.
2. Create a new annotation
3. type part of the tag name
4. press `,` to complete the tag
5. OR click the auto-complete tag name

Both 4 and 5 only insert the text that's been typed so far. :frowning:

**Comment by tilgovi** [comment]
It's not clear to me that a comma should use the completion since it's a normal separator. I don't expect the thing to behave differently just because there's a suggestion present. The suggestion can be selected with TAB, which otherwise wouldn't have any particular function in this context.

Clicking on the suggestion is definitely broken. That is probably a matter of event ordering: a blur happening on the tag before the click.

**Comment by BigBlueHat** [comment]
Yeah. Good point in the comma.

**Comment by judell** [comment]
These were new to me but accumulated a few gripes about tag input, including:

- some users clearly expect whitespace to be a separator

- can't enter repeated tags using tab, only enter

Q: Our tag input mechanism is a library, not homegrown? I ask because apart from these usage issues, we know there are extensions needed to (among other things) bind tags to namespaces. I'm wondering we'll extend the current mechanism or need to replace it. And whether these issues should wait until after that's determined.

**Comment by JakeHartnell** [comment]
> some users clearly expect whitespace to be a separator (as we see by the tags they make)

It should be noted that some users had asked for tags to be able to contain white space. IIRC at first we didn't support whitespace in tags but added them later.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
