### ISSUE TITLE
Add bookmarklet to http://hypothes.is for Safari

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2132]
I found out why Maryann did not find the bookmarklet. It isn't there for Safari when it visits http://hypothes.is. I made her a test bookmarklet page, she installed from there, and can now use H on Safari without using Via. I wondered why she thought Via was the only way. For her, it was!

**Comment by RawKStar77** [comment]
Previously, the bookmarklet wasn't working on Safari. If this no longer the we should certainly update the front-page. I've created an issue for it here: https://github.com/hypothesis/wordpress-theme-hypothesis/issues/30

I'm going to close this issue though because the relevant code is in the other repo.
