### ISSUE TITLE
Site report: iframe disables annotation?

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/h#2134]
http://www.folgerdigitaltexts.org/?chapter=5&play=Rom&loc=p7

not sure if there could ever be a workaround here--there are PDF and html versions of this text at folger--but would be cool if we could annotate here as well--and sync across the versions!

html:

http://www.folgerdigitaltexts.org/html/Rom.html

PDF:

http://www.folgerdigitaltexts.org/PDF/Rom.pdf

**Comment by tilgovi** [comment]
This would work today if we could inject into the page frame. Our app is actually designed in such a way that one or more frames can participate in annotating with the same sidebar, and the sidebar need not be a direct child of the annotated frame. So, if folger wanted to, they could put our sidebar with into their sidebars and then inject the rest into the frame showing the content.

For our extension and proxy service, we could look into automatically injecting the annotation capability into any same-origin frames we have access to.

There's definitely some UI strangeness that is likely to crop up, similar to what happens if different scrollable panes are on a page. The bucket tabs on the sidebar get a little confusing. The up/down gets a little less defined.

**Comment by judell** [comment]
Until/unless there's a way to inject, we kinda-sorta work in this case. You can make page notes, and tag them. That's what I'm doing now as I use H to tag issues in this repo. 

The question is whether to detect the problem and explain what *is* possible, or punt with a "nothing to see here" message.

Tagged with graceful_degradation.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
