### ISSUE TITLE
Keep unsaved annotations in the browser

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#2144]
Problem: If I create or edit an annotation but don't save it then it hasn't been sent to the server. If I leave the page it will lose the annotation with no warning.

Suggestion solution: Always autosave annotations in the browser, restore them in the sidebar when visiting the page again.

Another suggested solution: Don't even have a save button, just always autosave (first in the browser then asynchronously to the server) but keep the annotations private until the user hits a "Publish" button.

**Comment by tilgovi** [comment]
I think this is a duplicate of #2008

**Comment by seanh** [comment]
Hmm, is it a dup? #2008 seems to be about making highligh

**Comment by tilgovi** [comment]
It's the same, I think.

It just mentions highlight specifically because when making highlights you don't have to open the sidebar and even an experienced user might lose annotations by not realizing they haven't signed in.

Annotations open the sidebar and can't be saved right now without logging in so it's more apparent what's happening.

The underlying issue is the same, though: don't lose user data.

**Comment by seanh** [comment]
Alright, closing as dup then
