### ISSUE TITLE
Show popup when already selected text

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#2145]
Go to a web page. Select some text. Realise that Hypothesis isn't launched. Launch Hypothesis. You have to unselect and reselect the text to get the popup button.

Solution: show popup on launch if selected text.

**Comment by dwhly** [comment]
+1

**Comment by tilgovi** [comment]
This has worked at some point :-/

**Comment by tilgovi** [comment]
But it was never intentional.

**Comment by csillag** [comment]
> But it was never intentional.

Yes it was. I supported this use-case on purpose.

The required code was removed as one of the rarefactions, as superfluous.

**Comment by csillag** [comment]
What I wanted to say just now:

The required code was removed during one of the refactorings.

**Comment by tilgovi** [comment]
Sorry, but I can't recall any such intention or removal. You may be right.

**Comment by csillag** [comment]
Here is how it worked the last time:
 * at that time, we could only have one new annotation editor open in the sidebar
 * therefore, when we started to create a new annotation, we had to disable the adder button.
 * to achieve this, I added a switch to Annotator, to temporarily remove the ability to create new annotations. (IIRC, it was called `disableAnnotating()` and `enableAnnotationg()`, or something similar.)
 * While the creation of annotations was disabled, the selection events were not registered, so the adder button was never shown.
 * On `enableAnnotating()`, the Annotator plugin responsible for dealing with the selection tested if we have a valid selection, and if we did, triggered the same code path which is usually triggered by creating a new selection.
 * The tricky bit was that in this case, we don't have a mouse event, so we can't position the adder button based on the coordinates found in it. To work around this, we used to have a helper method for getting the location of the selection range. It used some jQuery magic, and worked by inserting "probes" before and after the wanted range, in order to get the right coordinates.

  * * *

Most of this was removed when we started to support having more than one "new annotation" editors in the sidebar. The rest of this (which has been dead code since the first refactoring) has been removed later.

   * * *

As of now, we no longer need the `disableAnnotationg()` / `enableAnnotating()` feature, but we could still do the same check upon initialization.

**Comment by csillag** [comment]
> The tricky bit was that in this case, we don't have a mouse event, so we can't position the adder button based on the coordinates found in it. To work around this, we used to have a helper method for getting the location of the selection range. It used some jQuery magic, and worked by inserting "probes" before and after the wanted range, in order to get the right coordinates.

If we ever want this feature back, this part was removed here: https://github.com/hypothesis/h/commit/29ff86fc4934262df5823740d9840fac0018df2d

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
