### ISSUE TITLE
Improve uri analyzer

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#2148]
There are [6 annotations created with this uri](https://api.hypothes.is/search?uri=http://blog.jonudell.net/2015/01/22/a-federated-wikipedia/): `http://blog.jonudell.net/2015/01/22/a-federated-wikipedia/`

But if you [search for the uri](https://api.hypothes.is/search?uri=http://blog.jonudell.net/): `http://blog.jonudell.net/`

None of those 6 is received. We have to analyze the uri field a bit more (or just use query-string) to provide better results

**Comment by judell** [comment]
There is an inconsistency in the first part of the screencast. The stream search finds one annotation, and the api search finds one, but they are different.

The second part is invalid as you say because of operator error on my part. A search for  http://blog.jonudell.net/2015/01/22/a-federated-wikipedia/ should return different results from http://blog.jonudell.net/, they are not the same, and we should not silently merge the two queries.

Closing this issue. Please recheck the first part of the screencast. I will recheck and update it to exclude the erroneous second sequence.

**Comment by gergely-ujvari** [comment]
I think in general it'll be a good idea (but not urgent) to recognize the domain.
