### ISSUE TITLE
Remove "click to close" feature for sidebar

### ISSUE THREAD

**Issue by tilgovi** [hypothesis/h#2167]
I removed the click to close feature in 04504dca0b36cffd57d3fd7fe071fd1ef52079b0.

I added it back in c90df05fc940587b3f4aef871538ad3e9f226b8d at the request of @judell.

However, I thought I had done it at _someone_'s request. I just can't seem to find record of that now.

In any case, I think it might be a good idea. The chevron is the obvious interaction point for open/close and it's not clear we need another way to close the sidebar. It may even annoy users who don't understand why the sidebar closes seemingly randomly while they do other things.

**Comment by csillag** [comment]
IIRC it was mentioned by Sean, but it was just a "first impression" thing.
2015.04.16. 18:47 ezt írta ("Randall Leeds" <notifications@github.com>):

**Comment by tilgovi** [comment]
Ah, you may be right. Thanks, @csillag.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
