### ISSUE TITLE
Feature request: Wrap embed.js in a commonjs module

### ISSUE THREAD

**Issue by shawninder** [hypothesis/h#2174]
Website developers can use *embed.js* to include the hypothesis client on their pages via a script tag which injects the required assets. This is very nice :) But I think exposing *embed.js* as a *commonjs* module as well would be nice to have for a couple of reasons:

- It would allow bundling and minifying *embed.js* in with the rest of the page's scripts (using `browserify`, for example), making for one less file to load on page start
- It would help developers have a consistent code base when they are already using commonjs for other libraries:
```
var $ = require('jquery')
require('hypothesisEmbed')
```
instead of
```
var $ = require('jquery')
<script type="text/javascript" src="http://.../embed.js"></script>
```

As a bonus, you could make such a module installable via npm: `npm install hypothesisEmbed --save`, which would make it easier to have your website depend on specific versions of the hypothesis client (or at least of *embed.js*).

**Notes:**
- I use `hypothesisEmbed` in my examples because I expect you'll want to keep `hypothesis` for a module that exposes the api methods allowing the creation of custom clients.
- Ideally, the actual client could be wrapped in a commonjs module (instead of embed.js), but that is a little harder because of its dependency on css files... Just thinking out loud here.

**Comment by tilgovi** [comment]
@shawninder the application is CommonJS already. This is outside the scope of what embed.js is for. Please consider using h/static/scripts/hypothesis.js instead, which is currently processed with browserify.

**Comment by tilgovi** [comment]
Also, you do not need to include jQuery yourself. It's bundled privately by the application.

**Comment by tilgovi** [comment]
I'm closing this one. The embed.js code is not intended to be consumed in any other environment than a script tag or a similar injection. The rest of the application code is CommonJS.

**Comment by shawninder** [comment]
What should I `require` to include the tool in my website?

**Comment by tilgovi** [comment]
You will need `<link rel="sidebar" href="https://hypothes.is/app.html">` in the page (you can add this from your script) and then include the file from h/static/scripts/annotator/main.js.

Since a lot of the project is still CoffeeScript at this time, you need to ensure that your toolchain understands CoffeeScript and .coffee extensions. For instance, with Browserify you can do "--extension=.coffee -t coffeeify" (you will also need strip-bomify, and browserify-shim).

This is also something that is completely unsupported at the moment and you will undoubtedly run into issues we have not uncovered.

Adding the appropriate CSS is your responsibility, too.

**Comment by tilgovi** [comment]
Actually, forget what I said about browserify and the rest. The built module is published when we publish to our site, so you should be able to use https://hypothes.is/assets/scripts/hypothesis.min.js. I am not sure that you can actually require it, though, since it is an immediate function invocation and doesn't export any symbols.

@shawninder requiring Hypothesis using a CommonJS system is probably just not supported at all right now, if it ever will be. You should look at openannotation/annotator for this.

**Comment by tilgovi** [comment]
In other words: Hypothesis is an application and not a library. You cannot `require` it.

**Comment by shawninder** [comment]
I understand. This is why I posted the feature request. When the time comes, I will try using the built module, but that will be a while still as I am quite busy with other projects right now. If I do end up making a wrapper for myself, I will make sure to submit a pull request. In the meantime, thanks for the pointers :)
