### ISSUE TITLE
Restore URI search in stream

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2179]
As of the latest release, URI search is currently disabled.  (https://github.com/hypothesis/h/commit/e139ca7)

**Comment by tilgovi** [comment]
That's not true?

**Comment by tilgovi** [comment]
That's not at all what that commit does. If there are problems with URI search you'll need to be more specific about expectations and results.

**Comment by dwhly** [comment]
Perhaps I misunderstood this exchange, can you explain?

> Disabled "page search" on /stream
> https://github.com/hypothesis/h/commit/e139ca7
> This was a source of confusion when some results didn't appear in the stream. With this change the
> stream should be faster, too, but unfortunately this was at the cost of the result count for the moment.
> Is this the same as searching the stream for uri:<addr>?  Something tells me no.
> Yes!!
> These were having problems not because the server didn't return them but because the client ignored them, thinking they didn't match.

Tried https://hypothes.is/stream?q=uri:hypothes.is and didn't get anything back, assumed perhaps it was disconnected.  What is a better description of the issue here.

**Comment by tilgovi** [comment]
Yes, you misunderstood, or I did. I thought you were asking if this fix was for the same problem as not getting back results for uri searches, i.e. a lot of what @judell was talking about in 2129. The answer to that is "yes".

What you're experiencing is that searching for part of a URI, in this case a domain, doesn't give back annotations made anywhere in that domain. That's a different problem than having the API and the stream return different results.

https://hypothes.is/stream?q=uri:hypothes.is -> 0 results
https://hypothes.is/api/search?uri=hypothes.is -> 0 results

https://hypothes.is/stream?q=uri:hypothes -> many results
https://hypothes.is/api/search?uri=hypothes -> many results

However you'd like to describe what you're seeing, I hope you agree it is not that URI search is disabled, nor can it be "restored" since it is working more than it ever has.

**Comment by dwhly** [comment]
> Yes, you misunderstood, or I did.

Probably both!

> What you're experiencing is that searching for part of a URI, in this case a domain, doesn't give back annotations made anywhere in that domain.

But I was actually trying to search for annotations on our home page, of which there are many.  Shouldn't:

https://hypothes.is/stream?q=uri:hypothes.is

Return those?  Happy to open another issue for that if appropriate.  On a tangent, noticing that

https://hypothes.is/stream?q=uri:http:%2F%2Fwww.theatlantic.com%2Ftechnology%2Farchive%2F2014%2F08%2Fadvertising-is-the-internets-original-sin%2F376041%2F

and https://hypothes.is/stream?q=uri:www.theatlantic.com%2Ftechnology%2Farchive%2F2014%2F08%2Fadvertising-is-the-internets-original-sin%2F376041%2F

return totally different results (i.e. plus and minus the "http://" part).  This is probably a separate issue...

**Comment by tilgovi** [comment]
This is probably a separate issue...

Exactly. That's why I'm trying to get you to spend the time to enumerate exactly what you see vs what you expect and why I closed this issue.

You'll notice that simply searching for "hypothes.is/" (with the trailing slash) gives you what you want.
