### ISSUE TITLE
Stream uri: search gives different results for urls terminated by /

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2181]
Results differ for:
https://hypothes.is/stream?q=uri:hypothes.is

And

https://hypothes.is/stream?q=uri:hypothes.is/

**Comment by tilgovi** [comment]
I've determined that the real issue here is ambiguity due to still not having clear user stories for the stream.

The same analysis cannot serve the needs finding all annotations on a site and all annotations on a page. The issue here only demonstrates the most obvious ambiguity wherein it's not clear whether a user means to find all the annotations on a home / root page or all annotations on a site / domain.

#2184 introduces new analyzers and field mappings that will enable the stream to have a "site" facet in addition (or in place of) "uri".

**Comment by tilgovi** [comment]
Confirmed fixed on stage just now.

**Comment by judell** [comment]
These match:

https://stage.hypothes.is/stream?q=uri:hypothes.is

vs

https://stage.hypothes.is/stream?q=uri:hypothes.is/

Just checking/confirming that, as per https://github.com/hypothesis/h/pull/2184#issuecomment-98879105, this:

https://stage.hypothes.is/stream?q=site:hypothes.is

is (while a good idea) not part of the current batch of changes.

**Comment by tilgovi** [comment]
Correct.

**Comment by dwhly** [comment]
:fireworks:

**Comment by judell** [comment]
Still an issue. https://github.com/hypothesis/h/issues/2217

**Comment by nickstenning** [comment]
For posterity, this and #2217 are different bugs. This is fixed.
