### ISSUE TITLE
Make "CreativeCommons" note on new annotation page configurable

### ISSUE THREAD

**Issue by wagoodman** [hypothesis/h#2185]
When adding a new annotation a message appears stating that "Annotations can be freely reused by anyone for any purpose". This may not be the case for everyone who uses hypothesis (since the document being hosted may not be public). Though anyone can change the "h/templates/client/annotation.html" snippet to not include the creative commons 'public domain dedication' comment as it should not always be assumed that the document is in the public domain. Maybe this item should be configurable, possibly allowing an 'declaration' item in the conf/*ini file with the exact wording stating the legal status of all comments made on the current hypothesis instance. In this case the admin can easily identify the [legal] wording based on the documents being hosted and update the ini config accordingly.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
