### ISSUE TITLE
Explaining reduced functionality

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2188]
In some cases it is possible to annotate with reduced functionality. Google Docs is an example. Selection doesn't trigger the adder; you can manually copy/paste a selection and invoke New Note; the annotation will display in the sidebar but will not behave as expected: no highlighting, no sync, no annotation count.

The reduced functionality still has value. You can still annotate at page level, tag your annotations, converse with others. So I would not want to blacklist a popular service like GDocs. The question is how to tell the user what's happening.

If we write documentation users can of course find it outside the context of the app. Better, if possible, would be to detect the degradation and tell the user what's happening within the app. If we wanted to do that:

- What is it possible to detect?

- How should we tell the user what's happening?

**Comment by tilgovi** [comment]
@judell can you keep issues like this on vision instead of here? This sort of thing can encompass changes to any number of components. I'd like to keep the focus here and keep the possibilities open. For instance, we might solve this by communicating expectations better at install time through better copy on our home page or our Chrome web store copy, or we might have copy we need to add to hypothesis/via, and we might have changes inside h. Until such time as we have a real plan, though, I would prefer if these conversations happen on the mailing list or in hypothesis/vision, a repo I set up specifically for feature requests and planning so that we could keep this place clean for people actively managing and fixing bugs and issues with h proper.

**Comment by judell** [comment]
No problem, will relocate the discussion.
