### ISSUE TITLE
Check HTTP `Link` headers for rel="canonical" (for non-HTML docs)

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#2224]
This would allow publishers to use `rel="canonical"` with non-hypertext formats such as PDF, images, etc.

Which means one could start annotating on the PDF version of an article, and have those annotations re-anchor on the HTML version of the article--as we can now with the reverse.

Sadly, browsers don't give JS any HTTP headers, so you have to make a separate `HEAD` request for that info. Still doable, though.

**Comment by bbarker** [comment]
Would `rel="alternate"` also be a good one to support in this way? For instance, we have a pdf page which has the full document, but an html page that only has the abstract. Thus, in the current sense that hypothesis is using canonical, the pdf page itself would not need to use `rel="canonical"` (unless there are multiple versions of a document) but rather `rel="alternate"` to point back to the html abstract.

I agree both of these would be good to have.

**Comment by BigBlueHat** [comment]
Yep! Once we have the general work done for checking `Link` headers, we can easily sniff out all kinds of variations--include the long list of things we already check for in markup (and possibly others).

**Comment by bbarker** [comment]
It looks like there are a number of chrome extensions that currently grab http link hearders, but some of them (maybe all of them) require an additional http request. Speaking as a person who knows little about chrome apps, [this chrome app's approach](https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj?hl=en) looks like it may be better. Chrome itself knows the link headers, and the description of that app looks as though enabling a couple of permissions can solve the problem.

A tangentially related question: will hypothesis (once this is implemented) be able to grab http link headers from a page with a content-less redirect?

Here's an example for us:

If you go to an article's abstract page ( e.g. http://arxiv.org/abs/1411.6341) and click on a pdf link (right hand side of page, under "Download"), you'll be sent to e.g. http://arxiv.org/pdf/1411.6341v1 which will then return HTTP 302 and redirect you to http://arxiv.org/pdf/1411.6341.pdf

So in this case, if we put the appropriate link-rel http headers in the middleman redirect URI ( http://arxiv.org/pdf/1411.6341v1 ), will these be picked up by hypothesis? We're still planning a bit ourselves, so as far as I know this is not a critical need for us. But if the answer is yes, then this might be the simplest way for us to get things connected in hypothesis.

**Comment by BigBlueHat** [comment]
@bbarker I dug into this a few months back and it seemed that a second HTTP request is the only way to get at it from the current JS run times in browsers--I found it baffling that this was the case...but what can one do? :anguished: 

So...given that...I think "catching" the headers during a redirect dance party would be "impossible" (or at the very least really-really-hard-even-from-an-extension). The best scenario, then, would be for the final destination (on which hypothes.is will be embedded or embed itself via the extension or bookmarklet) to include useful `Link` headers about it's `alternate` versions, `canonical` location, and anything else we think to look-up from there to help us understand what's being annotated in the broad scope of the Web.

In this specific case, then, I'd think `rel="alternate"` and `rel="canonical"` (+/- the DOI ones for now) would be the place to start. Each destination format should sport these headers (in the ideal world).

/me elides section about browsers not properly supporting decent content negotiation and saves that for another venue. :wink:

**Comment by bbarker** [comment]
Thanks! That clears things up a bit. We were actually just talking about this exact conneg issue a few minutes before I posted above...

**Comment by tilgovi** [comment]
I am almost certain we can get the headers from the Chrome extension by hooking into the navigation, whether or not there's a redirect doesn't matter. The tricky thing is that right now our Chrome extension only injects the application code; there is no communication between the application and the extension background code.

It occurs to me that if we narrow the description of this issue to really focus in on _just_ PDF (and after all, we don't annotate anything but PDF or HTML right now) we could treat this potentially by injecting the link headers as link tags in the PDF.js viewer and harvesting that using the normal Document plugin.

In fact, right now the Document plugin and the PDF plugin are alternatives, but that's really conflating two things for PDF: hooking into events for re-anchoring on page render events and whatnot and describing the URI for the document. Instead, we could have the Document plugin loaded always, but ensure that when we load a PDF we insert what we want into the viewer HTML and thereby the Chrome extension has a place to drop its additional knowledge without adding any browser-specific communication between the application and extension code.

**Comment by BigBlueHat** [comment]
So...I'm not keen on there being only a "Chrome extension solution" for this one. Having the Document plugin (or PDF...) do a "HEAD check" when it loads for additional metadata in the `Link` headers seems as equally doable as what you've described and would get us the value this provides in all scenarios (not to mention some consistency).

It would also prep for images, CSVs, and the like.

**Comment by zimeon** [comment]
It seems that from everything @bbarker and I have read, the pure JS and thus portable way is HEAD

**Comment by tilgovi** [comment]
True, not sure that gives anything better than making a HEAD request.

One thing to to check, though, is whether the PDF viewer is treated as same origin with the PDF URL. It may be that we can't make a HEAD request at all, or that we can't see the Link header in the response since it's not a "simple header" under CORS. In Chrome, we whitelist our own backend for cross domain requests, but I'm not sure we'd want to make that a blanket permission. It would require some thought.

The more I think about it, though, the more I actually like the idea of injecting the headers as tags in the PDF.js viewer. Why not? It would have to be done for each browser differently but PDF.js already has code for each browser specifically and they're already tapping the right events so they can do things like detect content-type before the page starts to download and switch to the PDF viewer even when the URL doesn't end in .pdf.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
