### ISSUE TITLE
Respond to browser URL changes for single-page apps

### ISSUE THREAD

**Issue by afomi** [hypothesis/h#2233]
As a User,
I'd like to be able to annotate unique URL's in my "single-page" Ember app.

**Comment by tilgovi** [comment]
@afomi is the change a hash change or a history API change?

**Comment by felipecocco** [comment]
I have experienced issues in an Angular App as well. When I tried out Hypothesis in other pages, as I navigated through different pages it seemed that in between page-loads the hypothesis icon will flicker, presumably re-initializing with the new page's content. In the Angular App I tried, as the routes change this does not seem to happen. However, if I just click the icon twice -- "refreshing" hypothesis -- it seems to behave correctly. The app is NOT running in html5mode, and the browser navigation (back and forward buttons) transitions correctly between the two states.

**Comment by judell** [comment]
Tagged: compatibility

**Comment by afomi** [comment]
HI @tilgovi, I'm using Ember's history implementation. I'd imagine the hash change would be similar, but perhaps even more tricky, for annotation.

**Comment by tilgovi** [comment]
If anyone here would like to try some untested code out on the latest release, see if something like this can help you: 

https://gist.github.com/tilgovi/aba591cf857efbb847c0

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
