### ISSUE TITLE
uncaught exception using ebsco pdf viewer

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2262]
The URL: http://eds.a.ebscohost.com/eds/pdfviewer/pdfviewer?sid=868e0f1a-8504-4eff-9edd-33406ff9edc6@sessionmgr4002&vid=2&hid=4213

In both Chrome and FF, no adder pops up on selection.

In Chrome console: Uncaught TypeError: window.annotator.showFrame is not a function

(Two users evidently tried to work around this issue, it [looks like](https://hypothes.is/stream?q=uri:http:%2F%2Feds.a.ebscohost.com%2Feds%2Fpdfviewer%2Fpdfviewer%3Fsid%3D868e0f1a-8504-4eff-9edd-33406ff9edc6@sessionmgr4002%26vid%3D2%26hid%3D4213) they selected, got nothing, clicked the toolbar note icon, and made page-level notes that they intended as selection-based notes.)

**Comment by RawKStar77** [comment]
The PDF is in an iFrame. That's why selection is not working. There a bunch of similar issues open around this topic:
https://github.com/hypothesis/h/issues/2244
https://github.com/hypothesis/h/issues/2134
https://github.com/hypothesis/h/issues/2244

I'm closing this issue, as I believe that there are enough existing issues around iframe problems (feel free to reopen if you feel this is in error). This is a know limitation.

**Comment by judell** [comment]
D'oh, my bad, I am aware of the iframe issue, just forgot to check that in this case. Thanks @RawKStar77.

**Comment by judell** [comment]
This is another reminder that we need to [manage user expectations when functionality must degrade](https://github.com/hypothesis/vision/issues/190)
