### ISSUE TITLE
Chrome extension mixed content warning

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#2268]
Extension built with `hypothesis-buildext conf/development.ini chrome --base 'https://127.0.0.1:5000'` (and running h on https):

The page at 'https://127.0.0.1:5000/viewer' was loaded over HTTPS, but requested an insecure image 'http://127.0.0.1:5000/assets/images/noise_1.png'. This content should also be served over HTTPS.`

**Comment by tilgovi** [comment]
Huh, yes, that's totally strange. I'm wondering if this is a case of you having run it without https before and having not cleaned the CSS out. I suspect this because that image is a background image referenced from the CSS, so if the CSS files got built with a different scheme you'd have those stale lines.

**Comment by seanh** [comment]
Assigning this to myself - I'll remember at some point to play with it some more and see if I can pin it down.

**Comment by tilgovi** [comment]
I bet this is because the assets were already built. Since you were running a dev extension that loads from the repo and the checksums didn't change the assets weren't rebuilt. The CSS, therefore, was specifying the absolute path to the location when you had loaded the application previously without SSL. This should be fixed since 59aeb9222b378b90abf080235dd8558940d46776.
