### ISSUE TITLE
Provide a site: query facet

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#2305]
> As a site publisher, I want to know when a page of my site has been annotated.

One way to come at that is to provide an Atom feed (and/or Stream filter) that is domain wide.

We have `uri:` but you've got to be reeeaal specific for that to work. Using wildcards would likely run us into weeds with URL formats.

So...how about `domain:` as a "vector" of search filtering?

That would allow me to do (the not yet possible, but super useful):
`http://hypothes.is/stream?domain:hypothes.is" and see *everything* annotated on that site.

**Comment by judell** [comment]
As per https://github.com/hypothesis/h/pull/2184#issuecomment-98879105, a site facet was introduced but then withdrawn and is waiting in the wings. Close this for now?

**Comment by dwhly** [comment]
Or just let it stand with an updated title as the open issue waiting for the site facet PR.
Side question: should uri:domain.tld/* work too?

**Comment by tilgovi** [comment]
should uri:domain.tld/* work too?

No. That's a valid character in a path. We can't treat it as a wildcard, as far as I know.

**Comment by tilgovi** [comment]
> If I want to listen to a path for annotations, for instance, as an instructor with material under my department/professor path at a university, where would I do that? uri: or site: ?

Probably not URI since it was the overloading of URI with this use case and the obvious one (exactly *this* URI) that caused me to draft the site facet to begin with.

**Comment by tilgovi** [comment]
FWIW the way I drafted the site facet it was hierarchical, "thing.com" included "thing.com/<anything>" and "thing.com/place" included "thing.com/place/<anything>".

**Comment by judell** [comment]
*FWIW the way I drafted the site facet it was hierarchical, "thing.com" included "thing.com/" and "thing.com/place" included "thing.com/place/"

All the requests I've heard imply wildcarding. Assuming we can't have and/or don't want wildcards in the query URL, maybe site: should mean that, and we punt on more precise path semantics?

**Comment by BigBlueHat** [comment]
@tilgovi I'm cool with the ever increasing narrowing of the path as you described--essentially a `*` wildcard after `thing.com` or `thing.com/place` from what I understand.

Bringing it back would be valuable on so many levels.

FWIW, punting on the "path semantics" (and only focusing on supporting `thing.com` querying) would be fine by me, but that path based stuff you described should stay in the queue--ex: `twitter.com/bigbluehat` etc.

**Comment by BigBlueHat** [comment]
Another request just came through from support@ for this feature in relation to Slack integration. Ideally (then) we'd need this on the RSS, Atom, and JSON (`/api/search`) feeds (ideally).

It's a key piece of the puzzle for CMS integrations (WordPress, Drupal, etc) also, fwiw.

**Comment by edsu** [comment]
I just added the js to [my jekyll blog](http://inkdroid.org) (very bland I know) -- and now I understand why people want this. If I'm going to rely on you to keep my annotations it would be nice to be able to get them out somehow for backup, etc.

**Comment by judell** [comment]
Feature is planned.

**Comment by tilgovi** [comment]
Is there an issue tracking it or did you close this accidentally?

**Comment by BigBlueHat** [comment]
@judell think maybe you clicked the wrong button? :smile:

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
