### ISSUE TITLE
Better error message when 3rd-party cookies are blocked

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/h#2306]
At the moment, users using the bookmarklet will encounter the rather unhelpful message "Session is invalid" if they attempt to log in with a browser that is blocking third-party cookies.

See [this support thread for an example](https://groups.google.com/a/hypothes.is/d/msg/support/NjJMYcvaxbw/hY_Pb6VPZz0J).

It should be possible to detect this situation and display a more helpful message explaining to the user how to add an exception for Hypothesis.

**Comment by tilgovi** [comment]
> It should be possible to detect this situation

:-/ maybe if we used a sentinel cookie and did some explicit test, because I'd like us to be setting the httponly flag for our session cookies as a security measure and that seems to interfere with the ability to know whether it's working.

I'd prefer we just put effort into #914 instead and close this as won't fix.

**Comment by judell** [comment]
+1. Progress on #914 is much needed for all the reasons cited, let's focus there.
