### ISSUE TITLE
Toolbar hides PDF.js scrollbar 

### ISSUE THREAD

**Issue by JJediny** [hypothesis/h#2307]
Playing with CSS found that changing width from 37px to 30px atleast allows a viewer to click/drag the semi-hidden scrollbar that is otherwise unclickable

.annotator-frame .annotator-toolbar {
  position: absolute;
  left: -33px;
  width: 30px;
  z-index: 2;
}

![image](https://cloud.githubusercontent.com/assets/6350035/8099712/38897c9c-0fcf-11e5-8022-5ac053f23b9a.png)

**Comment by tilgovi** [comment]
We had issue #1657 for this. The conclusion there was that we made the scollbar clickable even _through_ the sidebar. Is that still working?

I think the next step to addressing this is to change our PDF.js integration to put the annotation frame inside the main container so that it's inside the scrollable PDF pane.

**Comment by JJediny** [comment]
Without the css override using Chrome's Dev Tools I was not able to click and drag with the pointer - the scroll bar works but I'm not putting the ticket in for myself :)

**Comment by tilgovi** [comment]
Huh. I can use the scrollbar here. In any case, I'll leave this open because it would be nice to put the sidebar inside an appropriate pane in PDF.js viewer.

**Comment by judell** [comment]
*I can use the scrollbar here.*

Clicking through the sidebar works when it's expanded. When not, not. 

This is about pushing the toolbar a bit leftward so, when the sidebar is collapsed,  you can target a narrow section of the slider, like so:

![image](https://cloud.githubusercontent.com/assets/46509/8140477/a80d309e-1110-11e5-9f15-9045039a9b05.png)

**Comment by judell** [comment]
@conordelahunty, I tested the fix proposed by @JJediny and it works as described, creating a narrow space to the right of the toolbar icons so you can sneak in there and scroll.

**Comment by conordelahunty** [comment]
@judell Would this quick fix effect the sidebar on every document or only
on PDFs?

**Comment by tilgovi** [comment]
Could be done so that it's PDF only, but I think we can find a better solution.

**Comment by judell** [comment]
@conordelahunty any more recent thoughts on separating the h toolbar from the page's scrollbar?

**Comment by conordelahunty** [comment]
@judell I did have another idea actually but it's probably needs a little design exploration. Let's make a card and I can put it in my queue.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
