### ISSUE TITLE
Integrate with Radium viewer

### ISSUE THREAD

**Issue by etopian** [hypothesis/h#2332]
It would be very nice if hypothesis worked with Readium viewe like it does with PDF.js and epub.js

https://github.com/readium/readium-js-viewer
https://github.com/futurepress/epub.js

**Comment by tilgovi** [comment]
Thanks for asking about this.

Everything that is needed for a basic integration with epub.js should already exist and in the past there was a working example. That code has gone out of date but if you want to help restore it or just track the issue you should look here: https://github.com/futurepress/epub.js/issues/157

I'm going to close this issue since as much as possible I would prefer that integration with third party projects be handled by those projects or by glue projects.

However, if there are things we can do in this project to make the integration easier in a way that's generic, please open issues. An example of that would be something like, "Configurable parent container for sidebar" or "Toolbar drag gestures break fixed layout integrations" just to make some things up from my head (the first is already done, the second I'm just guessing might be an issue).
