### ISSUE TITLE
Extension UI does not load on clicking icon if the current web page is not loaded completely 

### ISSUE THREAD

**Issue by apurvajalit** [hypothesis/h#2347]
This could be the desired behavior in a lot of cases but could be an issue when main content of the page is rendered quickly but other elements like ads take a long time to load or just don't load at all. In such cases, the user might not understand why the extension UI is not opening.

**Comment by tilgovi** [comment]
The icon should at least change to indicate that the click was processed, even if we defer loading.

**Comment by robertknight** [comment]
The changes in https://github.com/hypothesis/h/pull/2657 will make it easier to add some kind of state indicator in the badge or tooltip if we're waiting for the page to load.

Really though, we don't need to wait for all the third-party content to load - what I had in mind to do was to try and just wait for the HTML of the main page (aka. `DOMContentLoaded`) to fire and then inject the sidebar.

**Comment by tilgovi** [comment]
The problem with such a change is that it either introduces more
differences between the extension and the embed or hurts the viability of
the embed code.

As a publisher, I want to be sure my content is never delayed by third
party addons.

I watched this play out at Meebo, where, despite a lot of engineering going
into ultimately making the entire first payload smaller than a Like button,
sites removed the chat bar. If "waiting for meebo.com" appeared in the
status bar _ever_ before users were fully engaged with loaded first party
content it didn't matter what benchmarks we showed them.

In the end the embed code aggressively deferred loading the application
until as late as possible, which is the behavior I tried to replicate by
using async, defer, appending scripts at the end, and then domready.

**Comment by robertknight** [comment]
Thanks for the background info @tilgovi , that's useful context.

**Comment by judell** [comment]
@robertknight shall we close this one?

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
