### ISSUE TITLE
Reply Action in Gmail/Google Inbox

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#2447]
Just an idea. :bulb:

I came across this while digging up some JSON-LD stuff for the Annotation WG. It seems we can add a button to the Gmail & Inbox UI's to route people to the reply page of an annotation when they receive a notification of the conversation.

It would look something like this:
```html
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "EmailMessage",
  "potentialAction": {
    "@type": "ViewAction",
    "target": "https://hypothes.is/a/d1fmi6NfTR6FroFyDJ5CaA",
    "name": "Reply"
  },
  "description": "Reply to tilgovi's comment on your annotation"
}
</script>
```

(note: the "target" URL above is not a reply to an annotation...I couldn't find one from the stream... :stuck_out_tongue_closed_eyes:)

If we do that, we'd get a quick click button in the message listing similar to the "View issue" button you see on GitHub emails.

These are known as [Go-To Actions](https://developers.google.com/gmail/markup/reference/go-to-action), and look to be the easiest ones to create.

**Comment by tilgovi** [comment]
:+1:

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
