### ISSUE TITLE
Latest Firefox addon validation report

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#2448]
@tilgovi @nickstenning I believe you both have access to this report.

Skipping down to the warnings:
https://addons.mozilla.org/en-US/developers/addon/hypothesis/file/296290/validation#suite-results-tier-2

Some highlights from the warnings list:
- [ ] Mouse events may cause performance issues. (x11)
- [x] DOM mutation event use prohibited *Done: old PDF code has been replaced*
- [x] JS prototype extension
- [ ] Access to the `Function` global
- [ ] `open` called in potentially dangerous manner
- [ ] `setTimeout` called in potentially dangerous manner (x7)
- [ ] Access to the `eval` global
- [ ] Use of deprecated SDK module (this is in our fallback code for old FF's)
- [ ] `contentScript` properties should not be used (x2)
- [ ] createElement() used to create script tag (...and this...is how we do what we do... :confounded:)

Not sure how we want to route / plan for these, or if it's time (or soon will be) to consider building a full-on, honest-to-goodness Firefox addon that cuts with the grain of their addon system.

:fire::wolf:

**Comment by tilgovi** [comment]
DOM mutation event use prohibited

O.o ????

**Comment by tilgovi** [comment]
Oh, we don't use DOM Mutation Events. The old PDF code we had did. Now we use Mutation Observers.

**Comment by tilgovi** [comment]
Converted to a checklist.

**Comment by robertknight** [comment]
>  [ ] setTimeout called in potentially dangerous manner (x7)

This is about the various mechanisms that can be used to eval a string of potentially untrusted code. It affects a lot of third party libraries as well. Chrome uses CSP to prevent execution of untrusted code at runtime from privileged extension code.

The good news is that Mozilla are busy developing a [set of APIs](https://wiki.mozilla.org/WebExtensions) to support running Chrome extensions and easy portability of Chrome extensions to Firefox is an explicit goal for them - so I think they will be receptive to changes that make this easier.

**Comment by tilgovi** [comment]
Oh, that's _excellent_.

As far as `eval` goes, we're using the ng-csp directive in the Angular code now. As far as I know there are only a couple places where we still use `eval` or the `Function` constructor. One is documented in #2445 and the other is in Annotator (but removed in Annotator 2.0-dev) `Util.getGlobal()`.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
