### ISSUE TITLE
Chrome: not obvious to new users that browser action button toggles annotator overlay

### ISSUE THREAD

**Issue by edrex** [hypothesis/h#2473]
I added an annotation to [a google sheet](https://docs.google.com/spreadsheets/d/1u1_H6gbuJ0T5Hhk2fjZxO5lWEHhPhOP_PqA05edgBGQ/edit#gid=0), then I realized that Annotator's inline UI was interfering with Google Sheets somehow. I reloaded the page to try to get rid of Annotator but, I think because it found an existing annotation, the UI loaded again.

I don't see a way, other than disabling the Chrome plugin, to avoid loading Annotator for this page.

Ideas:

 - maybe a close button that breaks down annotator for the current page load (is that what was removed in #2167?)

Ideally annotator should play nice with every site the user might visit, so it probably doesn't make sense to add a bunch of UI surface area to work around a problem that should never happen.

**Comment by tilgovi** [comment]
What do you have in mind as a close button that is different from turning the extension off for that tab? The extension is per-tab. You do not have to disable the plugin, just turn annotation off.

**Comment by edrex** [comment]
I hadn't realized that the extension button toggles the UI overlay, that makes total sense.

It seems like the visual queue that the button is a toggle is pretty weak (it just increases the value of the foreground graphic from the deactivated state):

<img width="87" alt="hypothes is chrome extension button - deactivated" src="https://cloud.githubusercontent.com/assets/14615/9563889/5482fc9a-4e48-11e5-9cfc-e9a6e241bf60.png">
<img width="109" alt="hypothes is chrome extension button - activated" src="https://cloud.githubusercontent.com/assets/14615/9563888/547bdee2-4e48-11e5-9bef-e3955afe9132.png">

What about reusing Chrome's "activated" styling for when the pointer is still down?

<img width="112" alt="hypothes is chrome extension button - activated proposal" src="https://cloud.githubusercontent.com/assets/14615/9563887/5463f43a-4e48-11e5-99dd-9fe2ee3c7dc1.png">

I'm not sure if there's a straightforward way for an extension to borrow that styling, or provide its own.

**Comment by edrex** [comment]
Reading the [browserAction docs](https://developer.chrome.com/extensions/browserAction), it seems like the only options for indicating state are updating the icon or adding badge text. Does hypothes.is' branding have a strong accent color?

**Comment by judell** [comment]
@conordelahunty what's your feeling about a stronger look when active?

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
