### ISSUE TITLE
Annotations missing from PDF.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2476]
A number of annotations were made against this PDF.
https://nfllabor.files.wordpress.com/2015/05/investigative-and-expert-reports-re-footballs-used-during-afc-championsh.pdf

They are no longer re-attaching using the chrome extension.  Here's the list of them...
https://hypothes.is/stream?q=seanjregan

I'll note that the stream URI query is not returning them, that may be a separate issue.
https://hypothes.is/stream?q=uri:https://nfllabor.files.wordpress.com/2015/05/investigative-and-expert-reports-re-footballs-used-during-afc-championsh.pdf

**Comment by tilgovi** [comment]
The URL search is a non-issue. Those annotations were made on an older version of Hypothesis and an older version of Via. At that time Via was perhaps not setting the right canonical URL and Hypothesis was storing the URN instead of the URL as the primary URI. The result is that the primary URI of the annotation is the urn:x-pdf identifier and the secondary URL in the document metadata is a via.hypothes.is URL. The URL you searched for is not in these annotations anywhere.

If I make a new annotation now, with Via or otherwise, the data is correct.

What's not clear is why no equivalence is formed between the Via URL and the HTTP URL after I make a new annotation, given that the URN matches in both cases.

**Comment by nickstenning** [comment]
So apart from the fact that the URIs on this document are stored as

```
https://via.hypothes.is/static/__shared/viewer/web/viewer.html?file=/id_/https://nfllabor.files.wordpress.com/2015/05/investigative-and-expert-reports-re-footballs-used-during-afc-championsh.pdf
```

which is obviously wrong and now won't be matched by searches for

```
https://nfllabor.files.wordpress.com/2015/05/investigative-and-expert-reports-re-footballs-used-during-afc-championsh.pdf
```

as made by the current client, there's another issue here. The PDF fingerprint as reported by PDF.js is:

```
> PDFViewerApplication.documentFingerprint
"07fad32194629740b9e67febbe84e99c"
```

but stored on the annotations, we have:

```
"urn:x-pdf:7fad32194629740b9e67febbe84e99c"
```

Notably, the leading zero has been stripped. Which is odd to say the least.

**Comment by nickstenning** [comment]
This appears to have been fixed by the recent via migration.
