### ISSUE TITLE
Don't clobber reply targets

### ISSUE THREAD

**Issue by tilgovi** [hypothesis/h#2480]
It should be fine for a "reply" to specify additional targets. Annotations can have more than one target and that gives them a lot of representational power that wouldn't be possible with single targets only.

Currently, we interpret annotations that have `references` field as "replies" and give them a target of their parent.

I'm starting to think we should either be having the client send annotations that are already formatted correctly as replies or we should have a separate endpoint for replying that doesn't take annotations, even if the result is that we create an annotation and fill in these fields.

**Comment by seanh** [comment]
One thing to watch out for is that if the reply already contains a target with a given scope, then we probably shouldn't add another target with the same scope

**Comment by tilgovi** [comment]
Ah, you said the same thing on this and #2479. It makes more sense here.

I think if the reply has a target we probably shouldn't do anything.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
