### ISSUE TITLE
Contextualizing Hypothesis JSON into Web Annotation JSON-LD

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#2482]
https://lists.w3.org/Archives/Public/public-annotation/2015Jul/0194.html
> Here's what I have so far:
..on the JSON-LD playground...
http://json-ld.org/playground/#/gist/5b3a8a89bea268ee7343

> ...and as a GitHub Gist--where you can fork, comment, etc....
https://gist.github.com/BigBlueHat/cd7cfcddecd1dce5f32f

> There's a good bit of ambiguity, selector type's don't "upgrade", there's
not a "RangeSelector" type (so the partial XPath's used by Annotator get
lost), and obviously there's a bunch of blank nodes to care about. :-/

> These are the variations I've made to the WD's context definition:
Added:
 - "@base": "http://hypothes.is/api/annotations/"
 - "id": "@id"
 - "tags": "oa:Tag"
Changed:
 - annotatedAt to created
 - serializedAt to updated
 - body to text
 - annotatedBy to user

> (I think that's all of them)

> I'm actually quite happy with how far it got. :) However, it's obviously
incomplete, looses data, and other not so great things...

> I'd be curious to know if there are ways to do this correctly (using just a
custom context with *no* data modifications) or if this is a fool's errand.

> If it's possible, then I can "upgrade" all the Hypothesis annotations to
Web Annotation Data Model JSON-LD with the addition of one file and one URL
to the payload...

There was a little follow-up discussion, but mostly the conclusion was that this JSON-LD conext I'd come up with was as close as we could get (at the time). There's a few more changes coming to the model with regards to multiple bodies (which we already have as `text` and each tag will become a separate annotation body in the model soon). Once those land, I'll create a new Gist / demo.

For now, how do we feel (given the above) about publishing a `Link` header (at least) and responding to `application/ld+json` with this (or a future, updated) JSON-LD context file?

The result is:
 - some support for the Web Annotation model (it's not yet a lossless, bi-directional thing, but the output is still accurate Web Annotation data)
 - those who understand it could export public (or personal, when we provide that) annotation in Web Annotation
 - support for Web Annotation without "breaking" our current format or changing it...much (however, the new multi-bodies work may mean a larger change in our output format)

The alternative is to provide a completely different API view where the output JSON-LD would look more similar to what you see in the [Web Annotation Data Model spec](http://www.w3.org/TR/annotation-model/).

So...options:
1. output this `Link` header & respond to `application/ld+json` in the current JSON format (no mods needed)
2. create a more complete alternative representation expressly for Web Annotation "export" where the JSON looks more similar to the spec's examples

Preference?

**Comment by tilgovi** [comment]
Our API already should respond to `application/ld+json` with JSON. Would the `Link` header be all that's required then?

**Comment by tilgovi** [comment]
(Our API doesn't actually do any content negotiation, it just responds always with JSON)

**Comment by BigBlueHat** [comment]
Yep. Just the `Link` header:
http://www.w3.org/TR/json-ld/#h3_interpreting-json-as-json-ld

**Comment by akuckartz** [comment]
> Please note that JSON-LD documents served with the application/ld+json media type MUST have all context information, including references to external contexts, within the body of the document. Contexts linked via a http://www.w3.org/ns/json-ld#context HTTP Link Header MUST be ignored for such documents.

http://www.w3.org/TR/json-ld/#h3_interpreting-json-as-json-ld

**Comment by BigBlueHat** [comment]
@akuckartz great to know, thanks! I'd missed that earlier.

So, our steps to make this happen would be:
 - [] publish static JSON-LD context file
 - [] add the `Link` header to `application/json` output
 - [] handle `application/ld+json` content negotiation *and* add the necessary `@context` key to that output

I think there's value to doing these steps sooner than having the entirety of our JSON mapped into the Web Annotation model. Doing that bit is likely an ongoing process.

**Comment by akuckartz** [comment]
@BigBlueHat A fourth step might be to reverse the second step at the end and to output the JSON-LD serialization also when `application/json` is requested.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).

**Comment by akuckartz** [comment]
This mass-closure of unresolved issues is a really **bad** idea. It obviously **does** indicate the intention to ignore the content of all those issues - and therefore a significant amount of ("long and unwieldy") contributions by the community. You could have simply tagged them as "idea or feature request".

**Comment by nickstenning** [comment]
Hi Andreas. Thanks for your concern. I'm sorry you think it's a bad idea. The issues, and the discussions on them, haven't gone anywhere, as you've just demonstrated by continuing a conversation on an issue that is still present, searchable, and readable but now marked with a red icon instead of a green one. We have no intention of ignoring the content in them -- my reference to "long and unwieldy" was solely with regard to the use of GitHub issues for tracking work. 100-comment-long issues don't make it easy for developers to work out what they're supposed to be doing.

We are working on making Hypothesis the best it can be, and even have people whose full-time job it is to engage with and understand the needs of our community! All of the issues I've closed have been discussed at length both internally and externally, and we continue to use community input as the primary factor for prioritising our work. We're working on the things we think the community deems most important, as fast as we possibly can.

We remain committed to developing in the open, and will continue to evolve our process and use of the various tools available to us as we grow and learn. In this instance we're pretty sure that closing these issues will allow us to more effectively manage the tracking of defects in Hypothesis.

**Comment by akuckartz** [comment]
I just spent two minutes to find out what happened after this issue was closed without resolving it. I failed and found nothing. To me that confirms what I wrote above about two years ago in https://github.com/hypothesis/h/issues/2482#issuecomment-182625264
