### ISSUE TITLE
extension and via conflict with embed at http://biostor.org/reference/145822/page/16

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2491]
main.js:48 Uncaught TypeError: Cannot read property 'offsetWidth' of null hypothes.is/assets/scripts/hypothesis.min.js?275ad5fc:5 Unhandled promise rejection TypeError: Cannot read property 'nodeType' of undefined(…)(anonymous function) @ hypothes.is/assets/scripts/hypothesis.min.js?275ad5fc:5 hypothes.is/assets/scripts/hypothesis.min.js?275ad5fc:5 Unhandled promise rejection TypeError: Cannot read property 'nodeType' of undefined(…)

**Comment by tilgovi** [comment]
Are you sure? We take pretty good care to prevent double embeddings of any kind.

**Comment by tilgovi** [comment]
I can't reproduce this report with via.

**Comment by judell** [comment]
Retitled. The error that seems to prevent annotations from rendering in chrome is:

Unhandled promise rejection DOMException: Failed to execute 'postMessage' on 'Window': An object could not be cloned.(…)

Other errors reported (in chrome, both via and extension) that do not prevent annotations from rendering:

Uncaught TypeError: Cannot read property 'offsetWidth' of null

Unhandled promise rejection TypeError: Cannot read property 'nodeType' of undefined(…)

**Comment by tilgovi** [comment]
The `offsetWidth` error appears to come from a google maps library and not us. It happens in Chrome regardless of the deployment mechanism.

The unhandled promise rejections about `nodeType` don't appear to be a real problem. They are caused by some selector type failing to anchor, but they don't cause problems beyond that and other selectors may anchor for the same target.

In Chrome, I don't see any problem with anchoring with the extension. I see lots and lots of annotations anchored. So I'm not super worried about the `nodeType` errors.

The `postMessage` issue you may want to report in Via. I suspect it's got nothing to do with a conflict between embeddings. The way via embeds h, as I understand it, h is supposed to be exempt from various kinds of rewriting. That should be true whether the site includes the embed script or via injects it, afaik.

**Comment by judell** [comment]
OK, will report in via.
