### ISSUE TITLE
Local pdf annotation is using file path?

### ISSUE THREAD

**Issue by edsu** [hypothesis/h#2492]
I made some annotations on my workstation at home this morning for a local PDF and then came to work and opened the exact same file (it's on DropBox) and my annotations didn't show up. 

Here is the query that h is doing:

https://hypothes.is/api/search?limit=200&offset=0&order=asc&sort=created&uri=file:%2F%2Flocalhost%2FUsers%2Fed%2FDropbox%2FBibDesk%2FPapers%2FSaracevic%2FInformation%2520Science.pdf

I got to thinking it might be interesting to try to use the a content identifier (md5, sha, etc) to identify the content rather than the path. I think my DropBox may have a slightly different path on my different workstations for whatever reason. You can see my annotations of the PDF at home here:

https://hypothes.is/api/search?limit=200&offset=0&order=desc&sort=created&user=acct:edsu@hypothes.is&tags=Saracevic:1999

It's interesting to see the `urn:x-pdf:0db3bc850da249578a0f723fd2b5768d` in the Document metadata already, so maybe this is almost working? If h used that to query instead it should get them?

https://hypothes.is/api/search?limit=200&offset=0&order=desc&sort=created&uri=urn:x-pdf:0db3bc850da249578a0f723fd2b5768d

**Comment by edsu** [comment]
I noticed that I wasn't logged in to h at work. Once I logged in my annotations showed up! But note, it is still querying using the file path, now it is slightly changed perhaps as the result of logging in?

https://hypothes.is/api/search?limit=200&offset=0&order=asc&sort=created&uri=file:%2F%2Flocalhost%2FUsers%2Fed%2FDropbox%2FBibDesk%2FPapers%2FSaracevic%2FInformation%2520Science.pdf

**Comment by judell** [comment]
Same as https://github.com/hypothesis/h/issues/2486?

**Comment by tilgovi** [comment]
I'm not sure if we have an issue for this or not. @nickstenning is closest to this work.

I think there are a couple issues going on here:

- The document location is the primary reference for PDF annotations. Fingerprint is secondary.
  - It currently requires annotation of each URL for the equivalence to the fingerprint to be established.
  - We currently expose filesystem details when users annotate PDFs locally.
  - When the new URI normalization code is turned on, as is currently, I don't think the fingerprint will be used at all.
- Annotation is currently required to establish document equivalence

**Comment by judell** [comment]
The error that prevents annotations from anchoring, when via is used in conjunction with this H-embedding site, appears to be:

Unhandled promise rejection DOMException: Failed to execute 'postMessage' on 'Window': An object could not be cloned.(…)

**Comment by edsu** [comment]
I wonder if the content fingerprint could be the primary reference for local files? It seems like it could be useful when the same file is edited by different users on different systems? For example I'm in a class right now where the professor has posted PDFs to an online syllabus. When you click on the PDF link you are prompted to download the PDF -- I guess this is a function of the content-type on the response? I think it's still fairly common at any rate.  It would be neat if we could see each other's annotations despite the fact that we might download the file to different locations. Or maybe this is too much of a corner case to be worth it. 

Still perhaps it's interesting to think about hanging annotations off of content identifiers, especially in the context of things like [IPFS](https://ipfs.io/).

**Comment by tilgovi** [comment]
I would love for the fingerprint to be the primary reference, at least for local annotations if not always. I find it very problematic that we include the file: URL at all and have argued against it before. In the context of Hypothesis, the public service, where we say we support pseudonyms, it's kind of unacceptable if, by annotating a local PDF, your _real name_ suddenly shows up in our public stream because of a "file:///Users/Randall Leeds/Documents/....".

**Comment by judell** [comment]
@edsu as per above -- "It currently requires annotation of each URL for the equivalence to the fingerprint to be established" -- was this the case? I.e. did you create annotations from both a local and a DropBox URL?

**Comment by robertknight** [comment]
> I got to thinking it might be interesting to try to use the a content identifier (md5, sha, etc)
> to identify the content rather than the path.

At Mendeley this is pretty much what we did and you can get a very long way with this for published works (ie. content that is not actively being updated) because there is very often only one copy in circulation.

**Comment by edsu** [comment]
@judell actually the annotations were hung off of the file:// URL that pointed at where I had mounted DropBox on my local file system. So I wasn't using Dropbox URLs. Does that help? I apologize for the confusion.

**Comment by edsu** [comment]
@robertknight Thanks! That's great to hear that it worked well in practice at Mendeley.

**Comment by judell** [comment]
"So I wasn't using Dropbox URLs."

And if you do?

**Comment by edsu** [comment]
@judell I'm confused about what you are asking me to do.

**Comment by judell** [comment]
@edsu sorry. I haven't used DropBox in a while, not sure how things lay out
w/respect to local vs web URLs. Setting that aside, are you able to host
that PDF at some non-local web address, even just temporarily?

**Comment by edsu** [comment]
@judell Are we testing that annotations of a pdf at a URL and annotations of the same pdf on local filesystem will all show up?

**Comment by nickstenning** [comment]
The issue here is exactly what @edsu has already identified, and trying different combinations of URLs is only going to confuse the issue further.

Here's the problem:

1. Create annotation on PDF with URL A and fingerprint X
2. Open PDF with URL B and fingerprint X: see no annotations

Here's the solution, which we've discussed before:

- When we search for annotations for a document, we need to search by all known identifiers for that document. We don't currently do so.

**Comment by judell** [comment]
Yes.

Until that solution is baked, there's this:


   1. Create annotation on PDF with URL A and fingerprint X
   2. Open PDF with URL B and fingerprint X: see no annotations
   3. Create annotation with URL B and fingerprint X

Now, in the current system, URL A and URL B are aliases.

**Comment by edsu** [comment]
Yep, and to see all the annotations you need to:

4. Reload page to see all the annotations.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
