### ISSUE TITLE
erroneous annotations appearing for pdf file in via

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2506]
URL: https://www.lib.ucdavis.edu/dept/admin/plan/ucd-library-strategic-plan-2013-16.pdf

API query results: https://hypothes.is/api/search?uri=https://www.lib.ucdavis.edu/dept/admin/plan/ucd-library-strategic-plan-2013-16.pdf -> 0

VIA URL: https:/via.hypothes.is/https://www.lib.ucdavis.edu/dept/admin/plan/ucd-library-strategic-plan-2013-16.pdf

Expanded VIA URL:

https://via.hypothes.is/static/__shared/viewer/web/viewer.html?file=https%3A%2F%2Fwww.lib.ucdavis.edu%2Fdept%2Fadmin%2Fplan%2Fucd-library-strategic-plan-2013-16.pdf

Query executed by H client in VIA context: https://hypothes.is/api/search?limit=200&offset=0&order=asc&sort=created&uri=https:%2F%2Fvia.hypothes.is%2Fstatic%2F__shared%2Fviewer%2Fweb%2Fviewer.html%3Ffile%3Dhttps:%2F%2Fwww.lib.ucdavis.edu%2Fdept%2Fadmin%2Fplan%2Fucd-library-strategic-plan-2013-16.pdf -> 48 results

URIs in result set:

https://via.hypothes.is/static/__shared/viewer/web/viewer.html?file=https://doc-00-3c-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/4p9rafgo15va8d5bkk3v5borbo3jlmek/1442347200000/12051615087829900932/*/0B9Xu_6XK8Y6dMDNZYmEwemdBdE10NmxwYnhNdnY4OWNDQVNJ?e=download

https://via.hypothes.is/static/__shared/viewer/web/viewer.html?file=https://gimmeshelter2015.files.wordpress.com/2015/09/joan-didion-goodbye-to-all-that-1.pdf

etc.

Questions: 

Are we normalizing to https://via.hypothes.is/static/__shared/viewer/web/viewer.html?

Why is that prefix appearing in the database?

Was this a recent change, and if so, what? (Several reports indicate this is a new behavior.)

**Comment by nickstenning** [comment]
As far as I'm aware there's nothing in the URI normalisation code either old [or new](https://github.com/hypothesis/h/blob/master/h/api/uri.py) that deals explicitly with URLs from via. Via (if I understand it correctly) is *intended* to address this issue by [injecting a "rel=canonical" into all pages](https://github.com/hypothesis/via/blob/54115f811b2298e51b871d4d6f4369e57bfdbb02/templates/banner.html#L2) — if they don't already have one — pointing at the original page's URL.

Unfortunately, [it doesn't look like that happens for PDFs].

So, why the problem now when we think it's worked before? I suspect it's because we're now treating the page URL as the primary identifier for PDFs, and searching only by that when we load the page. Previously we kicked off searches for every known URI, which would have included the fingerprint generated by PDF.js as well.

The straightforward fix, then, would probably be to start sending all known URIs with the query. (But ideally not sending multiple queries, as before.)

But to me that's still a bit nasty, because it relies entirely on the PDF fingerprint. This fingerprint is, as far as I can tell, not a standard, and depends wholly on implementation details of PDF.js. Using that as the primary indicator of document identity seems unwise. A better fix would be to investigate the feasibility of injecting a `rel="canonical"` link into the PDF viewer in via.

**Comment by tilgovi** [comment]
The fingerprint is a standard.

**Comment by tilgovi** [comment]
It's in the PDF specification. The first half is supposed to be fixed, the second half is supposed to change if the document is updated.

There's no specification, IIRC, for how to pick a fingerprint, though. It's also not mandatory for it to exist (but it mostly seems to in the wild).

PDF.js just reports the fingerprint, which is in the PDF metadata, it doesn't generate one.

**Comment by dwhly** [comment]
> PDF.js just reports the fingerprint, which is in the PDF metadata, it doesn't generate one.

If no DocumentID is present, or malformed, PDFjs will generate one. (https://github.com/mozilla/pdf.js/pull/5602) But since all Adobe compliant authoring tools create it, usually present.

**Comment by nickstenning** [comment]
I'm happy to be wrong!

**Comment by judell** [comment]
I think we have a more immediate concern than PDF fingerprints.

There are 1245 annotations whose uri fields contain some form of via URL. The major patterns are:

1. http://via.hypothes.is/[h]/DOMAIN/URL

ex: http://via.hypothes.is/9781421412948-108eliot2/9781421412948-108eliot2.pdf
ex: https://via.hypothes.is/h/http://acert.hunter.cuny.edu/blog/annotating-texts/2015/03/24/

2. http://via.hypothes.is/[h]/SCHEME://DOMAIN/URL

ex: https://via.hypothes.is/http://arstechnica.com/information-technology/2015/04/29/windows-10-updated-again-to-build-10074/
ex: http://via.hypothes.is/h/SCHEME://DOMAIN/URL

3. https://via.hypothes.is/static/__shared/viewer/web/viewer.html?file=HTTP(S)://DOMAIN/URL

ex: https://via.hypothes.is/static/__shared/viewer/web/viewer.html?file=http://arxiv.org/pdf/1312.6114v10.pdf

In general I wonder why any of these should ever appear in the database, seems like the uri field should only ever be SCHEME://DOMAIN/URL (or just DOMAIN/URL?)

However, pattern #3 is of greatest current interest. It only shows up starting on 9/15/2015. This coincides with the discontinuity that several users reported this week. What changed on 9/15/2015? I know that correlation != causation, but something changed on Tuesday and the timing does correlate with this issue.

BTW, @tilgovi, we speculated out of band as to why there are not many more erroneous annotations appearing if the cause were simply normalization to https://via.hypothes.is/static/__shared/viewer/web/viewer.html. Here is perhaps why: the results from the query executed by the via client above are only for domains that match pattern 3.

**Comment by judell** [comment]
I think we have a more immediate concern than PDF fingerprints.

There are 1245 annotations whose uri fields contain some form of via URL. The major patterns are:

1. http://via.hypothes.is/[h]/DOMAIN/URL

ex: http://via.hypothes.is/9781421412948-108eliot2/9781421412948-108eliot2.pdf
ex: https://via.hypothes.is/h/http://acert.hunter.cuny.edu/blog/annotating-texts/2015/03/24/

2. http://via.hypothes.is/[h]/SCHEME://DOMAIN/URL

ex: https://via.hypothes.is/http://arstechnica.com/information-technology/2015/04/29/windows-10-updated-again-to-build-10074/
ex: http://via.hypothes.is/h/SCHEME://DOMAIN/URL

3. https://via.hypothes.is/static/__shared/viewer/web/viewer.html?file=HTTP(S)://DOMAIN/URL

ex: https://via.hypothes.is/static/__shared/viewer/web/viewer.html?file=http://arxiv.org/pdf/1312.6114v10.pdf

In general I wonder why any of these should ever appear in the database, seems like the uri field should only ever be SCHEME://DOMAIN/URL (or just DOMAIN/URL?)

However, pattern #3 is of greatest current interest. It only shows up starting on 9/15/2015. This coincides with the discontinuity that several users reported this week. What changed on 9/15/2015? I know that correlation != causation, but something changed on Tuesday and the timing does correlate with this issue.

BTW, @tilgovi, we speculated out of band as to why there are not many more erroneous annotations appearing if the cause were simply normalization to https://via.hypothes.is/static/__shared/viewer/web/viewer.html. Here is perhaps why: the results from the query executed by the via client above are only for domains that match pattern 3.

**Comment by judell** [comment]
I think we have a more immediate concern than PDF fingerprints.

There are 1245 annotations whose uri fields contain some form of via URL. The major patterns are:

1. http://via.hypothes.is/[h]/DOMAIN/URL

ex: http://via.hypothes.is/9781421412948-108eliot2/9781421412948-108eliot2.pdf
ex: https://via.hypothes.is/h/http://acert.hunter.cuny.edu/blog/annotating-texts/2015/03/24/

2. http://via.hypothes.is/[h]/SCHEME://DOMAIN/URL

ex: https://via.hypothes.is/http://arstechnica.com/information-technology/2015/04/29/windows-10-updated-again-to-build-10074/
ex: http://via.hypothes.is/h/SCHEME://DOMAIN/URL

3. https://via.hypothes.is/static/__shared/viewer/web/viewer.html?file=HTTP(S)://DOMAIN/URL

ex: https://via.hypothes.is/static/__shared/viewer/web/viewer.html?file=http://arxiv.org/pdf/1312.6114v10.pdf

In general I wonder why any of these should ever appear in the database, seems like the uri field should only ever be SCHEME://DOMAIN/URL (or just DOMAIN/URL?)

However, pattern #3 is of greatest current interest. It only shows up starting on 9/15/2015. This coincides with the discontinuity that several users reported this week. What changed on 9/15/2015? I know that correlation != causation, but something changed on Tuesday and the timing does correlate with this issue.

BTW, @tilgovi, we speculated out of band as to why there are not many more erroneous annotations appearing if the cause were simply normalization to https://via.hypothes.is/static/__shared/viewer/web/viewer.html. Here is perhaps why: the results from the query executed by the via client above are only for domains that match pattern 3.

**Comment by tilgovi** [comment]
I wonder if we updated the PDF.js code in via last week and dropped the rel
canonical?

**Comment by nickstenning** [comment]
If we focus on pattern 3, there are two distinct problems here:

1. URIs are currently stripped of their query string for normalisation for most users. We already know about this and it's already fixed in the `search_normalized` feature which is still only turned on for staff.

   This can be verified by looking at the number of different URLs returned by a query for `https://via.hypothes.is/static/__shared/viewer/web/viewer.html?file=https:%2F%2Fwww.lib.ucdavis.edu%2Fdept%2Fadmin%2Fplan%2Fucd-library-strategic-plan-2013-16.pdf`:

        $ curl -sSL 'https://hypothes.is/api/search?limit=200&offset=0&order=asc&sort=created&uri=https:%2F%2Fvia.hypothes.is%2Fstatic%2F__shared%2Fviewer%2Fweb%2Fviewer.html%3Ffile%3Dhttps:%2F%2Fwww.lib.ucdavis.edu%2Fdept%2Fadmin%2Fplan%2Fucd-library-strategic-plan-2013-16.pdf'  | jq '.rows[].target[0].scope[0]' | sort -u | wc -l
        18

   Notably, if you're logged in as staff and make the same query, there is only one result -- the annotation I just made at that URL. This means that the new URI normalisation code is working as expected.

2. For some reason, we're not using the correct URLs for PDFs loaded in via. Specifically, as Jon notes, we seem to be using the full viewer HTML URL rather than a canonical URL for the PDF, possible only since last week. I'm not yet sure why this is or whether Via has ever correctly set `rel="canonical"` links for PDFs. In the mean time, as I articulated above, we could resolve this by making PDF fingerprints the primary URI by which we identify PDF documents.

**Comment by dwhly** [comment]
> I'm not yet sure why this is or whether Via has ever correctly set rel="canonical" links for PDFs. In the mean time, as I articulated above, we could resolve this by making PDF fingerprints the primary URI by which we identify PDF documents.

It seems like ideally we should store both the fingerprint (yay, this would address https://trello.com/c/vl2y9mLI/130-show-annotations-for-a-pdf-not-yet-associated-with-a-filename-or-url), perhaps making it primary, and also make sure we're storing (and checking for) the canonical URL if available-- perhaps because of older PDF annotations that may have only been associated with URLs?

**Comment by judell** [comment]
Why would the viewer URL, or indeed any URL with a Via prefix, ever be the value for Uri in a stored annotation?

**Comment by nickstenning** [comment]
> Why would the viewer URL, or indeed any URL with a Via prefix, ever be the value for Uri in a stored annotation?

The question is why would it not? That's the value of `window.location.href` on that page.

The only reason it's ever ​*not*​ the via URL is because we have code that explicitly looks for a `<link rel="canonical"...>` that via manually injects into the proxied page.

We *should* never be storing via-prefixed URLs, but avoiding doing so is a special case, not the default.

**Comment by judell** [comment]
"avoiding doing so is a special case, not the default" Understood. A better question to have asked: Why not strip the known via-related prefixes from the value that's stored in the uri field? It is a special case, we create it and we know about it, why involve the aliasing machinery here?

For me, at least, it'd be easier to reason about PDF fingerprints and aliasing if those things were completely orthogonal to via prefixes.

**Comment by tilgovi** [comment]
> Why not strip the known via-related prefixes from the value that's stored in the uri field?

The share feature is a special case, where via acts like any other sharing service in a sense, but in generally I avoided making the application aware of Via at all. Particular with things like this, it's much better if we can leverage general solutions rather than have small bits of hardcoded Via-related things in H.
