### ISSUE TITLE
Feature flags don't pay proper attention to permissions

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2529]
Turn on a feature flag (for admins or staff) ...
-- show_unanchored_annotations
...for instance.

Log out of H.
Go to the stream: https://hypothes.is/stream
You'll see the orphan message at the bottom of the cards.

That should not happen.

I also noticed that if the --groups flag was turned on (for admins or stafft) that on our blog, at for instance, here:
https://hypothes.is/blog/back-from-budapest/

That a ton of annotations would anchor to the page, in the manner of what was happening before the most recent patch that prevented the worst of this.  Again, log out of H. so that you're clearly not either staff or admin, and you can see the same thing.

EDIT: It seems now that those spurious annotations are now showing up on the blog regardless of any feature flagging (they're there now for instance-- unless we have it set wrong).  Jeremy notes:

"i thought we had fixed this
old annotations lingering on the WP install
randall pushed something
we checked it
but now it's back again"

**Comment by nickstenning** [comment]
> You'll see the orphan message at the bottom of the cards.

This isn't true (unless I'm missing something) if you:

- refresh the page
- open an incognito window
- wait a few minutes

It's happening because the values of feature flags are cached on the frontend, and so when you log out you still have the values of the flags from when you were logged in. This is confusing, granted, and we can fix it, but it won't be affecting any "real" users.

> I also noticed that if the --groups flag was turned on (for admins or stafft) that on our blog, at for instance, here... a ton of annotations would anchor to the page

I can't replicate this. As long as the "search_normalized" flag is switched on, that's not true.

*However*, someone switched the "search_normalized" flag off for staff.

I'm going to close this issue and open one new one about clearing flags when you log out. Nothing else seems to be going wrong here.
