### ISSUE TITLE
chrome badge doesn't track doc equivalence

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2559]
I'm working with a partner who will support people annotating a Drupal site. The titles (and so URLs) of the annotated articles are editable (in Drupal) by the annotators. The partner is adding a permanent URL as metadata of the form:

&lt;link rel="canonical" href=".../drupal_node_id/...">

In this situation, annotations are immune to changes in the URL that's displayed by Drupal on the browser's URL-line. An annotation made to http://some_version_of_the_url.html will anchor to http://another_version_of_the_url.html. So far, so good!

However the Chrome badge is not immune to that change. It will show a count for http://some_version_of_the_url.html  but not for http://another_version_of_the_url.html.

**Comment by lenazun** [comment]
Can we get some actual URLs examples to test this discrepancy?

**Comment by judell** [comment]
Yes. I can't share the partner's URLs, could fabricate equivalents, but it should be obvious if we compare the API query the app makes, which is visible in the console debugger, to the API query the badge makes, which isn't.

**Comment by nickstenning** [comment]
Is this a report of an actual bug or a speculation of a potential one?

There's no reason at all the badge query shouldn't track document equivalence, as it uses the same search endpoint as everything else.

**Comment by judell** [comment]
An actual bug. I'll try to recreate it based on the info and screenshots I
captured on a hangout with the partner.

**Comment by judell** [comment]
Here is the repro:

jonudell.net/h/test1.html

&lt;html>
&lt;head>
&lt;style>
body { font-family: verdana; margin: .75in }
li { margin-bottom: 10px }
&lt;/style>
&lt;/head>
&lt;body>
This is a test.
&lt;/body>
&lt;/html>
`
![image](https://cloud.githubusercontent.com/assets/46509/10235565/570a738e-6852-11e5-87fa-83221aea5397.png)


jonudel.net/h/test2.html

&lt;html>
&lt;head>
&lt;style>
body { font-family: verdana; margin: .75in }
li { margin-bottom: 10px }
&lt;/style>
&lt;link rel="canonical" href="http://jonudell.net/h/test1.html">
&lt;/head>
&lt;body>
This is a test.
&lt;/body>
&lt;/html>

![image](https://cloud.githubusercontent.com/assets/46509/10235570/67e0a336-6852-11e5-9ef5-d244e0b0e488.png)

**Comment by judell** [comment]
Observation: I checked in Fiddler and the queries aren't the same on the wire. The badge does not encode the url, the sidebar does. Could it be that in the normal case that's OK but when routing through the aliasing machinery it isn't?

**Comment by judell** [comment]
Observation: I checked in Fiddler and the queries aren't the same on the wire. The badge does not encode the url, the sidebar does. Could it be that in the normal case that's OK but when routing through the aliasing machinery it isn't?

**Comment by nickstenning** [comment]
URL encoding isn't part of the issue. Here's what you've done (I think).

1. create pages A and B
2. on page B, add a `<link rel="canonical">` that points to page A (i.e. B ---> A)
3. create an annotation *on page A*

Now, on creating an annotation on page B, the sidebar will detect the `<link rel="canonical">` and use the URL in the link tag to describe the annotation. That is, regardless of which page you create it on, the annotation will reference page A in its `target` property. But it will only reference page B if you create it on page B, because on page A we have no information about page B's existence.

When you come back later with the sidebar and it executes a search query, it again detects the link tag (if present) and sends a query for the canonical URL. That is, even on page B, it will search for annotations on the URL of page A.

The badge isn't even remotely as smart as the sidebar. It just sends a query for `window.location.href`, assuming the server will solve all the URI normalisation and document equivalence issues for it.

This would all work fine if we actually had information on the server that page A and page B were the same. One way of creating such information would be to create an annotation on page B, which I've now done. As you can see, the badge numbers are now correct on both pages.

So the long and the short of it is this: until you create an annotation on page B, we don't have any information which tells us that page A and page B refer to the same document.

As for fixing this, there are basically two options:

1. Make the badge smarter, and allow it to scan for page metadata.
2. Preemptively submit page equivalence data to the server, without waiting for an annotation to be created.

My preference would be to lean towards option 2.

**Comment by judell** [comment]
Wasn't 2) already contemplated as part of the completion of the doc
equivalence work?

**Comment by nickstenning** [comment]
Yep, definitely.

**Comment by nickstenning** [comment]
I'm going to close this issue. If you want to open an issue or create a card to track the underlying issue, please do.
