### ISSUE TITLE
can the extension override via?

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2586]
Among other reasons:

Badge count: 0, https://via.hypothes.is/https://personaldemocracy.com/media/why-our-webs-are-rarely-world-wide-and-what-we-can-do-about-it

Badge count: 3, https://personaldemocracy.com/media/why-our-webs-are-rarely-world-wide-and-what-we-can-do-about-it

**Comment by nickstenning** [comment]
Nothing is overriding anything, but the chrome extension badge is asking "are there any annotations on `https://via.hypothes.is/https://personaldemocracy.com/media/why-our-webs-are-rarely-world-wide-and-what-we-can-do-about-it`", to which the answer is no, because the annotations that are visible there are annotations on `https://personaldemocracy.com/media/why-our-webs-are-rarely-world-wide-and-what-we-can-do-about-it`.

So, this isn't a bug, but it is I suppose a missing feature. I think the smartest way to solve this is on the server: we need to add a rule to our URI normalisation that strips "https://via.hypothes.is/" from the front of any URL.

**Comment by judell** [comment]
Indeed. And in fact I thought we already were? If not this can be retitled to ask for that. 

Having the extension override via is a separate concern.

**Comment by tilgovi** [comment]
I would handle this on the front-end to reinforce the idea that our front-end code and via form a coherent whole client experience. The back-end doesn't know much about where it's deployed or if via is also deployed.

**Comment by tilgovi** [comment]
Meanwhile, the front-end already assumes via is in use and it creates the share link.

**Comment by nickstenning** [comment]
I'm going to close this issue. If you want to open an issue or create a card to track the underlying issue, please do.
