### ISSUE TITLE
UI breakage, unnecessary re-loading when logging in in sidebar fails

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#2642]
![untitled screencast - cropped 4](https://cloud.githubusercontent.com/assets/22498/10610462/d3006be6-773f-11e5-9417-125b77c7c82c.gif)

**Comment by robertknight** [comment]
I was able to reproduce this consistently (once every 2-3 attempts) with master from a few days ago using Angular 1.2.x

I'm not able to reproduce using a current master build with Angular 1.4.x however.

There is still a brief flash during load where both the 'Clear Search' and 'Clear Selection' buttons are visible but the view updates once the load completes.

**Comment by seanh** [comment]
> There is still a brief flash during load where both the 'Clear Search' and 'Clear Selection' buttons are visible but the view updates once the load completes.

Same here

**Comment by robertknight** [comment]
The flashing that is occurring is due to the `ng-show` directive being invoked asynchronously _after_ the template is compiled and linked in this particular case.

On first load, the following happens, all in the same `$digest` cycle:

1. `<search-status-bar>` directive compiled
2. `<search-status-bar>` linked
3. Watcher created by `ng-show` to hide the buttons in `<search-status-bar>` is invoked

When attempting to login with incorrect credentials however, (1) and (2) happen first in the same digest cycle and (3) then happens later in a separate cycle. During the gap between (2) and (3), you see the buttons flash in the UI.

The reason for these events happening in a separate cycle has something to do with the `DeepCountController` directive which is used to update message counts. In the second case above, when (1) and (2) happen, a $digest call invoked by `DeepCountController` appears on the stack, when (3) happens, the `$digest` call is in response to a `Browser.completeOutstandingRequests` callback in Angular.

If I remove the call to `scope.$digest` in `DeepCountController`, the flashing doesn't happen.
