### ISSUE TITLE
H unusably slow on michigan UP press page

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2651]
This page has H embedded on it and is unusably slow: http://quod.lib.umich.edu/d/dh/13474172.0001.001/1:9/--ethical-programs-hospitality-and-the-rhetorics-of-software?g=dculture;rgn=div1;view=fulltext;xc=1

**Comment by robertknight** [comment]
A [Chrome JS profile](https://www.dropbox.com/s/hn97g5c5d2z5amy/gh2651.cpuprofile?dl=0) shows that most of the time is being spent in diff-match-patch

**Comment by judell** [comment]
@robertknight the root cause here is that all pages in the set share a common doi, which means we alias them all to that, which means every annotation in the set tries to anchor on every page.

**Comment by robertknight** [comment]
@judell - I didn't check how many annotations there were in total but H should still cope better.

**Comment by tilgovi** [comment]
@robertknight it might help to use `raf` in guest.coffee around parts of the `anchor` method. Careful, though, not to allow too much concurrency here. If the anchoring is splitting and changing text nodes, concurrent anchoring can clobber each other. I backed away from this because I wanted to play it safe.

Other than that, we _really_ need to invest in a better implementation of approximate matching that the one from Diff-Match-Patch. Unfortunately, the DMP API is blocking. Without significantly complicating the dom-anchor-text-quote code, it's not possible to tolerate large changes in anchor position without introducing this potential for latency.

**Comment by tilgovi** [comment]
What I mean by "significantly complicating the dom-anchor-text-quote-code" is that it's possible to do something like chunk the text of the document so that the search can be done in pieces, with control given back to the UI in between. It actually might not be terribly bad to do it, but a better implementation of approximate matching that is 1) asynchronous/streaming, 2) multi-pattern and 3) treats edit distance and location distance separately.
