### ISSUE TITLE
api query for tag with uppercase succeeds only if lowercase

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2655]
Tags in use for that URI:

{
  "tags": [
    "LT2015"
  ]
},
{
  "tags": [
    "LT2015",
    "JJJS"
  ]
}

https://hypothes.is/api/search?tags=LT2015

{"rows": [], "total": 0}

https://hypothes.is/api/search?tags=lt2015

{ "rows":[...], "total": 22 }

I did not think we were case-sensitive at all, never mind oppositely so. I'll add some tests to the query correctness suite.

**Comment by tilgovi** [comment]
This is because the `TagsMatcher` is using a term query :-/. I tried _really_ hard to argue against keeping the tags and tags alias, but instead tags was implemented specially, and here we a bug in the special case :-/.

But also I think this is somewhat fallout from your insistence that tags should be exact matches, generally, and not match, say, a similar tag that has a space in it and an additional word. So, this is following your request, @judell, to the letter. What you're now asking is that tags are exact matches modulo case.

Some clarity on requirements is needed. My personal feeling is still, as you know, that there should be exactly one name for the "tag" field, that it shouldn't be handled specially, and that /stream should be a search API and not a strict filtering API. There seems to still be confusion about this endpoint and its facets.

**Comment by jeremydean** [comment]
i'm not finding that switching to lower case fixes the issue here:

https://hypothes.is/stream?q=tag:%27%23RVC190%27

**Comment by jeremydean** [comment]
here's another case where it doesn't seem to be capitalization only, but the use of the hashtag symbol:

https://hypothes.is/stream?q=tag:%27d004x%27

i actually think it would make sense to automatically strip the hashtag symbol in tag creation as it's a hold over from twitterspeak and not really functional (in fact, disfunctional in this case) within h.
