### ISSUE TITLE
Incorrect vertical alignment of dropdown menu labels in IE 10, 11

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2659]
Tested under IE 10 on Win 7 and IE 11 on Win 10:

![ie11-vert-menu-alignment](https://cloud.githubusercontent.com/assets/2458/10669033/ce4f36de-78d6-11e5-8064-97c503957d62.png)

![ie11-vert-menu-alignment-2](https://cloud.githubusercontent.com/assets/2458/10669107/11e4bc5c-78d7-11e5-9fb2-27eda486f675.png)

**Comment by judell** [comment]
Did you test IE 11 / Win 10 using the bookmarklet? I ask because that browser/OS combo fails for me in via (cf https://github.com/hypothesis/via/issues/59, https://github.com/hypothesis/via/issues/55).

Using the bookmarklet with IE 11 / Win 10 I can confirm your observation but am also seeing the sidebar occluded by the scrollbar.

![image](https://cloud.githubusercontent.com/assets/46509/11280803/822f4b68-8eac-11e5-9cac-762b9664e2ec.png)

**Comment by nickstenning** [comment]
Moved to https://github.com/hypothesis/client/issues/257.
