### ISSUE TITLE
"You must be signed in to create annotations" when creating highlights when not signed in

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#2692]
You can create highlights without being signed in to h, and when you do sign in they're silently saved to the server. While you're still signed out though you get one of these cards in the sidebar for each highlight you create:

![screenshot from 2015-10-29 18 00 17](https://cloud.githubusercontent.com/assets/22498/10827470/2ea3b128-7e67-11e5-9629-d0313eebb203.png)

Problems with this:

* The error message shouldn't be in the form of an annotation card, mixed in with all the other cards in the sidebar (these can actually appear in-between other cards or be scrolled off screen)

* The error message refers to annotations not highlights

* A new one of these cards appears for every highlight you make

* We let the user make highlights but don't save them to the server. We also don't (successfully) notify the user in any way that they weren't saved - creating highlights does not cause the sidebar to open. Even if it did, I don't think there's any guarantee that the error message annotation would be on screen. If the user closes the tab, or navigates to another page, their highlights are lost.

Many of these problems are also relevant when this same error message is used for creating annotations when signed out.

I wonder if we should completely redesign this part of the user experience (annotating and highlighting while signed out).

**Comment by nickstenning** [comment]
> I wonder if we should completely redesign this part of the user experience (annotating and highlighting while signed out).

Yes. This error message was always supposed to be a temporary hack.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
