### ISSUE TITLE
Research Unicode IVS support

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#2721]
(could also be considered a Bug depending on what our full Unicode support plans are)

From @tkanai's I18N research:

https://ja.wikipedia.org/wiki/%E8%91%9B%E5%9F%8E%E5%B8%82 represents a good example of [Unicode IVS](http://www.unicode.org/reports/tr37/) (see the [example](http://www.unicode.org/reports/tr37/#w1aac17b1) there for a quick understanding of the issue).

@tkanai's report:
> Unicode IVS is a feature provided in Unicode 6.0. It is a mechanism to add a tag to a letter to precisely point to a slightly different glyph. Good thing is that old Unicode systems, including old fonts can ignore the foreign tags and continue to show its mother glyph instead.
> The link above is one of the famous example page for Unicode IVS. The page is about a city in Nara prefecture, but the first letter of the city name is not listed in Unicode character list. To show the first letter, it is necessary to use Unicode IVS.
> Please take a look at the image file attached. The circle is the glyph what I’m expecting, but as you can see the boxes in blue, they glyphs are differently rendered in the annotation window. The root cause of this issue is that the font which is applied for the cited text in the Annotation window does not contains the same glyph with the web page and show the “mother” letter as its fallback. To solve this issue, the cited text in the annotation window should use the same font with the web page.

Image attached.
![unicodeivs](https://cloud.githubusercontent.com/assets/43209/11122241/50ccb238-8928-11e5-9987-766ddeb2a96e.PNG)

**Comment by BigBlueHat** [comment]
Also, I missed a key point from @tkanai--that this Unicode IVS issue can effect MathML rendering as well. In the end, we'd need to support a display font (for quoted content) that supports Unicode IVS.

The selection bits related to MathML are probably a separate thing to consider / understand / improve.

Cheers!

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
