### ISSUE TITLE
z-index too high for link hinting with keyboard driven browser

### ISSUE THREAD

**Issue by holtzermann17** [hypothesis/h#2759]
I use Pentadactyl (http://5digits.org/pentadactyl/), which allows me to follow URLs by number using the keyboard. Specifically, pressing <kbd>l</kbd> followed by <kbd>`<number>`</kbd> first decorates the links with numbers and then visits link numbered `<number>`.  But the Hypothes.is toolbar manages to have a z-index that keeps it on top of the numbers.

![zindex](https://cloud.githubusercontent.com/assets/179958/11503302/c60f86b0-9837-11e5-97d5-8d3b3443c6a9.jpg)

**Comment by nickstenning** [comment]
Thanks for reporting this. It's difficult to know what we can do about this, because both we and Pentadactyl have the same problem -- trying to insert UI into other people's pages without prior knowledge of what the highest z-index on that page will be.

We'll certainly look into our options, though.

**Comment by holtzermann17** [comment]
As a work-around I changed the `z-index` in my [dactyl.css](https://github.com/5digits/dactyl/blob/54fb39d13910b4680abc20d7b693b6f5058ae342/common/skin/dactyl.css#L21) to 2147483648, which is one more than the `z-index` used in the hypothesis toolbar.

**Comment by nickstenning** [comment]
I'm relabeling this as a bug, as I believe our "expected behaviour" should be "don't break accessibility tools".

**Comment by nickstenning** [comment]
Moved to hypothesis/client#242.
