### ISSUE TITLE
pdf.js plugin extraction

### ISSUE THREAD

**Issue by Canifex** [hypothesis/h#2782]
Hey,

is it possible to have the pdf.js annotation plugin only or is there any guide how to extract it? I think many users would be interested in just using the great pdf.js plugin you wrote, but might need another handling of what to do with annotations.

Greetings,

**Comment by nickstenning** [comment]
Hi there! Thanks for getting touch. Could you clarify what you're interested in? A Hypothesis extension that only works on PDFs and not on HTML documents? Or something else?

**Comment by Canifex** [comment]
Yeah, I just need your great pdf plugin: The possibility to select text in the in pdf.js opened pdf and click on "highlight" or "add comment". I need custom behaviour, if someone clicks on one of these buttons.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
