### ISSUE TITLE
issues using via on iOS 

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/h#2811]
trying to annotate a PDF on an iPad using via. (believe i'm using iOS version 9.2?)

it's possible, but there's some bugginess:

1) annotate/highlight button appears in bottom left of screen rather than next to text selection

2) cannot click on highlights to open annotations

3) cannot make sidebar scroll

4) cannot click out of sidebar to text--must close sidebar manually

**Comment by dwhly** [comment]
I've noticed these as well.  With point 1) I will note that originally, @JakeHartnell had set things up so that if a selection was active, clicking the annotate icon on the toolbar/heatmap (i.e. not the adder) would launch an editor with the selection incorporated.  Currently clicking the icon just launches a page note.

**Comment by robertknight** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;zvmbTi4a&#x2F;328-spike-suggest-improvements-to-mobile-touch-support"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [SPIKE] Suggest improvements to mobile&#x2F;touch support</a>

**Comment by robertknight** [comment]
> 1) annotate/highlight button appears in bottom left of screen rather than next to text selection

Will be fixed by https://github.com/hypothesis/h/pull/3347

**Comment by nickstenning** [comment]
Item 1) is now fixed (#3347 has been merged). Items 2) and 4) I have split out into their own issues as #3397 and #3398 respectively. Item 3) is now #3268.

Closing.
