### ISSUE TITLE
Users report being logged out frequently

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2876]
We have had several reports of users being frequently logged out of the service. We need to investigate what is going on, examine possible causes and identify any additional monitoring that may be useful.

Internal reports:
- https://hypothesis.zendesk.com/inbox/tickets/68

**Comment by lenazun** [comment]
We investigated reports of this between Jan 15 and Jan 20th.  Seems like people were being logged out because the db server was handling a heavier load than usual.   
However, we occasionally hear reports of users being logged-out unintentionally during other times.  We may want to investigate these separately.

**Comment by nickstenning** [comment]
> Seems like people were being logged out because the db server was handling a heavier load than usual.

There are many kinds of problems that could cause but at the moment I can't think of any way it could result in people being prematurely logged out.

**Comment by judell** [comment]
Can the forthcoming client telemetry help us investigate?

**Comment by nickstenning** [comment]
I'm going to close this. We have a card for it (in the sprint, no less) and we don't have any repro steps here so it's difficult to know when this is fixed as written.
