### ISSUE TITLE
Federate annotations

### ISSUE THREAD

**Issue by Somantiq** [hypothesis/h#2897]
Federate annotations via https://matrix.org/ - each domain should probably map to a Matrix room. This would make it easy for anyone to watch and participate in a discussion around a particular site without leaving their favorite discussion platform.

**Comment by nickstenning** [comment]
Thanks for this suggestion! We've chatted previously with the folks from Matrix about the possibilities here.

If you want to help us discuss what this might look like, we'd love to hear about it on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). I'm going to close this because we're going to be using GitHub issues for bug reports only.
