### ISSUE TITLE
Via error while trying to annotate a page on CloudFlare

### ISSUE THREAD

**Issue by lenazun** [hypothesis/h#2909]
Steps to repro:

Go to 
https://via.hypothes.is/cafe.com
https://via.hypothes.is/https://medium.com/@nayafia/we-re-in-a-brave-new-post-open-source-world-56ef46d152a3

Expected:  via loads with the page
Actual:  You will get an error message:

```
Please enable cookies.
Error 1000 Ray ID: 26ef2a0da3261e5f • 2016-02-03 15:28:12 UTC

DNS points to prohibited IP

What happened?

You've requested a page on a website (cafe.com) that is on the CloudFlare network. Unfortunately, it is resolving to an IP address that is creating a conflict within CloudFlare's system.

What can I do?

If you are the owner of this website:
you should login to CloudFlare and change the DNS A records for cafe.com to resolve to a different IP address.

CloudFlare Ray ID: 26ef2a0da3261e5f • Your IP: 54.219.24.245 • Performance & security by CloudFlare
```

**Comment by judell** [comment]
https://support.cloudflare.com/hc/en-us/articles/200171976-Error-1000-DNS-points-to-prohibited-IP

**Comment by nickstenning** [comment]
This is, as suggested by the document above, caused by the CloudFlare edge detecting and aborting what they think is an infinite loop in the routing.

In this case it isn't, and we convince them of that by stripping the CF-specific headers from the request before we pass it through via. Adding the following to the via nginx configuration has fixed this issue:

```
more_clear_input_headers CF-Connecting-IP;
more_clear_input_headers CF-Ray;
more_clear_input_headers CF-Visitor;
more_clear_input_headers CF-Ipcountry;
```

**Comment by dwhly** [comment]
Awesome!
