### ISSUE TITLE
Locally-annotated doc produces unclickable link on group landing page

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2915]
The image shows a locally-annotated PDF:

![image](https://cloud.githubusercontent.com/assets/46509/12794252/081a9de8-ca69-11e5-8e30-650552632ae0.png)

Here is the HTML behind the link:

&lt;a title="pone.0115253 1..39">pone.0115253 1..39&lt;/a>

What to do about that fact we have nothing to put in an href attr? Probably:

1. Don't wrap an anchor tag around it

2. Add an asterisk linking to an explanation that the document is not on the web, will need to be separately acquired.

/cc @conordelahunty

**Comment by conordelahunty** [comment]
Instead of putting in an address should do something more like:

**pone.0115253 1..39**
_Local file_

Local file feels clunky though, perhaps private file?

**Comment by lenazun** [comment]
Just a note: this looks like a quick design change in the template, but it's not! I think it requires fiddling with the logic on presenters.py

**Comment by dwhly** [comment]
The reason I'd steer slightly away from "private" is that if I've emailed the file to someone else, and we're collaboratively annotating it together, then it's not actually private.  I could post the file via a dropbox share link to twitter for instance.  

I actually think local sounds good.
Local file: plos02.pdf
?

**Comment by seanh** [comment]
This needs agreement on exactly what should be displayed, before fixing it. Most recent suggestion was Dan's:

    Local file: plos02.pdf

(and no `<a>` tag).

That suggestion displays the filename only and not the document title. In the screenshot at the top of this issue there are two things: the document title `pone.0115253 1..39` that's encoded in the PDF file (we can't help how people title their documents), and the filename `plos02.pdf`. That's why it currently displays both: `pone.0115253 1..39 (plos02.pdf)`.

**Comment by nickstenning** [comment]
Fixed by #3200.
