### ISSUE TITLE
Duplicate highlights appear when activating and de-activating H multiple times on a page

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#3096]
**Steps to reproduce**

1. Go to https://example.com
2. Toggle H on and off a few times, slowly, giving H enough time to load
   each time that it is toggled on
3. After several repeats at step 2, hover the mouse over a highlight on the page

**Expected results**
 1. Highlights show up the same way each time that H is loaded and disappear
    when unloaded

**Actual Results**
 1. Highlights get darker each time that H is loaded
 2. "injector.bundle.js:1292 Uncaught TypeError: Cannot read property '$$tag' of undefined"

**Comment by nickstenning** [comment]
Additional details, copied and pasted from #3294:

---

### Steps to reproduce
1. Activate H extension on page
2. Create an annotation
3. De-activate H extension
4. Re-activate H extension on same page

### Expected behaviour
After step 4, annotations should appear on the page in the same state as after step 2.

### Actual behaviour
After step 4, all the annotated sections of the page are covered with two highlights instead of just one.

### Additional details
Logging the calls to `Delegator#subscribe()` and `Delegator#unsubscribe()` shows that when annotator is loaded, it subscribes to these events on `document.body` which are not unsubscribed when deactivating the extension:

'beforeAnnotationCreated',  'annotationCreated', 'annotationUpdated', 'annotationsLoaded', 'annotationsUnloaded', 'annotationDeleted', 'panelReady', 'setVisibleHighlights'

Consequently, when H is activated a second time and annotations are loaded, both the old and new instances of H handle the events and the result is that two sets of highlights get created.
