### ISSUE TITLE
Direct link fails on medium.com (and other sites that modify URL fragment on page load)

### ISSUE THREAD

**Issue by judell** [hypothesis/h#3137]
### Steps to reproduce
1. Visit https://hyp.is/L_OOCOt9RY6Eij3Q-fFiTQ using Chrome extension

### Expected behaviour
Sidebar opens, focuses and displays annotation

### Actual behaviour
Sidebar opens, focuses annotation, but displays "You do not have permission to see this annotation"

### Browser/system information
Chrome / Windows 10

### Additional details
The Medium URL, https://medium.com/intercom-inside/the-dribbblisation-of-design-406422ccb026#.f2jqk75gw, has its own fragment id which, in this case, we do not replace.

**Comment by robertknight** [comment]
Looks like Medium replaces the fragment identifier when the page loads regardless of whether there was one present in the original URL or not. In order to make this work, we'll either need to intercept the URL before the page starts loading, or we'll need to find another way to communicate the direct linked annotation ID to the Chrome extension.

**Comment by robertknight** [comment]
Additional example: https://bouncer-stage.hypothes.is/AVODh1WfH9ZO4OKSlQ6p

**Comment by robertknight** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;GtI22Tmz&#x2F;310-direct-links-to-medium-com-articles-do-not-work"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Direct links to Medium.com articles do not work</a>
