### ISSUE TITLE
Browser action badge doesn't update the annotation count when adding or removing annotations

### ISSUE THREAD

**Issue by shawninder** [hypothesis/h#3149]
### Steps to reproduce
1. Visit a page
2. Add an annotation

### Expected behaviour
The badge showing the number of annotations on a page should be updated to show the new number including the annotation you just added

### Actual behaviour
The badge is not updated. To get the new count, you need to refresh the page

### Browser/system information
Browser: Google Chrome Version 49.0.2623.87 (64-bit)
OS: OSX YOSEMITE 10.10.5
But I suspect this will happen on all versions chrome and chromium

### Additional details
The same issue can be observed when deleting an annotation

**Comment by nickstenning** [comment]
Hi @shawninder, thanks for reporting this.

This is a limitation of the badge, and is expected behaviour at the moment. In the future we may improve the badge so that it can update dynamically when annotations are created or deleted.

I'm going to close this issue as we use GitHub exclusively for tracking bugs -- that is, behaviour which deviates from what we expected or designed.
