### ISSUE TITLE
Missing proper sidebar: bug or feature?

### ISSUE THREAD

**Issue by orschiro** [hypothesis/h#3164]
Dear all, 

Is it a bug or feature that the annotation sidebar is not properly viewed side by side the website but instead overlaps it?

I always need to close the sidebar if I want to continue annotate the website which is an inconvenient workflow. Much nicer would be if both would be displayed properly side by side. 

Please see the example screenshot below.

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/14180069/69ddddd4-f759-11e5-92bf-0caecaa1a992.png)

**Comment by robertknight** [comment]
Hello @orschiro - I completely agree and we have discussed this a few times. This is a missing feature rather than a bug. We use the https://github.com/hypothesis/vision/ repository at the moment as a way for the public to discuss feature/improvement requests. One of the things that needs to be done next is to do some exploration into ways to collapse the page content and find out what is compatible with most web content and what is not.

I'm going to close this issue since we use the `h` repository purely for bug reports but please feel free to open an issue in the `vision` repository.

**Comment by orschiro** [comment]
Dear Robert,

Thank you so much for your elaborative response!

It's good to hear that this feature has been discussed before.

Do you want me to create a new issue at the vision repository or can you
point me to existing discussions that I can contribute to?

Thankfully,

~Robert
