### ISSUE TITLE
Remove annotation.groupid __world__ default from database

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3177]
We now enforce this default in schemas, so there's no need to repeat it in the database. See this comment <https://github.com/hypothesis/h/pull/3152#discussion_r58033815>

**Comment by nickstenning** [comment]
Hmm. I'm not so sure about this. It can be useful to have defaults in the model so that programmatic creation of annotations is easier.

I also don't really think duplicating the default in the validation layer imposes any significant costs. Grepping for `__world__` is hardly difficult. Alternatively, the validation layer could simply remove the `groupid` when appropriate so that the database default is used.

**Comment by seanh** [comment]
Happy with either solution, but I want to leave it until the existing postgres PRs (views/schemas, storage and models) have all been merged so any changes here can be tested on all of the code at once

**Comment by chdorner** [comment]
Alright, let's keep the duplication then, I'm happy with that.
