### ISSUE TITLE
"Message not available" when viewing standalone annotation page for reply

### ISSUE THREAD

**Issue by dwhly-proj** [hypothesis/h#3367]
### Steps to reproduce
1. Go here: https://hypothes.is/a/nHGb5iLTEea7IgcrLQDtzw

### Expected behaviour
This is a public annotation (actually a reply).  It should be visible.

### Actual behaviour
"Message not available"

### Browser/system information
Chrome

### Additional details
Clicked on "Reply to XX" in an email reply notification.  Got the error.

**Comment by robertknight** [comment]
So what is happening here is that the linked annotation is a reply. When the page loads, it fetches the annotation (a reply) from the server and then fetches the replies to that reply, of which there are none.

When the app builds the conversation thread, it infers from the `references` field of the reply that there should be a parent reply and a parent annotation, however those were not fetched in the initial query, so it ends up building this thread:

```
root
|-- <annotation (missing)>
      |-- <first reply (missing)>
             |-- <second reply (this is the reply that was originally fetched)>
```

When this thread is rendered, it gets rendered as a card with just `Message not available` on it, because the top-level annotation is missing.

**Comment by robertknight** [comment]
It would be a nicer experience here if we could fetch the entire conversation thread and then focus/highlight the linked reply.

**Comment by dwhly-proj** [comment]
+1

**Comment by memartone** [comment]
We are getting the same problem in email notifications that someone has replied to our annotation. If you click on "reply" in the email, it says "Message not available".  I think this is a rather serious issue if we want people to engage more around annotations.

**Comment by nickstenning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;vOUw3BbE&#x2F;609-bug-message-not-available-when-viewing-standalone-annotation-page-for-reply"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [BUG] &quot;Message not available&quot; when viewing standalone annotation page for reply</a>
