### ISSUE TITLE
Please describe how and which data is send. 

### ISSUE THREAD

**Issue by COLABORATI** [hypothesis/h#3572]
Please describe in the About Page of your website how this extensions communication with your servers and which data exactly is send. Does this extension make me use your webservers as a proxy? 
Thank you very much!

**Comment by nickstenning** [comment]
Thank you for the suggestion. We'll review it and look into adding some information on the about page about what data gets sent to the server.

I can summarise briefly by saying that the only data that gets sent to the server is as follows:

- The contents of your annotation, and the information about which part of the page you have annotated.
- Metadata about the annotated page, such as its location and title.

Additionally, if you have the extension badge turned on, the URL of each page you visit will be sent in a query to our servers to see if there are any annotations on that page. This can be disabled in the extension options.

The extension does not in any way proxy the content you are viewing through our servers.

Thanks for your question. If you have further questions would you please direct them to either our [support email address](mailto:support@hypothes.is) or [the developer mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev) rather than opening GitHub issues?
