### ISSUE TITLE
Is it possible to use this extension only locally without sending any data?

### ISSUE THREAD

**Issue by COLABORATI** [hypothesis/h#3573]
I did not find any option for this, however I would like to use this extension only locally, without sinding any data anywhere. Is this possible? Thanks for your attention!

**Comment by nickstenning** [comment]
I'm afraid this isn't currently possible, as the extension relies on annotation service with an HTTP API to save its annotations.

Thanks for your question. If you have further questions would you please direct them to [the developer mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev) rather than opening GitHub issues?
