### ISSUE TITLE
RSS Support

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#391]
And it's myriad applications (IFTTT, et al)

**Comment by seanh** [comment]
I've started working on an Atom feed for the /stream page based on @BigBlueHat's feed for Hypothesizer. I missed @tilgovi's comment about hAtom though..

**Comment by BigBlueHat** [comment]
@seanh so before we can do that we need the markup being output into the annotation page:
https://hypothes.is/a/KLUGtTMjTUSOPVvACd-dNA (see line ~452). Not much there...yet. :wink: 

Here's some work @tilgovi sent me earlier for rendering the annotation markup server-side (rather than only in Angular as we do now):
https://github.com/tilgovi/h/commit/d74654127f8c6ab0c28e6777079a581a1cf77e15

The Angular code would just replace (or ideally update) that markup once it was running.

Adding `hAtom` would be trivial (just some class names) once that's done...as would the RDFa work I've done.

**Comment by seanh** [comment]
An atom feed for the /stream page was added (including discoverability): https://github.com/hypothesis/h/pull/2072

**Comment by JakeHartnell** [comment]
@seanh what's the status of this issue? Is it done?

**Comment by dwhly** [comment]
https://trello.com/c/FIEIXoub/115-add-rss-support

**Comment by JakeHartnell** [comment]
Thanks @dwhly!

**Comment by seanh** [comment]
Not done, we did Atom not RSS

**Comment by nickstenning** [comment]
Closing. Yes we did Atom, not RSS, but we did a syndication format, which I think was the underlying feature request.

**Comment by BigBlueHat** [comment]
Re-opening as @judell sees a keen need for RSS support in addition to the Atom feed format:
https://trello.com/c/FIEIXoub/115-add-rss-support

The underlying feed format request is handled in https://github.com/hypothesis/vision/issues/170--which could maybe be closed if you're in the mood. :wink:

This one should stay open for now, however.

**Comment by BigBlueHat** [comment]
Fixed via https://github.com/hypothesis/h/pull/2456
