### ISSUE TITLE
New user and group search URLs are confusing

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4004]
[@dwhly said](https://github.com/hypothesis/product-backlog/issues/12#issuecomment-256103074):

> I think the URLs here are getting strange.  I know this is late in the game, but worth asking.
> 
> Why are we implementing a URL of the format `/groups/xyz123/search`  
> 
> Why don't we keep this simple and have URLs of the following structure:
> `/search?q=group:xyz123`   for the explicit search syntax.
> `/groups/xyz123/my-test-group` for the invite link, and after you've joined the group as an alias for
> `/search?q=group:xyz123`  
> 
> But:
> `/groups/xyz123/search?q=tag:foo`
> For what is essentially:
> `/search?q=group:xyz123&tag:foo`
> 
> Just seems odd to me.  I don't get the reasoning behind it.  
> 
> The activity page will be the home for the group.  So special case 
> `/search?q=group:xyz123`  and show `/groups/xyz123/my-test-group` instead.
> 
> If the person then clicks on a tag, switch to the multiple search term format:
> `/search?q=group:xyz123&tag:foo`

**Comment by seanh** [comment]
> The activity page will be the home for the group.  So special case 
> `/search?q=group:xyz123`  and show `/groups/xyz123/my-test-group` instead.
> 
> If the person then clicks on a tag, switch to the multiple search term format:
> `/search?q=group:xyz123&tag:foo`

Could be a good solution. What happens if I'm on `/groups/xyz123/my-test-group` and, rather than clicking on a tag or any other facet link on the page, I just type some keywords into the search box and hit Enter? Does that switch me to `/search?q=group:xyz123&some-keywords`?

Does the group's sidebar shown when on `/search?q=group:xyz123...` or only when on `/groups/xyz123/my-test-group`?

**Comment by dwhly** [comment]
> What happens if I'm on `/groups/xyz123/my-test-group` and, rather than clicking on a tag or any other facet link on the page, I just type some keywords into the search box and hit Enter? Does that switch me to `/search?q=group:xyz123&some-keywords` ?

That was my notion.

My conception of this is that:
1) It's nice to have simple, short vanity URLs for groups, users, etc that people can share, and that people think of as the home for things.
2) it's nice that the 'sharing URL' is the same as the 'home URL'.  which is what we have now w/ the current group landing pages-- so that it doesn't change when you go there, and so that the thing you grab in the address bar is always the same thing you share.
3) it's nice when the home URLs have the english version of the group name after them, i.e. `/groups/xyz123/my-test-group`  

> Does the group's sidebar show when on `/search?q=group:xyz123` ... or only when on `/groups/xyz123/my-test-group` ?

Here are a set of proposed rules:
- If there is a group facet in the search, or you are on the group's home URL, then show the group sidebar for the first group facet shown (i'm still wondering if there's a case for multiple group facets).
- Otherwise if there is a user facet in the search or if you are on the user's home URL then show the user sidebar for the first user facet shown.

The last thing I'd ask is if we should be using the same URL structure for groups that we do for users `/u/username` and `/g/xyz123/my-test-group`

**Comment by ajpeddakotla** [comment]
Agree w/ Dan's take on this issue here. 

Simple and clean approach to URL. 

Nick and I talked about this, and if the approach is to 
retain the "group profile" URL, i.e. `/group/abc123/my-group`
which is the same as the unfiltered group search, i.e. what is now `/group/abc123/search`

Than creates a possibly simpler implementation of the URL schema.

**Comment by robertknight** [comment]
Summarizing the above and a discussion on Slack (https://hypothes-is.slack.com/archives/public/p1479738063007759 ), the changes we need to make are:

1. User and group profile pages will have vanity URLs at `/users/{username}` and `/groups/{pubid}/{slug}` which show the `/search` route with the queries `user:username` and `group:pubid` respectively.
2. Searches for `user:username` or `group:pubid` will route the user to the vanity URLs. Searches for _any other query_ will route the user to `/search?q=...`
3. If the search query contains `group:` terms, then a group sidebar will be shown for the first group in the query. Otherwise if the search query contains `user:` terms then a user sidebar will be shown for the first user in the query.

**Comment by dwhly** [comment]
One more Q:  Can `https://hypothes.is/search?q=` simply be `https://hypothes.is/search`?

**Comment by seanh** [comment]
> If the search query contains group: terms, then a group sidebar will be shown for the first group in the query. Otherwise if the search query contains user: terms then a user sidebar will be shown for the first user in the query.

Currently the user sidebar is shown whenever you're on the user search page: `/users/<username>/search` (soon to be just `/users/<username>`), as opposed to `/search`. The group sidebar is shown whenever the URL is `/groups/<pubid>/search` (soon to be just `/groups/<pubid>/<optional slug>`) as opposed to the `/search` page. I don't think we should change this logic about when the sidebars do and don't show at this stage.

**Comment by seanh** [comment]
> Searches for user:username or group:pubid will route the user to the vanity URLs. Searches for any other query will route the user to /search?q=...

I think this is referring to searches entered on the `/search` page and whether or not they should redirect to the `/users/<username>` or `/groups/<pubid>` pages, but is _not_ supposed to imply anything about when searches on the `/users/<username>` or `/groups/<pubid>` should redirect _back_ to the `/search` page? (Currently they never do, unless you delete the first lozenge.)

To be honest, I thought this issue was just about changing URLs, so I propose that we don't change the currently implemented logic (whatever it may be!) that decides when the `/search` page redirects to the user or group search page.

**Comment by seanh** [comment]
> User and group profile pages will have vanity URLs at /users/{username} and /groups/{pubid}/{slug} which show the /search route with the queries user:username and group:pubid respectively.

Alright. So my proposal is that _all_ I'm going to do for this ticket is:

1. Change `/groups/<pubid>/search` to `/groups/<pubid>/<optional slug>` (ie the same URLs that the classic groups page used to use)

2. Change `/users/<username>/search` to `/users/<username>`

3. Get rid of the unnecessary `?q=` that sometimes appears at the end of the `/search` URL

**Comment by dwhly** [comment]
@seanh: This seems eminently reasonable. We can extend later.

**Comment by robertknight** [comment]
> Alright. So my proposal is that all I'm going to do for this ticket is:

👍 from me.
