### ISSUE TITLE
Group name form field shouldn't be auto-focused on page load

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4009]
I'm not sure if this is happening on any other forms as well, but on the edit group form the name field gets auto focused on page load, which disables the rest of the page:

![peek 2016-10-27 19-19](https://cloud.githubusercontent.com/assets/22498/19779772/7a84c38e-9c7a-11e6-9daa-7deaf590ecfe.gif)

**Comment by sean-roberts** [comment]
I am willing to bet that this is because it's the same form for the create new group, which auto focuses to start the flow

**Comment by sean-roberts** [comment]
set in groups/schemas.py that it has autofocus. Knowing nothing about python, I am going to back out of this one. But I'd like to think it would be simple to switch that autofocus if we are editing

**Comment by robertknight** [comment]
Just testing on iOS at the moment and in combination with inline editing this made it impossible to edit the group description on iOS because as soon as the 'Edit Group' form loaded the name field was autofocused and tapping the 'Cancel' button resulted in the name field immediately being re-focused again.

I think this is happening because canceling inline editing reverts the HTML for a form to an earlier version and then re-applies component upgrades which in turn re-focuses the name field.
