### ISSUE TITLE
Document URLs in document buckets aren't linked

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4058]
![screenshot from 2016-11-11 20-07-22](https://cloud.githubusercontent.com/assets/22498/20228721/8b04103a-a84a-11e6-81cb-308fc9a92a48.png)

The URL under _Address_ on the right here isn't linked. Possibilities: link to the document in Via? Or just link to the URL as shown, without h?

**Comment by robertknight** [comment]
> Possibilities: link to the document in Via? Or just link to the URL as shown, without h?

Ideally we would re-use the direct link infrastructure. Perhaps:

Step 1: Direct link to first annotation shown in the bucket
Step 2 (Optional): Teach bouncer and client about an additional option which causes client not to select the direct-linked annotation

I think a convenient way of getting to the original URL without any rewriting would be useful, this could be done perhaps via an additional icon next to the link?

**Comment by dwhly** [comment]
> I think a convenient way of getting to the original URL without any rewriting would be useful, this could be done perhaps via an additional icon next to the link?

@conordelahunty and I discussed exactly this.  Keep the original link intact, and clickable as it is stated.  But include another button that links to via perhaps now, and bouncer hopefully in the near future, and (soon) preserves the context in place (for instance, if the user is viewing a group).

**Comment by dwhly** [comment]
>Step 1: Direct link to first annotation shown in the bucket
> Step 2 (Optional): Teach bouncer and client about an additional option which causes client not to select the direct-linked annotation

So your notion would be to scroll the page to the first annotation in the list?  That's actually pretty awesome.  Particularly if the facets in place constrain to a subset of all the annotations on that page.

**Comment by seanh** [comment]
I think the decision on this one was that the URL should be a bouncer link to the first annotation in the document bucket.

**Comment by dwhly** [comment]
1- Preserve the existing URL and make it clickable.
and
2- Link the "see annotations in context" button to a bouncer link to the first annotation-- since that will double as a mechanism to switch the group scope properly too.

We'll tackle stripping the select functionality off bouncer links as a possible later phase so that the top annotation isn't the only one showing after the user is taken to the page.

@conordelahunty Can you suggest something more prominent as a "Go there" button, which is above the naked link, and perhaps reuses the "up and to the right" icon?  I think we want to make sure that the first thing that a student clicks on as a juicy target is a thing which will take users there, activate H and switch the group appropriately-- which is one of our chief usability issues.

Also, what do we think about also placing the "up and to the right icon" on the document panel, perhaps at the extreme right, when it is in the collapsed state.  In other words, right now in the group landing page, you can click on the document and go there, thanks to via.  One click.  What we're introducing is an interface in which "going there" will require two clicks-- one to open the document bucket, and another to go there.  We could create a clickable region at the extreme right of the document bucket, with an icon there, that would let folks easily go to the page without first opening the document bucket.

**Comment by robertknight** [comment]
See mocks here: https://projects.invisionapp.com/share/B88RCLRFN#/screens

**Comment by conordelahunty** [comment]
Hey, here is a design for how I think we can make the difference a little clearer. There is a naked url and an explicit bouncer link:

![bouncer 1](https://cloud.githubusercontent.com/assets/8598901/20438004/4df1e96c-adb6-11e6-9c1e-1ee7a060f952.png)

I think there is a third scenario we might want to think about too. Might we want to make the naked url a facet? I mean, clicking on it adds that url as a facet in the search box and clicking on the bouncer link sends you to the document with the annotations showing. If the user wanted to go to the original document then they could copy and paste the naked url?

Also, there was some discussion having a bouncer link available to the user when the document module is in a collapsed state. The original thinking was that the user would be able to click on the preview url in the left hand side and that would bring them to the document with the annotations showing. This 1)got lost in translation and 2) is perhaps a little subtle so how about we show the bouncer arrow icon beside the preview url on hover?

![bouncer 2](https://cloud.githubusercontent.com/assets/8598901/20438022/59a2420c-adb6-11e6-9fcb-d10e8e23a141.png)

**Comment by dwhly** [comment]
> Hey, here is a design for how I think we can make the difference a little clearer.

Super...  Can we place it at the top though?  Rationale: Students are going to click on the first thing they see that looks like "A way to get there".  We know that if (for instance) students **don't** click on the via/bouncer link then they won't be scoped to the group, or have H deployed at all-- and it's creating a problem.  Putting the naked link at the top is likely to draw a fair number of clicks vs what they probably need to be doing instead, which is clicking 'visit in context'-- since the link looks "clickable", but the text to see annotations in context doesn't.

(A second suggestion might be to also make the string explicitly a button, so it looks more clicky.  Since we're not using link colors in our interface, it's not always obvious that things in the interface are links.)

> Might we want to make the naked url a facet? I mean, clicking on it adds that url as a facet in the search box and clicking on the bouncer link sends you to the document with the annotations showing.

The effect of this would be simply be to get rid of the other documents showing on the page, and to collapse the one you're looking at.  Is that a useful option?

Folks do of course need to use the link any time the document is behind a paywall and they're not using the extension.

> how about we show the bouncer arrow icon beside the preview url on hover?

Fabulous.

**Comment by conordelahunty** [comment]
@dwhly Rearranged and made a little clearer. Separating the bouncer link and url hopefully will make it less confusing too.

![update](https://cloud.githubusercontent.com/assets/8598901/20486407/e705b336-afff-11e6-93a3-0985b23d02b8.png)

**Comment by seanh** [comment]
I don't think we should do this one:

![59a2420c-adb6-11e6-9fcb-d10e8e23a141](https://cloud.githubusercontent.com/assets/22498/20487706/69f34dac-affc-11e6-979b-600ea6c20713.png)

That whole header area of a document bucket, including the domain name on the left, the document title in the middle, and the annotations count to the right, is the clickable area that you click on to expand / collapse the document. If the domain name becomes a link then on desktop you still have loads of clickable area for the expand / collapse and (in Rob's implementation of this in <https://github.com/hypothesis/h/pull/4090>), the arrow only appears when you hover over the domain name which acts as an affordance that you're about to click on a link not expand or collapse the bucket (there's also a tooltip and a cursor change):

![peek 2016-11-21 15-11](https://cloud.githubusercontent.com/assets/22498/20487850/e33de24e-affc-11e6-9973-2868272788be.gif)

On mobile, however, you have none of those three affordances _and_ the clickable area is much smaller / the domain name takes up a much larger proportion of the clickable area. It becomes very easy to accidentally follow this link instead of expanding / collapsing:

![screenshot from 2016-11-21 15-13-25](https://cloud.githubusercontent.com/assets/22498/20487938/337fadd2-affd-11e6-948c-5dd95be551e3.png)

Also the showing of the arrow icon on hover misbehaves on mobile.

I would say: make the domain name clickable on desktop only, or just don't do it at all.

**Comment by dwhly** [comment]
@conordelahunty 

> Rearranged and made a little clearer. Separating the bouncer link and url hopefully will make it less confusing too.

Awesome.  The underline helps a lot, thank you!

@seanh:

I don't think we should give up altogether :)   Can the arrow icon be non-hover on mobile?  Or disabling on mobile perhaps as a last resort.

Can I ask, what is the definition of a mobile browser from our code's perspective?  widths < x?

**Comment by robertknight** [comment]
Re-opening this. I have implemented the second design from @conordelahunty but not the most recent one (https://github.com/hypothesis/h/issues/4058#issuecomment-261578927 ).

**Comment by robertknight** [comment]
@conordelahunty - Can you provide the icons for the 'Tags' and 'URL' sections?

**Comment by conordelahunty** [comment]
@robertknight 
[icon-svgs.zip](https://github.com/hypothesis/h/files/616454/icon-svgs.zip)
