### ISSUE TITLE
Tags in document buckets aren't linked

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4060]
![screenshot from 2016-11-11 20-07-22](https://cloud.githubusercontent.com/assets/22498/20228823/0e8010f8-a84b-11e6-94fe-68ce0c1479f1.png)

 The tags under _Tags_ on the right here. Options: link to a `/search` page search for just that tag?

**Comment by seanh** [comment]
This is blocked waiting on a decision (from @ajpeddakotla I think?) about whether clicking on one of these tags should add that tag into the current search query, or replace the current search query with a query for just that tag.

**Comment by robertknight** [comment]
> This is blocked waiting on a decision (from @ajpeddakotla I think?)

The behavior @sheetaluk has implemented for users and groups in annotation cards is that they replace to rather than append to the query. This seemed reasonable and unsurprising to me. I suggest we give this a go and see if it feels intuitive in practice.

One way we could rationalize the behavior is that the sidebar links show subsets of the current results whereas the annotation card links show all annotations that have some attribute in common with the selected annotation (eg. same user, group, tag etc.).
