### ISSUE TITLE
Direct the user to their profile page after login

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/h#4070]
When a user logs into Hypothesis from `https://hypothes.is/login`, they are currently directed to `https://hypothes.is/stream` after login. 

We should instead direct them to their user profile page after they login.

**Comment by robertknight** [comment]
This was actually implemented by https://github.com/hypothesis/h/pull/4050 but it looks like it only works if the `search_page` feature flag is enabled for all (including logged-out users), not when the feature is enabled only for certain users.

The problem is that the post-login route is initialized in `AuthController` at the start of the request _before_ the login completes, so the route is determined based on the feature flags for logged-out users rather than based on the user's identity of the user after login.
