### ISSUE TITLE
Annotation count is shown twice on user and group search pages

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4168]
![screenshot from 2016-12-05 14-20-21](https://cloud.githubusercontent.com/assets/22498/20889227/19524cfa-bafa-11e6-9730-428332229e6a.png)

Note that this is the same number twice, it's not (currently) two different numbers, see https://github.com/hypothesis/h/issues/4066

**Comment by dwhly** [comment]
From a discussion in slack, change the count of search results to read "nn Matching Annotations".  Change the count within the user or group sidepanel to always show the total annotations that the user or group has made.

**Comment by seanh** [comment]
I don't think the count of _all_ the user's or group's annotations is available to the templates yet (the count shown in the sidebar is just the matching ones), so the Python code'll need to add those counts to the template data, it'll have to get them from the DB.

**Comment by chdorner** [comment]
Just a quick note: If we need to do additional queries we need to profile to see how long they take and how much time they add to the overall request processing.

**Comment by seanh** [comment]
@chdorner Would a feature flag for this change work? Then we can turn it on and off and test in production

**Comment by chdorner** [comment]
I would test it out locally first, also running `EXPLAIN ANALYZE ...` and making sure we have all the necessary indices set. If it doesn't add any significant time we should just get it out without a feature flag.
If it does make the request too slow we have to decide how important that count is to us and comparing it to how much work it is to build a caching layer into this.

**Comment by ajpeddakotla** [comment]
2 points

**Comment by ajpeddakotla** [comment]
I'm reopening this because there are some edge cases and some general confusion from a user perspective that we should clear up. @sheetaluk and I had a convo about this and here's what we came up with (also included this in the PR): 

______
So after talking @sheetaluk, there needs to be a finer grained approach to counts of annotations that we are showing in both the sidebar and the search results. 

So if we breakdown the different types of annotations that can be viewed, and who they can be viewed by, it looks something like this (for now - this will change with publisher groups). 

Empty |Private | Shared | Public
------ | ------ | ------ | ------
Me | Y | Y | Y
Person I am in one or more groups with | N | Y (but only in groups that I am a part of) | Y
Stranger | N | N | Y

Right now, what's been implemented - we're only showing public annotations which are not private or shared. 

What we'd like to do, because showing the finer detail helps better inform the user of the types of annotations they are making is to: 

**1. In the sidebar:** 
Breakdown the count to include (for users viewing their own profile):
Shared annotations: 
Private annotations: 
Public annotations: 

For users viewing someone else's profile: 
Public annotations: 
Shared annotations (if they share a common group with that user)

**2. In the search results:** 
If I'm viewing my own profile. 
Shared
Private
Public annotations (if I'm viewing my own profile)

If I'm viewing someone else's annotations
Shared (if they share a common group with me)
Public

**Comment by ajpeddakotla** [comment]
Closing as this has been merged.
