### ISSUE TITLE
Group invite component clipboard icon shows then hides onscreen keyboard

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4188]
Go to a group's search page on mobile, go to the _More info_ page, scroll to the bottom, click on the clipboard icon.

What happens: the onscreen keyboard momentarily appears and then disappears again.

What should happen: keyboard should not appear.

**Comment by ajpeddakotla** [comment]
We're time boxing this to 1/2 day - if we can't fix it in this time, we'll move on.

**Comment by sean-roberts** [comment]
So, for mobile safari, copying is not possible at all. (for a more involved answer see this thread http://stackoverflow.com/a/34046084) 

Therefore, the best we can do is try to select the text and not show an error message saying "copy failed". We can not prevent the keyboard from coming up because it's needed inorder to make a selection possible on mobile safari (we have to focus the input - triggers keyboard). And finally turn off the auto hide if it's mobile safari. The end result will be that on mobile safari, we focus the element and select the contents

**Comment by robertknight** [comment]
> So, for mobile safari, copying is not possible at all. (for a more involved answer see this thread http://stackoverflow.com/a/34046084)

The StackOverflow answer is out of date. Safari 10 added support for programmatic copy-to-clipboard. See https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html

However, it does have a bunch of limitations and quirks. See Git commit messages that modify `copy-button-controller.js` and comments in that file. In particular it was necessary to actually select the text in the input field (and thereby trigger the on-screen keyboard) because changing the copied text in the "copy" event was not supported.

**Comment by sean-roberts** [comment]
> The StackOverflow answer is out of date.
Well, just not referencing the latest release - but still true for the browsers that we support.

But since it's not the latest, I think the solution as it is now is fine for not the latest version.

But you're right, unfortunately triggering focus to select is the primary problem here. 

I will, however, see if ClipboardEvent.clipboardData.setData can be used for android/chrome support

**Comment by sean-roberts** [comment]
I don't see a path forward here that can work around the requirement to focus an input first
