### ISSUE TITLE
Settings UI/UX feature requests: Ability to globally auto-set post publicly/post to self

### ISSUE THREAD

**Issue by chrisaldrich** [hypothesis/h#4229]
Perhaps it exists already and I'm not seeing it, but most of what I highlight and annotate, I typically prefer if it were automatically published freely and in the open. Currently it appears that highlights default to "only me" after they're highlighted. Annotations appear to default to public initially as they're being written, but when re-entering the text without manually hitting publish, they then are posted automatically to "only me". 

This may be a reasonable default, but it means spending more time with the interface while I'm reading/working and thereby taking me out of the flow of my work. 

Unfortunately, there is no default setting for forcing my highlights and annotations to be public, which means when I'm done reading that I have to go into the UI and manually do three button presses to make this happen for EVERY post. Click to edit, click the setting arrow, and finally click to publish.  UGH!

In addition to allowing a master setting toggle for public/private at the main account level which would alleviate a large portion of my issue, I'd also recommend that rather than a drop down menu with two options that there just be a simple toggle to switch between public/private on each post so the user can accomplish in one click (or fingerpress on touchscreens) what currently takes two.  Admittedly it's also controlling a "publish" function simultaneously, but I think that each post could have a public/private toggle and a separate "publish" button without cluttering up the UI too much.

**Comment by sean-roberts** [comment]
Hey @chrisaldrich, thanks for the support and reporting your problem! You're not missing any such setting for this control. As it is, you're right, highlights are not public and making them publicly requires there to be actual annotation content and opting that you want to swap into that scope. The thought process there is because it's labeled as "Only Me" changing that to "Public" for users automatically (after text is entered) becomes a hard experience to get right. Like what if they enter text and then delete it all, does it go back?

We have been looking into some sort of sidebar settings/preferences and I will bring this up to the team. Though, I have no estimation when we will get to that.

Thanks again for your feedback!

**Comment by nickstenning** [comment]
Hi @chrisaldrich! Thanks again for reporting your problem here.

I've recorded your input on two separate issues (currently viewable by our team only). One is about improving the experience around highlights and the fact that they are currently always private by default (https://github.com/hypothesis/product-backlog/issues/190), and one is specifically about the request for a global default for public/private (https://github.com/hypothesis/product-backlog/issues/191).

Since we'd like to keep this repository for bugs, I'll now close this issue. Hope that's ok!
