### ISSUE TITLE
Tags in activity pages sidebar look wrong in Firefox (CSS issue)

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4296]
Chrome:

![screenshot from 2017-01-12 11-44-26](https://cloud.githubusercontent.com/assets/22498/21888551/aa75a88c-d8bc-11e6-9dab-674fa7b3b97a.png)

Firefox:

![screenshot from 2017-01-12 11-45-17](https://cloud.githubusercontent.com/assets/22498/21888554/ae5ab1f4-d8bc-11e6-92b6-a747be530094.png)

The usernames are also the wrong colour in Firefox, probably the same issue:

![screenshot from 2017-01-12 11-45-30](https://cloud.githubusercontent.com/assets/22498/21888563/bc04fcc4-d8bc-11e6-9689-4ffd2bce5cbc.png)

Group invite control is wrong colour too.

**Comment by robertknight** [comment]
As far as the colors are concerned, it is Chrome that is wrong here, not Firefox. The text color should be either `$grey-6` or `$grey-7`, not pure black.

I don't see the text wrapping issue with the number appearing on the wrong line in FF Nightly, so it may be specific to a range of FF versions.

**Comment by nickstenning** [comment]
I think the issue here is that `<button>`s can't be flex containers:

See:

- http://stackoverflow.com/questions/33344121/text-and-image-in-button-wont-stay-on-same-line-using-flexbox-in-firefox
- https://bugzilla.mozilla.org/show_bug.cgi?id=984869

The Bugzilla bug implies that this is "fixed" in FF 52 (the next version) but fixing this is pretty straightforward regardless (wrap the button contents) so maybe we should just do that...

**Comment by nickstenning** [comment]
Added a PR to fix the layout issue. I suspect that the colouring issues are also related to the fact that we're using `<button>` tags to implement these things. I'm not really sure I understand why they're not plain ol' links...
