### ISSUE TITLE
"Session is invalid" when trying to login to embedded client in Safari

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/h#4346]
### Steps to reproduce

1. Open a web page on which h is embedded (via WP or Canvas) in Safari. For example:

annotatingausten.sfsuenglishdh.net/chapters-1-5/

2. Try to login/view existing annotations.

### Tell us what should happen.

Login should be successful. AND public annotations should appear even when you don't login.

### Actual behaviour

Login fails: "Session is invalid. Please try again." AND public annotations are not visible.

### Browser/system information

Safari.

### Additional details

Once login is made through main hypothes.is page, public annotations are visible on pages in question.

And further attempts to logout/login do work on site after this initial workaround.

**Comment by sean-roberts** [comment]
FWIW, this is a none, long standing issue with the way we are doing authentication. It's because safari is treating us like we are an advertisement and can't set cookies for the logged in session.

To get around this, all the user's have to do is access the main hypothes.is website. They don't have to do anything but go directly there, then go back to their app. We have to establish a 1st party connection with the user before the browser allows us to use cookies.

**Comment by seanh** [comment]
I edited the title to hopefully clarify when this issue occurs. When a third-party website has the Hypothesis client embedded it's especially likely that users visiting that site in Safari and trying to use the client will not have had a first-party interaction with hypothes.is and so will get the "Session is invalid" error message.

I guess users would need to have a Hypothesis account in order to be trying to login to the Hypothesis client, but since creating that account they may have cleared their browser history (which I believe would bring the "Session is invalid" error back until they visit our site again?), or maybe they created the account in a different browser, or on a different computer.

I _don't_ think this will happen when the embedded client is using the new third-party accounts support, by the way, as that doesn't use cookies.

**Comment by sean-roberts** [comment]
Yes, we have to establish a 1st party interaction with the end user. The _only_ need to visit our website in a first part context and keep that context. Because, like you said, if the user ultimately cleared all of the site data, they are back to square one. You are correct though, we are going to move away from this with the new auth work we are working on.

I am going to add some analytics to our app to give us the hit/miss ratio for login successful/fail. The ultimate goal, of course, would be to get workable data on the surface area of this problem and to validate if our efforts fix it. For example, perhaps there is a stop gap solution that, while probably not the best UX, is still a whooole lot better than the current experience.

**Comment by robertknight** [comment]
Hypothesis (as of v1.39) now detects when the browser is preventing it from storing cookies and falls back to using OAuth rather than cookies for authentication in this context. You may find that you need to click the "Log in" button each time the client loads, but as long as you are signed in to the website you won't have to re-enter your login details each time.
