### ISSUE TITLE
~.000008sec difference between 'created' and 'updated' field in API

### ISSUE THREAD

**Issue by perezfr** [hypothesis/h#4411]
### Steps to reproduce
1. Query the api 'search' function with uri as 'https://www.commonsense.org/education/privacy/blog/digital-redlining-access-privacy'
2. 
3.

### Expected behaviour
'created' and 'updated' field should not be different for annotations that aren't updated.

### Actual behaviour
There are messages with ~.000008sec difference between 'created' and 'updated' field

### Browser/system information
Using the API search feature https://hypothes.is/api/search

### Additional details
attached csv of list of messages affected by the issue
[augCreateUpdate.txt](https://github.com/hypothesis/h/files/825619/augCreateUpdate.txt)

**Comment by seanh** [comment]
Thanks @perezfr , I can confirm that I can reproduce this bug.

@chdorner  @fatbusinessman  Should we fix this issue?

When you create an annotation, I guess the model code calls `utcnow()` once for `created` and then again for `updated`, rather than calling it once and assigning the same one value to both: <https://github.com/hypothesis/h/blob/master/src/memex/models/annotation.py>

The result is that, for an annotation that has never been edited, `created` and `updated` are not exactly the same. This _is_ wrong and I can in fact see it being a pain (for example if you want to produce a list of all annotations that have been edited, by finding those with different created and updated dates).

The obvious fix to me would be for `Annotation` to have an `__init__()` method that calls `utcnow()` once and sets it as the value of both `created` and `updated`, although I anticipate objections because I understand that people don't like adding code, especially not `__init__()` methods, to model classes. This particular `__init__()` method would not change the API of creating `Annotation` objects though.

Perhaps there is some declarative way to tell sqlalchemy to set `updated` to the same value that was generated for `created`? But I don't know if off the top of my head.

Or we find the user code outside of the model class and have _it_ run `utcnow()` once and pass in the one value for both `created` and `updated`. This seems wrong to me (I would go with the `__init__()` method) but it would work as long as we don't grow more lines of code that create `Annotation`s in the future and forget to do this correctly there as well.

Or we decide not to fix this.

* * *

As for _existing_ annotations in the db that have never been edited but that have different created and updated times, if we wanted to fix those retrospectively all I can think of is a database migration that looks for annotations whose created and updated are within some tiny fraction of a second delta of each other and changes them to be the same.

**Comment by chdorner** [comment]
Looking at the code this actually looks like a bug, the code does try to set it to the same timestamp: [here](https://github.com/hypothesis/h/blob/master/h/storage.py#L103) and [here](https://github.com/hypothesis/h/blob/master/h/storage.py#L134-L135).
In general, the fix should happen outside the model though, because `h.storage.create_annotation` is the only code path that is responsible for creating an annotation, so it should happen in there.

We should look into fixing this for new annotations, I'm not sure how if it's worth the effort for old annotations. It might be fairly straightforward if we are okay with making the decision that if the updated is not more than one second ahead of created than we set the updated timestamp to the same as created.

**Comment by perezfr** [comment]
The issue only seems to affect annotation data from before August/September 2016. Newer records don't seem to be affected by this issue.

**Comment by seanh** [comment]
I think this was fixed a long time ago
