### ISSUE TITLE
POST request to /users returns only first error message.

### ISSUE THREAD

**Issue by nlisgo** [hypothesis/h#4551]
### Steps to reproduce
1. Create a user via the API
2. Try to create the same user again

### Expected behaviour
The expectation is that the username and email both have to be unique in the system for each authority. It would improve the experience if all detected errors were reported.
```
{
  "status": "failure",
  "reason": ["user with email address test@test.com already exists", "user with username test already exists"]
}
```

### Actual behaviour
```
{
  "status": "failure",
  "reason": "user with email address test@test.com already exists"
}
```

**Comment by nickstenning** [comment]
Either this is possible straightforwardly with `jsonschema` library or it's not.

Pointed at 2 points on the basis that it is straightforward, otherwise we'll punt this and have a longer conversation with @nlisgo about other ways of addressing this problem.

**Comment by chdorner** [comment]
This is possible in `jsonschema`, we use its [`best_match`](https://python-jsonschema.readthedocs.io/en/latest/errors/#best-match-and-relevance) utility function to determine which one is the most important error message to show ([see the code](https://github.com/hypothesis/h/blob/master/h/schemas/base.py#L69)).

When I send off a request to `POST /api/users` with the body `{}` and get all error messages from `validator.iter_errors(appstruct)` I get all three: `'authority' is a required property`, `'username` is a required property`, and `'email' is a required property`.

I seem to remember that `iter_errors` will return two error messages for the same field if it's missing (for example, one is the error that it's missing, and then another error message that the type is incorrect). But I'm not 100% certain, we should look into the implications of this across all API schemas to see which impact this change has. In addition to that, it might also change the JSON structure of the error response, if we decide that `reason` can be an array of strings instead of just a string.

**Comment by nickstenning** [comment]
Great, that's good to know.

> it might also change the JSON structure of the error response, if we decide that reason can be an array of strings instead of just a string.

Given that `reason` is for humans, not machines, I think it would be just fine to `'; '.join(reasons)` instead of changing the type of the field.

**Comment by chdorner** [comment]
@nlisgo This is now deployed all the way out to production.
