### ISSUE TITLE
Cann't use local hypothesis storage following /docs/developing/install.rst instructions?

### ISSUE THREAD

**Issue by everest5216cbaok** [hypothesis/h#4663]
I followd the instruction of /docs/developing/install.rst and can access localhost:5000 successfully.
But when I enter a website address to "Paste a link..."(in home page), It links to "https://via.hypothes.is//www.xxx.com". 
Then I noticed client, following the https://h.readthedocs.io/projects/client/en/latest/developers/developing/#setting-up-a-client-development-environment and can access localhost:3000 successfully.
But when I enter a website address, It also links to "https://via.hypothes.is/www.xxx.com".
Can someone help giving me some detailed on how to use local hypothesis storage?

**Comment by robertknight** [comment]
The "Paste a link" input is part of the legacy website which was removed from the "h" service yesterday. It had a hardcoded link to our production proxy service at https://via.hypothes.is.

There are different parts to the Hypothesis software, and the proxy service ("Via") is separate from "h". If you want to run your own version of Via you need to set that up separately (https://github.com/hypothesis/via).

If you just want to use a local instance of Hypothesis for personal usage, you will probably find it easiest to build a custom Chrome extension (from the browser-extension repository) which communicates with your local "h" service, rather than setting up Via.

**Comment by everest5216cbaok** [comment]
Thank you for your quick reply, I have built the browser-extension successfully. It can be activated. When I select some element, it pops up menu correctly, But sidebar cannot be displayed.
I understand the instructions in 
https://h.readthedocs.io/projects/client/en/latest/developers/developing/#running-the-client-from-h
But I don't know who supply http://localhost:3000 service? I run the h service, but cannot access this address.

**Comment by robertknight** [comment]
> But I don't know who supply http://localhost:3000 service, h or client?

That is part of the client's development server which is run by `gulp watch` in the client repository. It is intended purely as a tool for developing the client.

**Comment by everest5216cbaok** [comment]
Thank you!You're so kind!
Sidebar can display, and I can make annotation using local hypothesis service.
I have another question, I hope not waste you too much time!
I have set host to 0.0.0.0 in development-app.ini in order that It can be accessed by chrome in another computer. But when I add plugin to chrome( in another computer), It cannot show correctly. Does The plugin can not find the server address? There are too many localhost address in client and browser-extension code and I have tried but useless. Is there a place to set the server's address so the browser-extension can be used in another computer?

**Comment by robertknight** [comment]
> But when I add plugin to chrome( in another computer), It cannot show correctly.

The URL of the h service is hard-coded into the browser extension when it is built, using the settings from `settings/chrome-dev.json`, or whichever settings file you are using. In order to build an extension which talks to a development h server on a different machine, you'll have to change those URLs or create a custom settings file and then do `make SETTINGS_FILE=settings/your-custom-settings.json`.

**Comment by everest5216cbaok** [comment]
@robertknight Thank again ^_^!
Almost finished, my colleague must love it! But I find plugin cannot display correctly when accessing https site.
Should my service changed to https? Or What I can do to fix it?

**Comment by robertknight** [comment]
> Should my service changed to https? Or What I can do to fix it?

If you want to run your own instance of the service and be able to annotate pages served over HTTPS, you'll need to enable SSL for the service. There is information on how to do that for local development here: https://h.readthedocs.io/en/latest/developing/ssl/ . If you want to let other people use an extension that talks to your service instance, you'll need to make sure the certificate is correctly signed for whatever domain the service is exposed at, otherwise the browser will reject the connection between the extension and the service.

**Comment by everest5216cbaok** [comment]
@robertknight Great! It can work although speed is not fast!
Thank you so much!
