### ISSUE TITLE
Don't send broken bouncer links in email notifications for third-party accounts

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4715]
[Bouncer links don't work for third-party accounts](https://github.com/hypothesis/client/issues/613) so we shouldn't send bouncer links in email notifications (reply notifications, moderation notifications) for third-party annotations.

**Comment by robertknight** [comment]
Possible solutions discussed on Slack:

1. Fix Bouncer links to work with third-party accounts
2. Replace uses of incontext/HTML links in these notifications with links to the original document

My personal preference would be to look into resolving this in Bouncer and only if that really is difficult go for option (2).

**Comment by fatbusinessman** [comment]
One possible approach that cropped up in a call today is to let Bouncer know that certain authorities should be redirected directly, rather than proxied through Via, because we know any annotations under those authorities involve an embedded client. We could code this into 

Since Bouncer retrieves annotation information from Elasticsearch, which now [includes an `authority` field](https://github.com/hypothesis/h/pull/4708), we can use this value directly rather than having to infer it from the author.

One advantage of explicitly marking certain authorities as redirect-only, rather than applying this to all third-party accounts, is that we don’t have to think too hard now about how this will affect Canvas accounts.

**Comment by robertknight** [comment]
Bouncer links are now working for third party annotations following https://github.com/hypothesis/bouncer/pull/61
