### ISSUE TITLE
Version / date + FOSS licenses

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#513]
It would be great if there was an option under the main options menu or somewhere to get the current version of the app / server combo quickly.  Maybe including the date that it was last updated?

ALSO:  Include info about FOSS licenses here.

**Comment by tilgovi** [comment]
Version may or may not happen, depending on how our experience turns out over the next few releases of the Chrome extension. For other environments, the version is always the newest, which is one of the beautiful thing about web apps.

For the license stuff, which was just a footnote here, I have since added a proper issue in #1400.
