### ISSUE TITLE
api search fails when offset + limit > 10000

### ISSUE THREAD

**Issue by tgbugs** [hypothesis/h#5191]
### Steps to reproduce
1. pick a `HYP_GROUP` with lots of annotations.
2. OK `curl --header "Authorization: Bearer ${HYP_API_TOKEN}" "https://hypothes.is/api/search?offset=9999&order=asc&sort=updated&group=${HYP_GROUP}&limit=1"`  
OK `curl --header "Authorization: Bearer ${HYP_API_TOKEN}" "https://hypothes.is/api/search?offset=9800&order=asc&sort=updated&group=${HYP_GROUP}&limit=200"`
3. FAIL `curl --header "Authorization: Bearer ${HYP_API_TOKEN}" "https://hypothes.is/api/search?offset=10000&order=asc&sort=updated&group=${HYP_GROUP}&limit=1"`  
FAIL `curl --header "Authorization: Bearer ${HYP_API_TOKEN}" "https://hypothes.is/api/search?offset=9801&order=asc&sort=updated&group=${HYP_GROUP}&limit=200"`

### Expected behaviour
High offsets should return annotations.

### Actual behaviour
`{"status": "failure", "reason": "Uh-oh, something went wrong! We're very sorry, our application wasn't able to load this page. The team has been notified and we'll fix it shortly. If the problem persists or you'd like more information please email support@hypothes.is with the subject 'Internal Server Error'."}`

### Browser/system information
curl and requests both fail

### Additional details
First detected at offsets > 150k.

**Comment by robertknight** [comment]
Sentry report: https://sentry.io/hypothesis/h/issues/621979351/

```
TransportError: TransportError(500, u'search_phase_execution_exception', u'Result window is too large, from + size must be less than or equal to: [10000] but was [100001]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.')
(18 additional frame(s) were not displayed)
...
  File "elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "elasticsearch/client/__init__.py", line 655, in search
    doc_type, '_search'), params=params, body=body)
  File "elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "elasticsearch/connection/http_urllib3.py", line 180, in perform_request
    self._raise_error(response.status, raw_data)
  File "elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)

TransportError: TransportError(500, u'search_phase_execution_exception', u'Result window is too large, from + size must be less than or equal to: [10000] but was [100001]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.')
```

**Comment by robertknight** [comment]
Hmm ... the current `/api/search` API design is fundamentally inefficient in the way that it uses the search infrastructure.

What we I think we would like to do in future is provide a cursor-based API for efficiently paging through results. In other words, the response to an `/api/search` request will likely contain either a link to the next page of results or some token to be passed to `/api/search` in order to get the next page. This means that it won't be possible to directly request annotations starting at some particular offset, you'll have to get the previous pages first. Would this cause any problems as an API consumer @tgbugs ?

----

As an implementation note, in Elasticsearch we probably want to use the [search_after](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html) API.

**Comment by robertknight** [comment]
If we need to resolve this in the very short term before we can make changes to the search API, we could alter the [index.max_result_window](https://hyp.is/g9NUppGCEeiimIdb6jQJXQ/www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html) setting.

**Comment by tgbugs** [comment]
@robertknight Requesting arbitrary offsets is currently critical for how we use the API.

Having to page through 150k+ results to get to the newest annotations every time we want to sync would not be good.

The reason for this that we request in ascending order sorted by updated. This prevents there from being any gaps where we might miss annotations. In theory we could request in descending order until we hit annotations that we already have, but the issue with descending order is that if there is a failure, then there will be a gap of unknown size which will require additional logic/state to resolve/prevent or require a resync.

We maintain a local copy of all annotations in a given group and either use the websocket to maintain synchronization or we periodically resynchronize by fetching new annotations starting at an offset equal to the current number of annotations we have accounted for.

In our use case we rarely delete annotations so offset is extremely convenient. The other option would be to query for annotations updated after a certain time (or updated more recently that a certain annotation), in which case pagination would be fine, we just need a way to start from the most recent annotation we have (currently approximated by using offset) and retrieve new annotations from oldest to newest.

**Comment by robertknight** [comment]
Thanks for the input @tgbugs. So to recap, your use case is to synchronize annotations from the Hypothesis API to some other datastore? In that case I would propose that if we add support for a "start" parameter or something like that (eg. `/api/search?sort=updated&order=asc&start={date}`) you can use the timestamp of the last-created annotation in your store to fetch search results since that annotation was created. Does that sound like it could work?

I expect the `start` logic here would be `<` or `>` depending on the sort order. The timestamps in our API have microsecond-level precision, so I think the probability of multiple annotations have exactly the same timestamp is low enough that we don't have to worry about it.

**Comment by tgbugs** [comment]
@robertknight Your summary is correct, and the proposed solution using start date should work perfectly.

**Comment by tgbugs** [comment]
@robertknight is there a near term fix for this? I am running sync off the websocket at the moment, but eventually I will need to resync due to missed annotations. Thanks!

**Comment by robertknight** [comment]
Thanks for the report @tgbugs. We have now implemented a solution in the form of a [`search_after` parameter](https://h.readthedocs.io/en/latest/api-reference/#operation/search) which causes search to return annotations starting from the first one where the field you are sorting by has a greater value than the `search_after` value.

This kind of cursor-based pagination is much more efficient on the backend than numeric offsets.

Please give this a try and let us know if it meets your needs.

**Comment by tgbugs** [comment]
@robertknight Fantastic! I made the relevant [changes](https://github.com/tgbugs/hyputils/compare/tgbugs:72ecf9ec0eb478077c6b6fe9dc2b40e7583fb49c...tgbugs:b0ab43af3c4a7666b1f860653c4bd560ce44c744#diff-93879427eaadb0b0a926effd5dd63e27) to my client library and did a full test, and was able to pull down 175557 annotations in 12 minutes with no fear of missing annotations. Many thanks!
