### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode bytes... in search API

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#5312]
https://sentry.io/hypothesis/h/issues/678132892/

```
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 69-70: invalid continuation byte
(22 additional frame(s) were not displayed)
...
  File "webob/request.py", line 834, in GET
    vars = GetDict(data, env)
  File "webob/multidict.py", line 287, in __init__
    MultiDict.__init__(self, data)
  File "webob/multidict.py", line 38, in __init__
    items = list(args[0])
  File "webob/compat.py", line 125, in parse_qsl_text
    yield (x.decode(encoding), y.decode(encoding))
  File "encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)

UnicodeDecodeError: 'utf8' codec can't decode bytes in position 69-70: invalid continuation byte
```

**Comment by robertknight** [comment]
Reproduced both in production (Python 2.7) and locally (Python 3) using these requests based on metadata in the Sentry report:

```shellsession
$ curl 'https://hypothes.is/api/search?limit=1&url=http://www.academia.edu/19861496/Ek-hong_Ljavakaw_Sia_CV_%E8%AC%9D%E6%98%93%E5%AE%8F%E7%B0%A1%E6%AD%B'
<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>
    
  </body>
</html>

$ curl 'http://localhost:5000/api/search?limit=1&url=http://www.academia.edu/19861496/Ek-hong_Ljavakaw_Sia_CV_%E8%AC%9D%E6%98%93%E5%AE%8F%E7%B0%A1%E6%AD%B'
<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>
    
  </body>
</html>

$ 
```

**Comment by lyzadanger** [comment]
This error triggered again on Monday (Jan 7, 18). I didn't realize that we'd already tracked it! I dug in a bit and found that the problem is at the `webob` level: `webob` tries to parse the `url` GET param and chokes. This choking happens at the first reference of `request.params` in the search API view (in `h.views.api.annotations`). That first reference makes `webob` initialize the `params` multidict and that fails.

Some thoughts, some of which were chatted about during a dev sync:

* This occurs lower in our stack than our app code, so band-aiding it with a naive `try/except` in the view seems lame, at least at first blush
* This occurs _rarely_ (only seen twice, ever)
* Both occasions had problematic URL strings that shared the same domain, `www.academia.edu`. I haven't dug into IPs or anything but this immediately suggests it's the same user/client
* This may magically go away when we upgrade to py3 or upgrade `pyramid` and by extension its dependencies (e.g. `webob`)

[Here is a relatively stale `webob` GH issue](https://github.com/Pylons/webob/issues/161) discussing this issue.

Recommendations:

* Do nothing at present, as this error is rare, likely isolated to a single user, and likely tough to fix at our code level; observe. Abandon this plan if this event happens more often.
* Accelerate [upgrade to Py3](https://github.com/hypothesis/h/issues/5384)

**Comment by seanh** [comment]
I'm gonna close this since it's rare and we decided to hope Python 3 fixes it
