### ISSUE TITLE
Search broadens instead of narrowing

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/h#5338]
When searching for keyword on activity pages the search broadens as more terms are added rather than narrowing. This is counter intuitive. 

![image](https://user-images.githubusercontent.com/30059933/46429357-11a64380-c6fb-11e8-9555-22e460374efe.png)

![image](https://user-images.githubusercontent.com/30059933/46429421-3dc1c480-c6fb-11e8-8542-70a10e05ce9a.png)

You can do things like this because underneath this uses a [SimpleQueryStringFilter](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html). But it is not documented anywhere and it would make sense that the default_operator would be an "OR" and not an "AND".
![image](https://user-images.githubusercontent.com/30059933/46429798-2e8f4680-c6fc-11e8-971e-50eb41cf937d.png)

An easy fix is to change the default_operator to be "AND" and update the documentation to explain the more advanced syntax.

**Comment by dwhly** [comment]
YES!  This is a long standing issue.  Difficult?

**Comment by hmstepanek** [comment]
Very simple.

Hannah

**Comment by robertknight** [comment]
> An easy fix is to change the default_operator to be "AND" and update the documentation to explain the more advanced syntax.

We should definitely do this. The reason Elasticsearch uses OR by default AIUI is that it sorts results by relevance. In that context the results containing all the keywords usually bubble to the top because they have the highest scores. Here however we are sorting annotations in reverse chronological order, so the current behaviour (OR-ing terms) is really not useful.
