### ISSUE TITLE
Crash: "ConcurrentUpdateError: concurrent document creation" when trying to create an annotation

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#5495]
https://sentry.io/hypothesis/h/issues/846053583/?referrer=github_plugin

```
ConcurrentUpdateError: concurrent document creation
(10 additional frame(s) were not displayed)
...
  File "pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "h/views/api/annotations.py", line 77, in create
    annotation = storage.create_annotation(request, appstruct, group_service)
  File "h/storage.py", line 146, in create_annotation
    updated=updated,
  File "h/models/document.py", line 484, in update_document_metadata
    updated=updated,
  File "h/models/document.py", line 130, in find_or_create_by_uris
    raise ConcurrentUpdateError("concurrent document creation")
```

**Comment by seanh** [comment]
Sentry issue: [H-1PF](https://sentry.io/organizations/hypothesis/issues/899979481/?project=37293&referrer=github_plugin)

**Comment by hmstepanek** [comment]
It appears this issue only happens when highlighting. If a concurrency error is hit in h during an annotation creation, the sidebar will show an error message however, if a concurrency error is hit in h during a highlight creation, the sidebar will not open therefore the error message is not shown and the annotation still shows up as being created in the sidebar until the user refreshes in which case the annotation disappears. What's interesting here, is the highlights are being duplicated in the database several times, even when a concurrency error does not happen. Duplicating highlights does make a concurrency error more likely to occur.

**Comment by seanh** [comment]
Note that these `ConcurrentUpdateError`s are actually being raised deliberately by the code. `ConcurrentUpdateError` is a `TransientError` subclass, and `TransientError` can be raised by the code whenever it runs into a race condition between concurrent requests in order to give up and ask `pyramid_tm` to automatically retry the whole request from the start. So the fix here is just to not report retryable errors to Sentry _unless the final retry of a request has failed. See <https://github.com/hypothesis/h/pull/5644#issuecomment-503490200> for more details

**Comment by hmstepanek** [comment]
See https://hypothes-is.slack.com/archives/C1MA4E9B9/p1560534205003800.
I have opened two issues to tackle filtering out ConcurrencyErrors using view-predicates (or some other means) once pyramid_tm has been upgraded:
- https://github.com/hypothesis/h/issues/5646
- https://github.com/hypothesis/h/issues/5645

That being said, the plan is to not filter these Sentry errors out until after we upgrade to a newer version of pyramid_tm where we can determine what retry attempt we are on and know when to raise the error to Sentry and when to not.
