### ISSUE TITLE
Investigate deform-jinja2 Python 3 compatibility

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#5516]
This is a Python 2.6 library with no tests that hasn't been upgraded to Python 3. Our own tests don't render our templates either, so wouldn't catch problems with this library. We may want to do Python 3 analysis of this library, or remove it, or just keep a careful eye on form rendering and validation as we upgrade.

**Comment by robertknight** [comment]
I was about to write a quick response here that I thought it would be better to simply remove the library since we've basically replaced all the templates it provides. I did a quick test to check that and it looks like the only template we hadn't overridden was the one for `<input type="hidden">`.

Removing the library also removes a point of confusion because it means that all the form markup comes from templates in our source tree, not a mix of templates in h and packages we include.
