### ISSUE TITLE
Run modernize

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#5522]
Run [`modernize`](https://python-modernize.readthedocs.io/en/latest/) and see if we want to do any of its suggestions.

**Comment by robertknight** [comment]
Reading the modernize docs, it seems that this is a tool designed to be run before migration in order to make code compatible with Python 2 and 3, adding a dependency on functions from `six` where necessary. Since we're no longer supporting Python 2, I think this is obsolete. Feel free to re-open if you think I might have overlooked something here.
