### ISSUE TITLE
MultipleResultsFound: exception on /accounts/developer page

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#5552]
https://sentry.io/organizations/hypothesis/issues/854147807/?project=37293&referrer=github_plugin

```
MultipleResultsFound: Multiple rows were found for one_or_none()
(10 additional frame(s) were not displayed)
...
  File "h/views/accounts.py", line 588, in get
    token = self.svc.fetch(self.userid)
  File "h/services/developer_token.py", line 35, in fetch
    return self._cached_fetch(userid)
  File "/usr/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 137, in wrapper
    result = user_function(*args, **kwds)
  File "h/services/developer_token.py", line 75, in _fetch
    .order_by(models.Token.created.desc())
  File "sqlalchemy/orm/query.py", line 2735, in one_or_none
    "Multiple rows were found for one_or_none()")
```

**Comment by lyzadanger** [comment]
I've been looking at this a bit today, and here's what I'm seeing:

* If I'm reading Sentry data correctly, this error has only ever been triggered by one user (username withheld for privacy reasons, of course).
* A reasonable hypothesis would be that [the create/update branching in `h.views.accounts`](https://github.com/hypothesis/h/blob/93872fa492e417d8c45072d442df8d1db5a406a9/h/views/accounts.py#L596) had a race-condition situation (perhaps a double-click of a submit button on a form) and multiple developer tokens got created for this user, causing an Exception when [this query](https://github.com/hypothesis/h/blob/93872fa492e417d8c45072d442df8d1db5a406a9/h/services/developer_token.py#L72) is executed because there are two matching records, not one (or None) as expected
* The error condition is any duplicate data in the `token` table such that it violates the uniqueness of `(userid, authclient=None)`. I whipped up a query against metabase/prod read replica (`SELECT userid, COUNT(*) FROM token WHERE authclient_id IS NULL GROUP BY userid HAVING COUNT(*) > 1`)—there are a total of two users in this state right now (the one who has triggered all errors so far, and one additional user). This suggests the race condition/whatever is relatively rare.

None of this suggests a course of action; just reporting on some research.
