### ISSUE TITLE
API Search: search_after seems not to work

### ISSUE THREAD

**Issue by pafonta** [hypothesis/h#5555]
### Steps to reproduce
1. https://hypothes.is/api/search?sort=updated&search_after=2019-03-01T00:00:01Z

### Expected behaviour
This should return only annotations updated today (2019-03-01) and after.

### Actual behaviour
Annotations updated **before** 2019-03-01 are returned.

### Browser/system information
Not relevant.

### Additional details
I might miss something but I would say that this query parameter is not following the [API specs](https://h.readthedocs.io/en/latest/api-reference/#operation/search).

**Comment by robertknight** [comment]
The default search order is descending, which means that you are getting back search results starting from the last annotation added before 2019-03-01 and going backwards in time. If you add `order=asc` to the query, you'll get what you expect.

A possible point of confusion here is that `search_after` means "return results _after_ the item having this value for the field being sorted", where "after" means "occurring later in the complete list of results for the query" rather than "after" in a temporal sense. The reason is that you can sort by non-temporal fields such as group ID, ID or username.

I wonder if there is something we can do to avoid this confusion in the API documentation or parameter naming?

**Comment by pafonta** [comment]
Thank you very much for your prompt and detailed answer! I understood your explanation and got it working for my use case.

I would suggest to add a mention to the `order` parameter in the doc of `search_after`. It might give a hint to understand `search_after` the way it should. Even if now that you have explained it it makes sense. I would also add in the doc that time is not the only value type for `search_after`. It will also give a hint. Well, maybe your explanation could just go to the doc :) 

Naming is never easy. Maybe `field_offset` as this more an offset than a filter and this is not a traditional pagination offset with a beginning at 0.

**Comment by roamhacker** [comment]
I ran into this issue as well. Docs are in general great, but this is not obvious due to name of search_after.  A little note about sort order in the search_after area will help future users
