### ISSUE TITLE
Add authentication to the Bulk API to only allow LMS to call it

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/h#5960]
The Bulk API has the potential to do a lot more damage than an existing single end-point. It's new and it's only used by the LMS, so lets lock it down to that only.

Once we have an end-point that just validates the request https://github.com/hypothesis/h/issues/5908 we should lock it down before we release anything that is active.

We will need to:

 * Ensure the end-point is called by users with auth client entries in the DB only
 * Ensure that the user has the LMS authority

__Note__ We will be adding service users, is there a way we could lock it down to an LMS service user instead?

----

Implementation notes:

 * This will likely need a new Context object for the bulk API
 * The functest are a good place to prove this works

See also:

 * https://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.has_permission

**Comment by seanh** [comment]
## Notes on authentication and authorization in Pyramid

* Pyramid's "security" docs are worth a read: https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/security.html. Also https://docs.pylonsproject.org/projects/pyramid/en/latest/api/security.html and https://docs.pylonsproject.org/projects/pyramid/en/latest/api/authentication.html

Here's an old diagram explaining how authentication and authorization work in Pyramid:

![2018-07-23 15 28 01](https://user-images.githubusercontent.com/22498/76998676-6bc9b180-694d-11ea-9040-1fa090b7ea3e.jpg)

* The authentication policies determine what **principals** the request has, which answers the question **who** does the request come from? For an LMS request `request.effective_principals` might look like this:

  * `"system.Everyone"`: all requests have this
  * `"system.Authenticated"`: all logged-in or authenticated requests have this
  * `"group:__authclient__"`: all AuthClient-authenticated requests have this
  * `"client_authority:lms.hypothes.is"`: only AuthClient-authenticated requests using an LMS-authority AuthClient have this

* The ACLs on the resource objects then determine, based on those principals, what **permissions** the request has. Along with the required permissions declared in the view configs, these determine whether the request is allowed to call the view or not. Permissions are usually verbs and need to be interpreted in the context of the current request's context resource. For example if the context resource is a _user_ then the permission `"update"` would represent permission to update that user (e.g. permission to call the user update API view)

* [`request.effective_principals`](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.effective_principals) is the list of principals for the current request. Can be useful in debugging, or when writing "in-view" authorization logic

* [`request.has_permission()`](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.has_permission) lets you query whether the current request has a given permission on the current context. Again, useful for debugging or for writing "in-view" authorization logic

## Notes on authentication in h

* The **authority** that the LMS app authenticates itself to h as is `"lms.hypothes.is"` in production, QA and dev

* h API docs on "client credentials", which is when you use the `/admin/oauthclients` page to create an OAuth client (with an OAuth 2 client ID and secret) and authenticate your requests as that OAuth client rather than as a user. This is how the LMS app currently authenticates its requests, we've created auth clients for it in h QA/prod and h's `make devdata` creates an auth client for it in h dev (and LMS's `make devdata` configures LMS with the corresponding auth client ID and secret): https://h.readthedocs.io/en/latest/api/authorization/#client-credentials

* Some more docs on "AuthClient" authentication in the API reference: https://h.readthedocs.io/en/latest/api-reference/v2/#section/Authentication/AuthClient

* Some API endpoints can _only_ be used with AuthClient authentication, and that's what we want for the bulk API too. Examples:

  * Add member to group: https://h.readthedocs.io/en/latest/api-reference/v2/#tag/groups/paths/~1groups~1{id}~1members~1{user}/post

  * Create user: https://h.readthedocs.io/en/latest/api-reference/v2/#tag/users/paths/~1users/post

  * Fetch user: https://h.readthedocs.io/en/latest/api-reference/v2/#tag/users/paths/~1users~1{user}/get

  * Update user: https://h.readthedocs.io/en/latest/api-reference/v2/#tag/users/paths/~1users~1{username}/patch

* In some cases an API can be used by non-AuthClient requests but it has certain _parameters_ that are for AuthClient's only. Search for "For AuthClient-authenticated requests only" in [the API reference](https://h.readthedocs.io/en/latest/api-reference/v2/)

* In the authentication machinery, the [`principals_for_auth_client()` function](https://github.com/hypothesis/h/blob/b96f728b2ad25b15c842e7aad5dd831930614dec/h/auth/util.py#L135-L153) adds a set of principals to AuthClient-authenticated requests. Three different AuthClient-related principals get added to the AuthClient-authenticated requests. The third of these looks most likely useful to us:

  1. A `role.AuthClient` (`"group:__authclient__"`) principal that simply declares "this is an AuthClient-authenticated request"

  2. A `"client:{client_id}@{authority}"` principal that is specific to the particular authclient that was used. For LMS requests this would be a `"client:<CLIENT_ID>@lms.hypothes.is"`

  3. A `"client_authority:<AUTHORITY>"` principal that just declares that an AuthClient was used and what the AuthClient's authority was. For LMS requests this would be a `"client_authority:lms.hypothes.is"` principal. This looks like what we need.

* I think you could simply have a `BulkAPI` resource that gives a `"bulk_api"` permission to AuthClient-authenticated, LMS-authority requests, something like this:

   ```python
   class BulkAPIResource:
       __acl__ = [(Allow, "client_authority:lms.hypothes.is", "bulk_api")]
  ```

  It may be as simple as that or your class may need an `__init__()` and `__getitem__()`, not sure. And of course you will have to configure the bulk API route to use this class as its factory in `routes.py` and add `permission="bulk_api"` to the bulk API view's view config.

**Comment by seanh** [comment]
I think we should ignore "service users" (which are called "machine users" on GitHub and in all of our issues about them, FYI) for the purposes of this issue and just use auth clients. Getting it to use services users instead of auth clients to authenticate the request will involve a bunch of additional work that we should avoid

**Comment by seanh** [comment]
Not described above is the actual _authentication policies_ in h that provide the effective principals for each request. They are quite complicated, and I don't think you'll need to either touch or understand them for this issue. They provide the `"client_authority:lms.hypothes.is"` principal for LMS requests, and that's all we need.

**Comment by seanh** [comment]
I think a `BulkAPIResource` with an `__acl__` as shown above, and with the corresponding route and view config to use it, will be enough to ensure that only the LMS app using its AuthClient can call the bulk API.

We may also want to ensure that the objects that the bulk API creates, and the effective user that it acts as, also belong to the LMS authority. I think that can be done in the view by finding every time an authority is mentioned anywhere in the validated request body, and asserting that `request.effective_principals` contains a corresponding `"client_authority:<FOUND_AUTHORITY>"` principal, and probably raising `HTTPUnauthorized` if it doesn't.
