### ISSUE TITLE
https://via.hypothes.is/https://baguette.netlib.re/baguette/ does not work

### ISSUE THREAD

**Issue by dogoepp** [hypothesis/h#6024]
Similarly to #4218, the url https://via.hypothes.is/https://baguette.netlib.re/baguette/ leads to an error. But this error is not an HTTP code, rather a message from Pywb failing.

### Steps to reproduce
1. Go to https://via.hypothes.is/https://baguette.netlib.re/baguette/

### Expected behaviour
Page loads with the Hypothesis side bar.

### Actual behaviour
The following messages appears instead (page blank otherwise)

```
Pywb Error
Could not load the url from the live web: https://baguette.netlib.re/baguette/
```

### Browser/system information
Firefox 75.0 (64 bits) on Kubuntu 18.04

### Additional details
Similar to #4218 but the symptom is not the same.

**Comment by jon-betts** [comment]
Slightly tardy reply, sorry! This was likely caused by transient difficulties accessing the website. 

If we cannot load the URL from the web, then we cannot display it. This page is currently accessible directly and through Via at https://via.hypothes.is/https://baguette.netlib.re/baguette/

So this is a "works for me" at the moment.

**Comment by dogoepp** [comment]
Fair enough, it works now. However, at the time the website was very reachable for me. Could it be that `via` had DNS, TLS, software or networking issues that caused it to not retrieve the page ?
