### ISSUE TITLE
Highlights cannot be seen when sharing a link via sidebar

### ISSUE THREAD

**Issue by iburunat** [hypothesis/h#6069]
Thanks for this excellent tool! I noticed three behaviours that I will post in different issues.

When I share a link from my annotation sidebar, I observe that I can't see `highlights`, only `annotations` (both being public). Any reason for this? Sometimes only highlights are necessary, without the need of having an associated annotation to it.

**Comment by klemay** [comment]
Hi @iburunat - highlights are private by default. Originally this decision was made because we wanted to avoid people cluttering the Public channel (and groups) with highlights that don't have any commentary attached. We now know there are use cases for wanting to share just a highlight - there is an existing feature request for that here: https://github.com/hypothesis/product-backlog/issues/395

I'm going to close this issue in favor of the linked issue above.

Also, I wanted to share a workaround in case you haven't already thought of it: if you add a tag to a highlight, it becomes an annotation, and can then be shared publicly.

**Comment by iburunat** [comment]
Thanks!
