### ISSUE TITLE
PASTE A LINK not showing public annotations

### ISSUE THREAD

**Issue by iburunat** [hypothesis/h#6071]
When sharing a link via `PASTE A LINK` in `web.hypothesis.is`,  I don't see the public group where my public annotations should be. Instead I see a series of third-party groups. For instance: I use `PASTE A LINK` for [this article link](https://www.biorxiv.org/content/10.1101/2020.05.22.110817v1.abstract). I paste it in a browser where I am not logged in to see how it would show to others, and I see none of my public annotations. In fact, as mentioned above, I don't see the public group, but other groups (_eLife, EMBO Press, Review Commons, Peerage of Science, Open Biology_ and _Test Journal_). Any idea on how to show my annotations/highlights using `PASTE A LINK`? Thanks!

**Comment by robertknight** [comment]
If you log in to Hypothesis you'll be able to see the Public group on that page, along with your private groups.

This is what I see logged out:

<img width="1119" alt="Screenshot 2020-06-10 09 34 45" src="https://user-images.githubusercontent.com/2458/84246038-e98cfb80-aafd-11ea-967a-eaef4e5897c6.png">

Versus logged in:

<img width="353" alt="Screenshot 2020-06-10 09 37 38" src="https://user-images.githubusercontent.com/2458/84246130-07f2f700-aafe-11ea-86ae-614ab0251c8b.png">

The reason the "Public" group doesn't show up is because we've ended up with a feature originally developed for one purpose having unwanted side effects. Certain publishers wanted the ability to have control over the annotations that are presented by default on certain pages. This is implemented by creating custom groups for specific domains and nominating them to appear instead of the "Public" group by default. Hypothesis users can log in and switch to the Public group (or any other private group). In the case of bioarxiv though it looks like this feature has been used in a different way than originally intended. I'll raise the issue internally.

**Comment by iburunat** [comment]
Thanks so much for the clarification:

> The reason the "Public" group doesn't show up is because we've ended up with a feature originally developed for one purpose having unwanted side effects. Certain publishers wanted the ability to have control over the annotations that are presented by default on certain pages

Ok, that explains it. I merely wanted to replicate what I observed in this [video](https://www.youtube.com/watch?v=mz5ajUINu9I) on how to engage in events with Hypothesis. You can see that there is no user logged in and the public annotations on the PLOS ONE article are visible. I understand that has changed now and one can only see public annotations by being logged in. In that case I assume there is no way to share public annotations made by a user to an audience that has no hypothesis account.
