### ISSUE TITLE
Identify and implement an short-term WebSocket efficiency and scalability improvements

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#6192]
Some ideas mentioned here in Slack: https://hypothes-is.slack.com/archives/C074BUPEG/p1599584777044500

**Comment by robertknight** [comment]
Previous issue - https://github.com/hypothesis/h/issues/5030

**Comment by robertknight** [comment]
We have deployed one fix which reduces the amount of work done for annotation notifications that are not delivered to a client because the event does not match the client's filters. We are still establishing the overall impact this has.

Along the way I did some profiling of the WebSocket server in production using py-spy and wrote up results here: https://hypothes-is.slack.com/archives/C1MA4E9B9/p1600106383024200?thread_ts=1600097748.019700&cid=C1MA4E9B9

Something that can be seen in the profile is that a lot of work is being done in URI normalization:

<img width="755" alt="py-spy profiling" src="https://user-images.githubusercontent.com/2458/93202779-2f83dc00-f74b-11ea-99a5-15ab191cc76f.png">

@jon-betts has [opened a PR](https://github.com/hypothesis/h/pull/6224) here which should improve the situation by only normalizing the URIs that appear in the filter configuration when the WebSocket connection is opened, rather than every time the filter is matched against an annotation.

One hypothesis I have for why URI normalization is showing up in that table is because the URIs in the client's configuration get expanded to all the "equivalent" URIs according to the document DB. With the code on master, every single URI in the expanded configuration gets re-normalized every time that filter is matched against an annotation. We don't currently have any statistics on what the mean, nth-percentile, etc. numbers of URIs are in the expanded configuration, but if there are cases where it is a lot, that would explain why filtering shows up high in the profile.

There are additional optimizations we could consider here as well, such as using a set rather than a list to store the URI collection if the number of elements is above a certain size.

**Comment by robertknight** [comment]
Significant improvements were made in https://github.com/hypothesis/h/pull/6224 and https://github.com/hypothesis/h/pull/6231. We also enabled New Relic integration with the websocket server.

Some results here: https://hypothes-is.slack.com/archives/C0C6BDS1H/p1600193002021400

**Comment by jon-betts** [comment]
One last go at this with a final PR which drops the time taken by another large chunk: https://github.com/hypothesis/h/pull/6241

This really has to be the end of it, as there aren't any likely improvements from here, and even if it was 1 billion times faster, there are only really around 2ms to play for now, which is way past the point of mattering.

I realised that a good way to look at this is throughput instead of speed. Previously our filtering took about 350ms, which means that we'd be fully saturated at a rate of 3 annotations per second. This is quite likely given recent volumes.

When we dropped this to 25ms this became 40/s. At 2ms we're at 500/s, which should be good enough for us for a long time. We're going to be hitting limits all over the place before this becomes an issue again.
