### ISSUE TITLE
Unsuccessfully finding annotations with symbols

### ISSUE THREAD

**Issue by AtomicNess123** [hypothesis/h#6719]
I have some annotations for which I have inserted the text `+++` in the annotation text (meaning "important").
However, when I go to https://hypothes.is/users/USER and search for `+++`, nothing shows up, when it should. What am I doing wrong?

**Comment by robertknight** [comment]
Hello,

You're not doing anything wrong. Hypothesis currently doesn't support searching for annotations using keywords that consist only of punctuation symbols. Like most search engines, Hypothesis search works by splitting the text into words and building an index that maps from words to annotations that contain them. Symbols like "+" are considered word separators rather than word characters and as such are not added to the index for searching. This might change in future, but for the time being you'll need to use a different convention to mark important annotations. For example, using "xxx" instead of "+++" would work.

---

Note for other Hypothesis developers: The tokenizing configuration for different fields is defined in `h/search/config.py`. You can use the `_analyzer` endpoint in Elasticsearch to see what the output of a particular analyzer (tokenizer + normalizer) looks like. For example:

```sh
curl -X POST "http://localhost:9200/hypothesis/_analyze?pretty" -H 'Content-Type: application/json' -d'{
   "analyzer": "uni_normalizer",
   "text": "a +++ b"
}'
```
