### ISSUE TITLE
Set up i18n

### ISSUE THREAD

**Issue by tilgovi** [hypothesis/h#72]

**Comment by JakeHartnell** [comment]
In #470, @tilgovi brought up the possibility of potentially using these libraries:
    http://i18next.com/
    https://github.com/archer96/ng-i18next

**Comment by lenazun** [comment]
https://github.com/airbnb/polyglot.js is pretty good

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
