### ISSUE TITLE
multi-frame notifications are leaking to the wrong frames

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#797]
Currently, many sidebar -> host notifications/events are simply broadcasted to all guests + host, instead of some finer targeting.

In most cases, this does not cause any problem, except maybe some performance penalty, but (for example) when anchoring annotations, false positive matches are possible because if this. (Anchoring an annotation intended from one frame into an other.)

(I have not actually seen this; this is only a plausible speculation, based on what I read on the code, also confirmed by @tilgovi, when we talked about this.)

This should be cleared up at some point.

**Comment by judell** [comment]
Still relevant?

**Comment by tilgovi** [comment]
Yes.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
