### ISSUE TITLE
cross-format: new URL notifications upon discovering equvivalences

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#834]
Currently, when we deploy H over a new document, we use the document plugin to ask for a list for equivalent (or synonym) URLs. We get the list, then then during the life-cycle of our session, we are getting all annotations for those URLs.

However, it may happen that during the life-cycle, a new equivalence is discovered.
After that point, if we would reload the page (and h), we would get the annotations belonging to the newly discovered documents, too.

We should enhance our solution so that these annotations are loaded right away, without the need to reload.

In practice, this would involve introducing a new kind of notification message type to our message system: a `reload-urls` message. (We can already deliver messages from the server to the client, and we already have message types, so this should not hurt.)

Upon receiving this message, the client could re-execute the URL collection phase (using the document plugin), and the reload the annotations, including from the new URLs.

Or, while we are at an early stage, it could just display the usual "we have N new annotations, you should reload" message, as we currently do for annotations arriving to the current page.

Should be a piece of cake. (Especially if implemented after #833.)

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
