### ISSUE TITLE
ClinGen issue with tags

### ISSUE THREAD

**Issue by alunaticity** [hypothesis/h#8363]
User Story #1: When searching by a standard annotation tag, through the API, we would like to have the ability to see a visual list of all the annotations, much like the hypothe.is group dashboard.  
Currently when we link the annotations through the API to our ClinGen Variant curation Interface, if there are more than one tag for a given tag (e.g., variant ID) we will not see the list, but only the first annotation.

Example:  Variant ID  where tag has been annotated multiple tags.
Tag:  CAID:CA375717704

![Image](https://github.com/hypothesis/h/assets/66852962/31704602-f7fa-4e51-91c6-3185e4a5b840)

If each paper was expanded you would see all 4 annotations.

Variant Curation Interface view of the links:

![Image](https://github.com/hypothesis/h/assets/66852962/c7326af0-2055-4d20-b15b-9bc096d51368)

Variant curation interface link view (after clicking the “4 Baseline Community Annotations”) above:

![Image](https://github.com/hypothesis/h/assets/66852962/2fffe40d-5cf9-4a33-bbfe-5f8338b316a5)

Takes the user to the first paper, and they never have the chance to see the other 3, unless they become a member of the annotation group itself.

Bradford:
And I don't think it's federation from the standpoint of where the annotations are stored (correct me if I'm wrong, Matt), but the ability to distribute the administration of things like group membership, since there are so many groups, we have different coordinators to do that.
Bradford Powell
1:07 PM
Ideally the coordinators could do that through an API (so we could front something from them from existing systems, or even automatically add/remove hyp.is group members when we manage that membership in our systems.

Pull requests closed multiple times w/ no comment. (Bradford: see https://github.com/hypothesis/h/issues/7572 for my somewhat tongue-in-cheek bug report about lack of review of pull requests…)

![Image](https://github.com/hypothesis/h/assets/66852962/6bec05cd-2575-425d-b892-a9feddb693a4)

Structured/Approved Tags within the institute (or per group). When we query the API using the hypothes.is link that was created we can slurp the data from the tags into structured fields that correspond to their tag.

**Comment by robertknight** [comment]
I am unclear what this issue is asking for. In Hypothesis, the term "API" refers to our [JSON API](https://h.readthedocs.io/en/latest/api/) which developers can use to read and write data in languages like JavaScript or Python. The API isn't a web page that users can directly access. The only kind of "landing page" it has is the documentation.

It sounds instead like they are asking for enhancements to _activity pages_, which is the search interface at https://hypothes.is/search. On this comment:

> Currently when we link the annotations through the API to our ClinGen Variant curation Interface, if there are more than one tag for a given tag (e.g., variant ID) we will not see the list, but only the first annotation.

Should this have read "more than one annotation for a given tag" or "more than one tag matching the tag query?"

@bpow it sounds like you were part of the discussion. Do you want to clarify?

**Comment by bpow** [comment]
I was part of the call this was discussed on (along with other possible user stories), but do not have full details about this user story. I agree that this sounds like more of a question of forming a direct link to within an activity page rather than of interaction with the API per se. I don't have access to the ClinGen Variant Curation Interface to be able to see how this link is represented there. I will try to clarify with others in ClinGen.

**Comment by courtneythaxton** [comment]
@robertknight  I am happy to help with the top query on an issue we are having being able to show the multiple annotations for a given tag. Our developer that works to link the annotations generated in hypothes.is to our own ClinGen Variant Curation Interface is @markmandell, and the product owner is @wrightmw. Happy to get on a Zoom or virtual call if that is easier.

**Comment by dwhly** [comment]
@courtneythaxton @wrightmw Can u guys maybe create a quick screenshare or video of the issue?  Or provide additonal detail here.  We'll jump on a call later if we need to-- but having the info here will help additional people have the context.

**Comment by markmandell** [comment]
Hi @robertknight, thank you for investigating the issue. Following up on this issue after updating how we link to the variant information. We are now linking to the search page for a given variant by tag. For example: https://hypothes.is/search?q=tag:ClinVarID:1634

Previously, we were displaying the link provided in the API response when searching by group tag and variant ID tag.

**Comment by markmandell** [comment]
I believe the issue was on our end with the link and not an issue with the Hypothesis API. I've updated the link on our site and confirmed with our users that this is the expected result they are looking for.

Previously, we were using the `incontext` link to display a link in our interface to the first annotation returned for that tag/variant ID, for example: https://hyp.is/d9W_uD59Eeu4OzNo4sBZ0g/www.ncbi.nlm.nih.gov/pmc/articles/PMC7494713/ 

where the users want to view a list of annotations for a given variant, https://hypothes.is/search?q=tag:ClinVarID:1634

The group is https://hypothes.is/groups/q9Be5aLa/acadvl-variant-curation for the above variant tag.

**Comment by robertknight** [comment]
> I believe the issue was on our end with the link and not an issue with the Hypothesis API. I've updated the link on our site and confirmed with our users that this is the expected result they are looking for.

Ah, I see. That makes sense. On that basis are you OK if I close this issue?

**Comment by markmandell** [comment]
Sounds good to me, thank you!
