### ISSUE TITLE
[passlib.handlers.bcrypt:WARNING] (trapped) error reading bcrypt version

### ISSUE THREAD

**Issue by wenion** [hypothesis/h#8418]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'

I think the passlib v1.7.4 didn't support bcrypt v4.1.2. There is no __about__.py file in bcrypt v4.1.2 package

**Comment by robertknight** [comment]
To add context, this is a warning that appears in the logs when performing an action in Hypothesis that encrypts a password.

Steps to reproduce in development:

1. Go to http://localhost:5000/account/settings
2. Change your password (the new one can be the same as the old)

The following appears in the logs:

```
web (stderr)         | 2024-03-04 09:37:56,520 [48366] [passlib.handlers.bcrypt:WARNING] (trapped) error reading bcrypt version
web (stderr)         | Traceback (most recent call last):
web (stderr)         |   File "/Users/robert/hypothesis/h/.tox/dev/lib/python3.11/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
web (stderr)         |     version = _bcrypt.__about__.__version__
web (stderr)         |               ^^^^^^^^^^^^^^^^^
web (stderr)         | AttributeError: module 'bcrypt' has no attribute '__about__'
```

The warning on its own is harmless since the `version` variable here is only used to write a message to debug logs. See [upstream code](https://foss.heptapod.net/python-libs/passlib/-/blob/1.7.4/passlib/handlers/bcrypt.py?ref_type=tags#L609):

```py
try:
    version = _bcrypt.__about__.__version__
except:
    log.warning("(trapped) error reading bcrypt version", exc_info=True)
    version = '<unknown>'

log.debug("detected 'bcrypt' backend, version %r", version)
return mixin_cls._finalize_backend_mixin(name, dryrun)
```

**Comment by robertknight** [comment]
Upstream issue: https://foss.heptapod.net/python-libs/passlib/-/issues/190
