### ISSUE TITLE
Index limitations with the `annotation` and `document_uri` tables

### ISSUE THREAD

**Issue by indigobravo** [hypothesis/h#8498]
### Description

Whilst restoring a recent backup of the production `h` database a number of errors relating to index limitations on the `annotation` and `document_uri` tables were encountered. Due to this the indexes on the restored tables do not match production. 

### References

- [Slack: 2024-02-07](https://hypothes-is.slack.com/archives/C1MA4E9B9/p1707310332150309)

**Comment by marcospri** [comment]
## ix__document_uri_uri_normalized

The original issue what not about index but about the unique one that combined a few columns.

[For that the fix was to use md5 in the index
](https://github.com/hypothesis/h/pull/8502)

After that we are still getting an issue in the index on doucment_uri because some values are very large there.

This index is created with:

`CREATE INDEX ix__document_uri_uri_normalized ON public.document_uri USING btree (uri_normalized);`


which currently fails with:

```
ERROR:  index row size 2776 exceeds btree version 4 maximum 2704 for index "ix__document_uri_uri_normalized"
DETAIL:  Index row references tuple (950228,3) in relation "document_uri".
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing
```

[we can find the longest URIs with this query
](https://metabase.hypothes.is/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo1LCJuYXRpdmUiOnsicXVlcnkiOiJzZWxlY3QgaWQsIGRvY3VtZW50X3VyaSwgbGVuZ3RoKHVyaV9ub3JtYWxpemVkKSBcbmZyb20gZG9jdW1lbnRfdXJpIFxud2hlcmUgaWQgaW4gKFxuODg1NDg5Nyxcbjg4NTQ4OTgsXG4xMjM1MzYzNSxcbjEyMzUzNjM2LFxuMTA4MTA0MSxcbjExMzU1MTg1LFxuMTI1NTMyOTUsXG43ODk2NTgyLFxuNzg5NjU4MCxcbjczNTI4OTBcbilcbm9yZGVyIGJ5IGxlbmd0aCh1cmlfbm9ybWFsaXplZCkgZGVzYyBsaW1pdCAxMCIsInRlbXBsYXRlLXRhZ3MiOnt9fSwidHlwZSI6Im5hdGl2ZSJ9LCJkaXNwbGF5IjoidGFibGUiLCJwYXJhbWV0ZXJzIjpbXSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJ0YWJsZS5jb2x1bW5fd2lkdGhzIjpbbnVsbCw3ODBdfX0=) (ids taken from running a much slower query first).


To fix this we need to:
- Limit at the API/service level to the max length of normalized_uri so no new rows make its way to the DB. 

- Change this index to use m5d like the uniquene one.
- **Or** fix the problematic rows (how?) and keep the current index.

**Comment by marcospri** [comment]
## ix__annotation_tags

This index also fails to be created due to rows with tags that are to long.

[For tags we already do validation of the length at the API level](https://github.com/hypothesis/h/pull/8526)

We have to fix the existing tags in the DB.

[Finding long tags in the DB](https://report.hypothes.is/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJzZWxlY3QgbGVuZ3RoKHRhZyksIGlkIGZyb20gKFxuc2VsZWN0IHVubmVzdCh0YWdzKSB0YWcsIGlkIGZyb20gYW5ub3RhdGlvblxuKSBhbm5vX3RhZ3Ncblxub3JkZXIgYnkgbGVuZ3RoIGRlc2MgbGltaXQgMTAwIiwidGVtcGxhdGUtdGFncyI6e319LCJkYXRhYmFzZSI6Mn0sImRpc3BsYXkiOiJ0YWJsZSIsInBhcmFtZXRlcnMiOltdLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=) 


We removed the longest **tags** in the DB to leave the DB in a state where the index can be created again:

https://hypothes-is.slack.com/archives/C4K6M7P5E/p1707842794675309

Sample query to remove the queries:

`update annotation set tags = '{}' where id in (..)`


**This should work on the next restore.**

**Comment by indigobravo** [comment]
I can confirm database restores now complete without error. Thanks for the work on this.
