### ISSUE TITLE
Do authentication in a pop-up

### ISSUE THREAD

**Issue by tilgovi** [hypothesis/h#914]
1) Works around third-party cookie disabling
2) Provides the right separation of concerns for being an OAuth consumer and/or provider
3) Is the right thing to do for user security because it means they only enter passwords in top level frames that show the location bar and SSL status.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).

**Comment by piccolbo** [comment]
There is no sign of this issue on either trello or the dev google group as far as a search for [invalid session] or [third party cookies] tells me. The problem persists. What gives?

**Comment by robertknight** [comment]
@piccolbo - This is on Trello on our Product Backlog board, which unfortunately is not publicly visible. Public feature discussion happens in the https://github.com/hypothesis/vision/ repository. See this issue: https://github.com/hypothesis/vision/issues/211

**Comment by piccolbo** [comment]
I would concur with "unfortunately".  For the record, an allowed cookie pattern of [.*].hypothes.is doesn't do it in chrome, but the naked domain does.

**Comment by nickstenning** [comment]
Hi Antonio, we're very aware of this issue, and we'll get to it as soon as we reasonably can. In the mean time we'd appreciate your patience and respect. Everything we do is given away for free, and people making snarky comments on GitHub doesn't make us more productive.

**Comment by piccolbo** [comment]
Snarky? I just meant to underline and support @robertknight  own opinion that having a subset of issues invisible is a bad idea, not to be snarky but to help it rise to a top priority. That's it. I concur. +1. Me too. That's all there was to it. But it's "snarky" so I will just spend my time on some other project, where people may be willing to actually take feedback, once they asked for it.

**Comment by nickstenning** [comment]
I freely apologise if I misinterpreted you. It's sometimes very hard to tell, and lines like "The problem persists. What gives?" aren't exactly easy to interpret as positive and supportive. To reiterate: we do know about and want to fix this problem. We just also know about and want to fix many, many other problems, too. We'll get to it as soon as we can.
