### ISSUE TITLE
Add pagination to the edit-group-members page (frontend part)

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#9148]
Depends on https://github.com/hypothesis/h/issues/9133.

Designs for how pagination should look can be seen in the mockups here: https://www.figma.com/design/jon1U01LGSLcx7PWtZ9TPZ/Hypothesis---Group-Management?node-id=2677-127&node-type=canvas&t=p3razwyrGsqdX50I-0

**Comment by robertknight** [comment]
Pagination controls are now implemented, with the following differences from the mocks:

1. There is no page size control yet. This is still planned.
2. The pagination control is centered at the bottom rather than placed on the top aligned to the right
3. The previous and next page buttons are larger and have explicit text labels
4. The font size in the pagination controls is 14px (our standard UI text size) instead of 13px
5. For a single-digit page number, the button size is 36x42px rather than 24x24. For touch devices the minimum recommended size is ~40px, for desktop they can be smaller but I would still advise not to go too small.

The nuances of exactly how pagination items are determined is explained in https://github.com/hypothesis/frontend-shared/pull/1829. In brief, the items are chosen to satisfy the following constraints:

- First, last and current pages always visible
- One page before and after current always visible
- Same number of items shown regardless of current page

**Comment by robertknight** [comment]
I added some notes above on the rationale for the current implementation. We may decide to revisit these questions but I will create new issues for that.
